force-app/main/default/objects/Account/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number which should be used in all API calls. Please note that we will not be encrypting the account number in Salesforce side, this will be internally handled by User domain in PayPal.</description>
    <externalId>true</externalId>
    <inlineHelpText>Encrypted Account Number which should be used in API calls.</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <description>Transaction Logs associated with an account</description>
    <label>Transaction Log</label>
    <nameField>
        <label>Transaction Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TransactionsWidgetController.cls
public with sharing class TransactionsWidgetController {
    @AuraEnabled(cacheable=true)
    public static List<Transaction_Log__c> searchTransactions(Id contextId, DateTime startDate, DateTime endDate){
        Customer360APIRequest req = new Customer360APIRequest();
        req.setAccount([SELECT Account.Account_Number_Encrypted__c FROM Case WHERE Id = :contextId].Account);
        req.addToDataCategoriesToBeLoaded(Customer360.DataCategory.TRANSACTIONS);
        req.addToSearchCriteriaToBeLoaded(Customer360.SearchCriteria.TRANSACTIONS_START_DATE, DateTime.newInstance(startDate.date(), Time.newInstance(0,0,0,0)).formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''));
        req.addToSearchCriteriaToBeLoaded(Customer360.SearchCriteria.TRANSACTIONS_END_DATE, DateTime.newInstance(endDate.date(), Time.newInstance(0,0,0,0)).formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''));
        Customer360APIResponse resp = Customer360API.getCustomer360Data(req);
        if(resp.isAPIStatusFailure()){
            throw new TransactionAPIException('Unable to retrieve Transaction data');
        }
        Customer360SO obj = TransactionAPI.mapResponseToCustomer360SO(new Customer360SO(), req, resp);
        return obj.transactions;
    }

    private virtual class TransactionAPIException extends Exception {}
}