force-app/main/default/objects/Account/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number which should be used in all API calls. Please note that we will not be encrypting the account number in Salesforce side, this will be internally handled by User domain in PayPal.</description>
    <externalId>true</externalId>
    <inlineHelpText>Encrypted Account Number which should be used in API calls.</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Channel_Id__c.field-meta.xml
<CustomField>
    <fullName>Channel_Id__c</fullName>
    <description>Unique identifier for the contacted Channel. This could be UCID or Avaya Id for Voice calls, MMT Chat Interaction Id for Chat or Kana Message Id for emails. Case origin and Channel Id will uniquely identify the Salesforce case associated to the contacted channel.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for the contacted channel or selected Case Origin.</inlineHelpText>
    <label>Channel Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ToolInterplayController.cls
public class ToolInterplayController {

    // This is a dummy controller method that should be removed once we implement
    // real controllers to handle all the Tool Interplay messages.

    @AuraEnabled
    public static String dummyCaseCreation(String acctNo)
    {
        Account acct;
        List<Account> accts = [SELECT Id, Account_Number_Encrypted__c, AccountNumber, Name FROM Account WHERE Account_Number_Encrypted__c = :acctNo];

        if ((accts == null) || (accts.size() == 0))
        {
            acct = new Account();
            acct.Name = 'Jennifer Lawrence';
            acct.Account_Number_Encrypted__c = acctNo;
            acct.AccountNumber = acctNo;
            upsert acct Account_Number_Encrypted__c;
            System.debug('New Account Created - ' + acct.Id);
        }
        else
        {
            acct = accts[0];
            System.debug('Account already available - ' + acct.Id);
        }

        Case cs = new Case();
        cs.Origin = 'Phone';
        cs.Status = 'Resolution';
        cs.AccountId = acct.Id;
        cs.Channel_Id__c = String.valueOf(Integer.valueof(Math.random() * 10000));
        insert cs;

        System.debug('New Case Created - ' + cs.Id);
        return cs.Id;
    }
}