force-app/main/default/objects/Account/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number which should be used in all API calls. Please note that we will not be encrypting the account number in Salesforce side, this will be internally handled by User domain in PayPal.</description>
    <externalId>true</externalId>
    <inlineHelpText>Encrypted Account Number which should be used in API calls.</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PayPal_Case__c/PayPal_Case__c.object-meta.xml
<CustomObject>
    <description>Cases created in internal PayPal systems like Disputes, PET, SCM and so on.</description>
    <label>PayPal Case</label>
    <nameField>
        <label>PayPal Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PayPal Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseWidgetController.cls
public with sharing class CaseWidgetController {
    @AuraEnabled(cacheable=true)
    public static List<Paypal_Case__c> searchCases(Id contextId, DateTime startDate, DateTime endDate){
        Customer360APIRequest req = new Customer360APIRequest();
        req.setAccount([SELECT Account.Account_Number_Encrypted__c FROM Case WHERE Id = :contextId].Account);
        req.addToDataCategoriesToBeLoaded(Customer360.DataCategory.CASES);
        req.addToSearchCriteriaToBeLoaded(Customer360.SearchCriteria.CASES_START_DATE, DateTime.newInstance(startDate.date(), Time.newInstance(0,0,0,0)).formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''));
        req.addToSearchCriteriaToBeLoaded(Customer360.SearchCriteria.CASES_END_DATE, DateTime.newInstance(endDate.date(), Time.newInstance(0,0,0,0)).formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''));
        Customer360APIResponse resp = Customer360API.getCustomer360Data(req);
        if(resp.isAPIStatusFailure()){
            throw new TransactionAPIException('Unable to retrieve Case data');
        }
        Customer360SO obj = PayPalCaseAPI.mapResponseToCustomer360SO(new Customer360SO(), req, resp);
        return obj.cases;
    }

    private virtual class TransactionAPIException extends Exception {}
}