force-app/main/default/objects/Account/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number which should be used in all API calls. Please note that we will not be encrypting the account number in Salesforce side, this will be internally handled by User domain in PayPal.</description>
    <externalId>true</externalId>
    <inlineHelpText>Encrypted Account Number which should be used in API calls.</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Prefetch_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Prefetch_Loaded_Time__c</fullName>
    <description>This is a general bucket that indicates when the Prefetch data was last pushed to Salesforce platform. Please note that it is common to think this time will match with loaded time of all individual child objects, which could be true in certain scenarios, but there are possibilities where certain data categories will have different time than this.</description>
    <inlineHelpText>This is a general bucket that indicates when the Prefetch data was last pushed to Salesforce platform. Please note that it is common to think this time will match with loaded time of all individual child objects, which could be true in certain scenarios,</inlineHelpText>
    <label>Prefetch Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wallet_Info_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Info_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Wallet Info Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/Account_Wallet__c.object-meta.xml
<CustomObject>
    <description>Wallet object stores all the financial instruments associated with the account like banks, cards, paypal credit and so on.</description>
    <label>Account Wallet</label>
    <nameField>
        <label>Account Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Wallet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Wallet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Instruments associated with an Account</description>
    <inlineHelpText>Financial Instruments associated with an Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Wallet</relationshipLabel>
    <relationshipName>Account_Wallet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Card_Network__c.field-meta.xml
<CustomField>
    <fullName>Card_Network__c</fullName>
    <description>Card Network - Visa/Mastercard/Amex/Discover/etc.,</description>
    <inlineHelpText>Card Network - Visa/Mastercard/Amex/Discover/etc.,</inlineHelpText>
    <label>Card Network</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation status of the financial instrument</description>
    <inlineHelpText>Confirmation status of the financial instrument</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Credit_Limit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Amount__c</fullName>
    <description>Total credit limit for PayPal Credit product</description>
    <inlineHelpText>Total credit limit for PayPal Credit product</inlineHelpText>
    <label>Credit Limit Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Credit_Limit_Currency__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Currency__c</fullName>
    <description>Credit Limit Currency Code</description>
    <inlineHelpText>Credit Limit Currency Code</inlineHelpText>
    <label>Credit Limit Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Credit_Usage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Usage_Amount__c</fullName>
    <description>Amount of PayPal credit used by the customer</description>
    <inlineHelpText>Amount of PayPal credit used by the customer</inlineHelpText>
    <label>Credit Usage Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Credit_Usage_Currency__c.field-meta.xml
<CustomField>
    <fullName>Credit_Usage_Currency__c</fullName>
    <description>Currency code for the PayPal credit usage</description>
    <inlineHelpText>Currency code for the PayPal credit usage</inlineHelpText>
    <label>Credit Usage Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Customer Name on File. This could be same or different than the one used in the profile/account.</description>
    <inlineHelpText>Customer Name on File.</inlineHelpText>
    <label>Customer Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>Expiry Date for the card or any other applicable financial instrument</description>
    <inlineHelpText>Expiry Date for the card or any other applicable financial instrument</inlineHelpText>
    <label>Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Financial_Instrument_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Financial_Instrument_Subtype__c</fullName>
    <description>Financial Instrument Subtype - For card it could be Credit/Debit, For bank it could be checking/saving and so on.</description>
    <inlineHelpText>Financial Instrument Subtype - For card it could be Credit/Debit, For bank it could be checking/saving and so on.</inlineHelpText>
    <label>Financial Instrument Subtype</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Financial_Instrument_Type__c.field-meta.xml
<CustomField>
    <fullName>Financial_Instrument_Type__c</fullName>
    <description>Financial Instrument Type - like Card/Bank/etc.,</description>
    <inlineHelpText>Financial Instrument Type - like Card/Bank/etc.,</inlineHelpText>
    <label>Financial Instrument Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Issuer_Name__c.field-meta.xml
<CustomField>
    <fullName>Issuer_Name__c</fullName>
    <description>Issuer Name for Card/Bank, etc.,</description>
    <inlineHelpText>Issuer Name for Card/Bank, etc.,</inlineHelpText>
    <label>Issuer Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Last_4_digits__c.field-meta.xml
<CustomField>
    <fullName>Last_4_digits__c</fullName>
    <description>Last 4 digits of the card/bank account number/etc.,</description>
    <inlineHelpText>Last 4 digits of the card/bank account number/etc.,</inlineHelpText>
    <label>Last 4 digits</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <description>Card Art, Bank Logo, etc.,</description>
    <inlineHelpText>Card Art, Bank Logo, etc.,</inlineHelpText>
    <label>Logo URL</label>
    <length>1028</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the financial instrument</description>
    <inlineHelpText>Current status of the financial instrument</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Wallet_Id__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Id__c</fullName>
    <description>Unique identifier for the corresponding financial instrument</description>
    <inlineHelpText>Unique identifier for the corresponding financial instrument</inlineHelpText>
    <label>Wallet Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FinancialInstrumentsController.cls
public class FinancialInstrumentsController {

    /* This controller is applicable for Personal, Premier and Business accounts
     * 
     * Please note that this component can be embedded within both case record page as well as 
     * account record page since it supports querying based on both case or account.
     */

    @AuraEnabled(cacheable=true)
    public static FinancialInstrumentsControllerResponse getFinancialInstruments(Id caseId, Id accountId)
    {
        System.debug('FinancialInstrumentsController:getFinancialInstruments Start');

        // Lets set the current execution context as a first step in any transaction
        ExecutionContextUtil.initContextData(PayPalContext.Actor.TEAMMATE, caseId, accountId);
        FinancialInstrumentsControllerResponse response = new FinancialInstrumentsControllerResponse();

        // If both caseId and accountId is NULL, lets stop right here
        if ((caseId == null) && (accountId == null))
        {
            System.debug(LoggingLevel.ERROR, 'Both Case Id and Account Id is null - cannot proceed further');
            response.result.setStatusAndMessage(Customer360.Status.FAILURE, 'Unexpected Error: Both Case Id and Account Id is missing in the request');
            return response;
        }

        List<Account> accountList = new List<Account>();

        // If we have a valid accountId, lets try to load data using that rather than using the caseId
        // Ideally, we could have done this using Dynamic SOQL instead of writing two queries, but we need to 
        // use dynamic SOQL with a caution since it is vulnerable to SQL injection and hence better to avoid it
        // unless the usecase is complex enough to mandate it.
        if (accountId != null)
        {
            accountList = queryAccountWithAccountId(accountId);
            if (accountList.size() == 0)
            {
                // May be the account Id is invalid
                System.debug(LoggingLevel.ERROR, 'Invalid Account Id: accountId - ' + accountId);
                response.result.setStatusAndMessage(Customer360.Status.FAILURE, 'Unexpected Error: Failed to find the account with Account Id passed in the request');
                return response;
            }
        }
        else // query with caseId, if we are here it cannot be null
        {
            accountList = queryAccountWithCaseId(caseId);
            if (accountList.size() == 0)
            {
                // May be the case is not linked to any account, its strange but there is a possiblity
                System.debug(LoggingLevel.ERROR, 'Case Id received is not associated with any account: caseId - ' + caseId);
                response.result.setStatusAndMessage(Customer360.Status.FAILURE, 'Unexpected Error: Case Id passed in the request is not associated with any Account');
                return response;
            }
        }

        Account acc = accountList[0];
        Customer360APIRequest cx360Request = new Customer360APIRequest();
        cx360Request.setAccount(acc);

        /***************************** Wallet Information *****************************/
        if (Customer360Util.isDataNotAvailableLocally(Customer360.DataCategory.WALLET, acc.Wallet_Info_Loaded_Time__c))
        {
            System.debug('Wallet Information needs to be loaded. Last loaded time - ' + acc.Wallet_Info_Loaded_Time__c);
            cx360Request.addToDataCategoriesToBeLoaded(Customer360.DataCategory.WALLET);
        }
        else 
        {
            System.debug('Wallet information is available and fresh enough to use. Last loaded time - ' + acc.Wallet_Info_Loaded_Time__c);
            cx360Request.addToDataCategoriesAvailable(Customer360.DataCategory.WALLET);
            response.financialInstruments = acc.Account_Wallet__r;
        }

        // Great, we are done with data checks needed for Wallet, lets see if we need to load in real time
        if (cx360Request.getDataCategoriesToBeLoaded().size() > 0)
        {
            response = populateResponseUsingCustomer360API(response, cx360Request);
        }
        else {
            // Great, everything we need was retrieved from local objects itself - thanks to pre-fetch tech
            // Lets mark the status as SUCCESS.
            response.result.setStatus(Customer360.Status.SUCCESS);
        }

        System.debug('FinancialInstrumentsController:getFinancialInstruments End');
        return response;
    }

    /* Ths controller returns the same Wallet details as the above one, but without using any Cache
     * There are times where a teammate wants to see a fresh customer data (may be the customer has performed
     * some action in PayPal site/app) that we want to reflect in CS side. Each controller will provide this
     * option to get fresh data. We can decide whether hard refresh is needed or not in UI side.
     */

    @AuraEnabled
    public static FinancialInstrumentsControllerResponse getFinancialInstrumentsWithoutCache(Id caseId, Id accountId)
    {
        System.debug('FinancialInstrumentsControllerResponse:getFinancialInstrumentsWithoutCache - Start');

        // Lets set the current execution context as a first step in any transaction
        ExecutionContextUtil.initContextData(PayPalContext.Actor.TEAMMATE, caseId, accountId);
        FinancialInstrumentsControllerResponse response = new FinancialInstrumentsControllerResponse();

        Account acc = Customer360Util.getBasicAccountDetails(caseId, accountId);
        if (acc == null)
        {
            System.debug(LoggingLevel.ERROR, 'Failed to identify the Account using account id or case id');
            response.result.setStatusAndMessage(Customer360.Status.FAILURE, 'Unexpected Error: Failed to identify the Account using Account Id or Case Id');
            return response;
        }

        Customer360APIRequest cx360Request = new Customer360APIRequest();
        cx360Request.setAccount(acc);

        // No need to check for any data loaded time here, lets go directly for prepping API call
        cx360Request.addToDataCategoriesToBeLoaded(Customer360.DataCategory.WALLET);

        // Make sure CSDAS skips its cache and load data from domain services
        cx360Request.setSkipCacheDataFlag(true);

        response = populateResponseUsingCustomer360API(response, cx360Request);

        // TBD - We should ideally presist the fresh data into local sobjects since teammate would
        // not want to see the old data again after this stage. Lets perform an async update to Database

        System.debug('FinancialInstrumentsControllerResponse:getFinancialInstrumentsWithoutCache - End');
        return response;
    }

    private static FinancialInstrumentsControllerResponse populateResponseUsingCustomer360API(FinancialInstrumentsControllerResponse response, Customer360APIRequest cx360Request)
    {
        // Get the required Customer360 data in real-time
        Customer360APIResponse cx360Response = Customer360API.getCustomer360Data(cx360Request);

        if (cx360Response.isAPIStatusSuccess())
        {
            response.result.setStatus(Customer360.Status.SUCCESS);

            // Go ahead and map the Customer360 API response to Wallet Info
            Customer360SO cx360SO = Customer360API.mapResponseToCustomer360SO(cx360Request, cx360Response);
            response = mapCustomer360SOToWalletInfo(response, cx360SO, cx360Request, cx360Response);
        }
        else
        {
            // There is only one data entity we were trying to load, if it is not SUCCESS, then whole Wallet information is not available
            // We dont need to worry about or handle partial success vs failure in this case
            response.result.setStatusAndMessage(Customer360.Status.FAILURE, 'Failed to load the Data');
            response.result.unavailableDataList.addAll(Customer360.getDescriptionForCategories(cx360Request.getDataCategoriesToBeLoaded()));
        }

        return response;
    }

    private static FinancialInstrumentsControllerResponse mapCustomer360SOToWalletInfo(FinancialInstrumentsControllerResponse response, Customer360SO cx360SO, Customer360APIRequest cx360Request, Customer360APIResponse cx360Response)
    {
        // Map Wallet Info - Simple isn't it?
        response.financialInstruments = cx360SO.financialInstruments;
        return response;
    }

    private static List<Account> queryAccountWithCaseId(Id caseId)
    {
        return [SELECT Id, Account_Number_Encrypted__c, AccountNumber, 
                        (SELECT Id, Wallet_Id__c, Logo_URL__c, Issuer_Name__c, Customer_Name__c, Financial_Instrument_Type__c,
                        Financial_Instrument_Subtype__c, Last_4_digits__c, Expiry_Date__c, Status__c, Confirmation_Status__c,
                        Credit_Limit_Amount__c, Credit_Limit_Currency__c, Credit_Usage_Amount__c, Credit_Usage_Currency__c,
                        Card_Network__c
                        FROM Account_Wallet__r),
                Prefetch_Loaded_Time__c, Wallet_Info_Loaded_Time__c
                FROM Account
                WHERE Id IN (SELECT AccountId FROM Case WHERE Id=:caseId)
               ];
    }

    private static List<Account> queryAccountWithAccountId(Id accountId)
    {
        return [SELECT Id, Account_Number_Encrypted__c, AccountNumber, 
                        (SELECT Id, Wallet_Id__c, Logo_URL__c, Issuer_Name__c, Customer_Name__c, Financial_Instrument_Type__c,
                        Financial_Instrument_Subtype__c, Last_4_digits__c, Expiry_Date__c, Status__c, Confirmation_Status__c,
                        Credit_Limit_Amount__c, Credit_Limit_Currency__c, Credit_Usage_Amount__c, Credit_Usage_Currency__c,
                        Card_Network__c
                        FROM Account_Wallet__r),
                Prefetch_Loaded_Time__c, Wallet_Info_Loaded_Time__c
                FROM Account WHERE Id=:accountId
               ];
    }
}