force-app/main/default/objects/Account/fields/Account_Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Account_Created_Time__c</fullName>
    <description>When was the account created, not in Salesforce but in the actual system of record.</description>
    <inlineHelpText>Account created time</inlineHelpText>
    <label>Account Created Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number which should be used in all API calls. Please note that we will not be encrypting the account number in Salesforce side, this will be internally handled by User domain in PayPal.</description>
    <externalId>true</externalId>
    <inlineHelpText>Encrypted Account Number which should be used in API calls.</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status - Open, Locked, Closed, etc.,</description>
    <inlineHelpText>Account Status - Open, Locked, Closed, etc.,</inlineHelpText>
    <label>Account Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type - like Personal / Premier / Business in the tenant side. This could be a candidate for a picklist, but we dont need to put too many restrictions for customer data in the client side since we are not using Salesforce as a source of truth. So, let&apos;s keep it loosely coupled.</description>
    <inlineHelpText>Account Type - like Personal / Premier / Business</inlineHelpText>
    <label>Account Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Unregistered__c.field-meta.xml
<CustomField>
    <fullName>Is_Unregistered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customers can use PayPal without registering for an account or do guest checkout even if they have one. This flag indicated whether the account is registered or not.</description>
    <inlineHelpText>Is this Account not registered yet?</inlineHelpText>
    <label>Is Unregistered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Linked_Accounts_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Linked_Accounts_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Linked Accounts Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Prefetch_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Prefetch_Loaded_Time__c</fullName>
    <description>This is a general bucket that indicates when the Prefetch data was last pushed to Salesforce platform. Please note that it is common to think this time will match with loaded time of all individual child objects, which could be true in certain scenarios, but there are possibilities where certain data categories will have different time than this.</description>
    <inlineHelpText>This is a general bucket that indicates when the Prefetch data was last pushed to Salesforce platform. Please note that it is common to think this time will match with loaded time of all individual child objects, which could be true in certain scenarios,</inlineHelpText>
    <label>Prefetch Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unregistered_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Unregistered_Account_Type__c</fullName>
    <description>If the account is not registered with PayPal, this field will indicate type of the account like Guest, WAX or DCC.</description>
    <inlineHelpText>If the account is not registered with PayPal, this field will indicate type of the account like Guest, WAX or DCC.</inlineHelpText>
    <label>Unregistered Account Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/Linked_Account__c.object-meta.xml
<CustomObject>
    <description>A PayPal account can be indirectly linked to other PayPal accounts by tEmail, Phone, Wallet and so on. This custom object is used to store accounts linked with each other via such category. The initial idea is to create account records for all linked accounts, but creating all those records is absolutely unnecessary unless the teammate wants to switch to one of those accounts. Even in that case, teammates will be switching to only one of those accounts and not to all. We will preserve the minimal details in this object and will create actual account is necessary.</description>
    <label>Linked Account</label>
    <nameField>
        <label>Linked Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Linked Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Linked_Account__c/fields/Account1__c.field-meta.xml
<CustomField>
    <fullName>Account1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account in one side of the linking</description>
    <inlineHelpText>Account in one side of the linking</inlineHelpText>
    <label>Account1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Linked Accounts (Account1)</relationshipLabel>
    <relationshipName>Linked_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Account_Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Account_Created_Time__c</fullName>
    <description>Account Created Time</description>
    <inlineHelpText>Account Created Time</inlineHelpText>
    <label>Account Created Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Account Number</description>
    <inlineHelpText>Account Number</inlineHelpText>
    <label>Account Number</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number</description>
    <inlineHelpText>Encrypted Account Number</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status</description>
    <inlineHelpText>Account Status</inlineHelpText>
    <label>Account Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type</description>
    <inlineHelpText>Account Type</inlineHelpText>
    <label>Account Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Full Name of the linked account</description>
    <inlineHelpText>Full Name of the linked account</inlineHelpText>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Has_Strong_Link__c.field-meta.xml
<CustomField>
    <fullName>Has_Strong_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether account1 and account2 are strongly linked so that there is no need for validation while switching to that account.</description>
    <inlineHelpText>Indicates whether account1 and account2 are strongly linked so that there is no need for validation while switching to that account.</inlineHelpText>
    <label>Has Strong Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Is_Unregistered__c.field-meta.xml
<CustomField>
    <fullName>Is_Unregistered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Unregistered</description>
    <inlineHelpText>Is Unregistered</inlineHelpText>
    <label>Is Unregistered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Unregistered_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Unregistered_Account_Type__c</fullName>
    <description>Unregistered Account Type</description>
    <inlineHelpText>Unregistered Account Type</inlineHelpText>
    <label>Unregistered Account Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account_Attributes__c/Linked_Account_Attributes__c.object-meta.xml
<CustomObject>
    <description>Attributes by which two accounts are linked. It could be by name, email, phone or financial instruments.</description>
    <label>Linked Account Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Linked Account Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linked_Account_Attributes__c/fields/Attribute_Value__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value__c</fullName>
    <description>Value of that attribute that is matching between accounts. It could be the name or email address or phone number, etc., This values is required to identify the exact value that is matching since there is a possibility of account having multiple data points (like multiple emails) out of which one could match.</description>
    <inlineHelpText>Value of that attribute that is matching between accounts.</inlineHelpText>
    <label>Attribute Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account_Attributes__c/fields/Has_Strong_Link__c.field-meta.xml
<CustomField>
    <fullName>Has_Strong_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the attribute is strongly linked or not. For e.g., an inactive email in account 1 could be matching with active email in account 2. In this case, we will consider these accounts as linked and it is linked by email address, but it is not a strong link for validation purposes since the email is inactive in an account.</description>
    <inlineHelpText>Is the attribute strongly linked?</inlineHelpText>
    <label>Has Strong Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linked_Account_Attributes__c/fields/Linked_Account__c.field-meta.xml
<CustomField>
    <fullName>Linked_Account__c</fullName>
    <description>Attributes by which two accounts are linked.</description>
    <inlineHelpText>Attributes by which two accounts are linked.</inlineHelpText>
    <label>Linked Account</label>
    <referenceTo>Linked_Account__c</referenceTo>
    <relationshipLabel>Linked Account Attributes</relationshipLabel>
    <relationshipName>Linked_Account_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linked_Account_Attributes__c/fields/Response_JSON__c.field-meta.xml
<CustomField>
    <fullName>Response_JSON__c</fullName>
    <description>The JSON string that contains the linked attribute details are stored in this field. Ideally, we would like to explode the whole data into the object, but given that Salesforce is not the system of record, we don&apos;t need to complicate unless it is absolutely necessary.</description>
    <inlineHelpText>The JSON string that contains the linked attribute details.</inlineHelpText>
    <label>Response JSON</label>
    <length>8192</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LinkedAccountsController.cls
public class LinkedAccountsController {

    /* This controller is applicable for personal, premier and business accounts.
     * The business accounts has even more nuances link MUMA which are not handled in the
     * current implementation, but eventually we will end up dealing with all linked accounts - 
     * either the direct links which is mostly common among business accounts or the indirect relationships
     * which are mostly common among consumer accounts but somtimes applicable even for business accounts.
     * 
     * Please note that this component can be embedded within both case record page as well as 
     * account record page since it supports querying based on both case or account.
     */

    @AuraEnabled(cacheable=true)
    public static LinkedAccountsControllerResponse getLinkedAccounts(Id caseId, Id accountId)
    {
        System.debug('LinkedAccountsController:getLinkedAccounts Start');

        // Lets set the current execution context as a first step in any transaction
        ExecutionContextUtil.initContextData(PayPalContext.Actor.TEAMMATE, caseId, accountId);
        LinkedAccountsControllerResponse response = new LinkedAccountsControllerResponse();

        // If both caseId and accountId is NULL, lets stop right here
        if ((caseId == null) && (accountId == null))
        {
            System.debug(LoggingLevel.ERROR, 'Both Case Id and Account Id is null - cannot proceed further');
            response.result.setStatusAndMessage(Customer360.Status.FAILURE, 'Unexpected Error: Both Case Id and Account Id is missing in the request');
            return response;
        }

        List<Account> accountList = new List<Account>();

        // If we have a valid accountId, lets try to load data using that rather than using the caseId
        // Ideally, we could have done this using Dynamic SOQL instead of writing two queries, but we need to 
        // use dynamic SOQL with a caution since it is vulnerable to SQL injection and hence better to avoid it
        // unless the usecase is complex enough to mandate it.
        if (accountId != null)
        {
            accountList = queryAccountWithAccountId(accountId);
            if (accountList.size() == 0)
            {
                // May be the account Id is invalid
                System.debug(LoggingLevel.ERROR, 'Invalid Account Id: accountId - ' + accountId);
                response.result.setStatusAndMessage(Customer360.Status.FAILURE, 'Unexpected Error: Failed to find the account with Account Id passed in the request');
                return response;
            }
        }
        else // query with caseId, if we are here it cannot be null
        {
            accountList = queryAccountWithCaseId(caseId);
            if (accountList.size() == 0)
            {
                // May be the case is not linked to any account, its strange but there is a possiblity
                System.debug(LoggingLevel.ERROR, 'Case Id received is not associated with any account: caseId - ' + caseId);
                response.result.setStatusAndMessage(Customer360.Status.FAILURE, 'Unexpected Error: Case Id passed in the request is not associated with any Account');
                return response;
            }
        }

        Account acc = accountList[0];
        Customer360APIRequest cx360Request = new Customer360APIRequest();
        cx360Request.setAccount(acc);

        /***************************** Linked Accounts *****************************/
        if (Customer360Util.isDataNotAvailableLocally(Customer360.DataCategory.LINKED_ACCOUNTS, acc.Linked_Accounts_Loaded_Time__c))
        {
            System.debug('Linked Accounts needs to be loaded. Last loaded time - ' + acc.Linked_Accounts_Loaded_Time__c);
            cx360Request.addToDataCategoriesToBeLoaded(Customer360.DataCategory.LINKED_ACCOUNTS);
        }
        else 
        {
            System.debug('Linked Accounts is available and fresh enough to use. Last loaded time - ' + acc.Linked_Accounts_Loaded_Time__c);
            cx360Request.addToDataCategoriesAvailable(Customer360.DataCategory.LINKED_ACCOUNTS);
            response = mapLinkedAccounts(response, acc.Linked_Accounts1__r);
        }

        // Great, we are done with data checks needed for Linked Accounts, lets see if we need to load in real time
        if (cx360Request.getDataCategoriesToBeLoaded().size() > 0)
        {
            response = populateResponseUsingCustomer360API(response, cx360Request);
        }
        else {
            // Great, everything we need was retrieved from local objects itself - thanks to pre-fetch tech
            // Lets mark the status as SUCCESS.
            response.result.setStatus(Customer360.Status.SUCCESS);
        }

        System.debug('LinkedAccountsController:getLinkedAccounts End');
        return response;
    }

    /* Ths controller returns the same Linked Accounts as the above one, but without using any Cache
     * There are times where a teammate wants to see a fresh customer data (may be the customer has performed
     * some action in PayPal site/app) that we want to reflect in CS side. Each controller will provide this
     * option to get fresh data. We can decide whether hard refresh is needed or not in UI side.
     */

    @AuraEnabled
    public static LinkedAccountsControllerResponse getLinkedAccountsWithoutCache(Id caseId, Id accountId)
    {
        System.debug('LinkedAccountsController:getLinkedAccountsWithoutCache - Start');

        // Lets set the current execution context as a first step in any transaction
        ExecutionContextUtil.initContextData(PayPalContext.Actor.TEAMMATE, caseId, accountId);
        LinkedAccountsControllerResponse response = new LinkedAccountsControllerResponse();

        Account acc = Customer360Util.getBasicAccountDetails(caseId, accountId);
        if (acc == null)
        {
            System.debug(LoggingLevel.ERROR, 'Failed to identify the Account using account id or case id');
            response.result.setStatusAndMessage(Customer360.Status.FAILURE, 'Unexpected Error: Failed to identify the Account using Account Id or Case Id');
            return response;
        }

        Customer360APIRequest cx360Request = new Customer360APIRequest();
        cx360Request.setAccount(acc);

        // No need to check for any data loaded time here, lets go directly for prepping API call
        cx360Request.addToDataCategoriesToBeLoaded(Customer360.DataCategory.LINKED_ACCOUNTS);

        // Make sure CSDAS skips its cache and load data from domain services
        cx360Request.setSkipCacheDataFlag(true);

        response = populateResponseUsingCustomer360API(response, cx360Request);

        // TBD - We should ideally presist the fresh data into local sobjects since teammate would
        // not want to see the old data again after this stage. Lets perform an async update to Database

        System.debug('LinkedAccountsController:getLinkedAccountsWithoutCache - End');
        return response;
    }

    private static LinkedAccountsControllerResponse populateResponseUsingCustomer360API(LinkedAccountsControllerResponse response, Customer360APIRequest cx360Request)
    {
        // Get the required Customer360 data in real-time
        Customer360APIResponse cx360Response = Customer360API.getCustomer360Data(cx360Request);

        if (cx360Response.isAPIStatusSuccess())
        {
            response.result.setStatus(Customer360.Status.SUCCESS);

            // Go ahead and map the Customer360 API response to Linked Accounts
            Customer360SO cx360SO = Customer360API.mapResponseToCustomer360SO(cx360Request, cx360Response);
            response.linkedAccounts = cx360SO.linkedAccounts;
        }
        else
        {
            // There is only one data entity we were trying to load, if it is not SUCCESS, then whole Linked Accounts is not available
            // We dont need to worry about or handle partial success vs failures in this case
            response.result.setStatusAndMessage(Customer360.Status.FAILURE, 'Failed to load the Data');
            response.result.unavailableDataList.addAll(Customer360.getDescriptionForCategories(cx360Request.getDataCategoriesToBeLoaded()));
        }

        return response;
    }

    private static LinkedAccountsControllerResponse mapLinkedAccounts(LinkedAccountsControllerResponse response, List<Linked_Account__c> linkedAccounts)
    {
        if ((linkedAccounts == null) || (linkedAccounts.size() == 0))
        {
            System.debug('There are no linked accounts associated with the account');
            return response;
        }

        Map<Id, LinkedAccountSO> linkedAccountsSOMap = new Map<Id, LinkedAccountSO>();
        List<Id> linkedAccountIds = new List<Id>();

        // Iterate through each linked account and create a map of SOs and collect Ids as well in the process
        for (Linked_Account__c lacct : linkedAccounts)
        {
            LinkedAccountSO lacctSO = new LinkedAccountSO();
            lacctSO.linkedAccount = lacct;
            linkedAccountsSOMap.put(lacct.Id, lacctSO);
            linkedAccountIds.add(lacct.Id);
        }

        // Query all linked account attributes using the linked account Ids collected above
        List<Linked_Account_Attributes__c> lacctAttributes = queryLinkedAccountAttributesWithIds(linkedAccountIds);
        if (lacctAttributes != null)
        {
            for (Linked_Account_Attributes__c attribute : lacctAttributes)
            {
                LinkedAccountSO lacctSO = linkedAccountsSOMap.get(attribute.Linked_Account__c);
                if (lacctSO == null)
                {
                    // This cannot happen by any chance, but still we need to handle this scenario as a developer
                    System.debug(LoggingLevel.ERROR, 'LinkedAccountSO object in the map is unexpectedly missing');
                    continue;
                }
                lacctSO.attributes.add(LinkedAccountAPI.mapLinkedAccountAttributeObjToSO(attribute));
            }
        }

        response.linkedAccounts = linkedAccountsSOMap.values();
        return response;
    }

    private static List<Account> queryAccountWithCaseId(Id caseId)
    {
        return [SELECT Id, Account_Number_Encrypted__c, AccountNumber, 
                        (SELECT Id, Full_Name__c, Account_Number__c, Account_Number_Encrypted__c, Account_Type__c, Account_Created_Time__c, 
                        Account_Status__c, Has_Strong_Link__c, Is_Unregistered__c, Unregistered_Account_Type__c
                        FROM Linked_Accounts1__r),
                Prefetch_Loaded_Time__c, Linked_Accounts_Loaded_Time__c
                FROM Account
                WHERE Id IN (SELECT AccountId FROM Case WHERE Id=:caseId)
               ];
    }

    private static List<Account> queryAccountWithAccountId(Id accountId)
    {
        return [SELECT Id, Account_Number_Encrypted__c, AccountNumber, 
                        (SELECT Id, Full_Name__c, Account_Number__c, Account_Number_Encrypted__c, Account_Type__c, Account_Created_Time__c, 
                        Account_Status__c, Has_Strong_Link__c, Is_Unregistered__c, Unregistered_Account_Type__c
                        FROM Linked_Accounts1__r),
                Prefetch_Loaded_Time__c, Linked_Accounts_Loaded_Time__c
                FROM Account WHERE Id=:accountId
               ];
    }

    private static List<Linked_Account_Attributes__c> queryLinkedAccountAttributesWithIds(List<Id> linkedAccountIds)
    {
        return [SELECT Id, Name, Attribute_Value__c, Has_Strong_Link__c, Response_JSON__c, Linked_Account__c
                FROM Linked_Account_Attributes__c
                WHERE Linked_Account__c = :linkedAccountIds
               ];
    }
}