force-app/main/default/objects/Account/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number which should be used in all API calls. Please note that we will not be encrypting the account number in Salesforce side, this will be internally handled by User domain in PayPal.</description>
    <externalId>true</externalId>
    <inlineHelpText>Encrypted Account Number which should be used in API calls.</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Prefetch_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Prefetch_Loaded_Time__c</fullName>
    <description>This is a general bucket that indicates when the Prefetch data was last pushed to Salesforce platform. Please note that it is common to think this time will match with loaded time of all individual child objects, which could be true in certain scenarios, but there are possibilities where certain data categories will have different time than this.</description>
    <inlineHelpText>This is a general bucket that indicates when the Prefetch data was last pushed to Salesforce platform. Please note that it is common to think this time will match with loaded time of all individual child objects, which could be true in certain scenarios,</inlineHelpText>
    <label>Prefetch Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cache_Duration__mdt/Cache_Duration__mdt.object-meta.xml
<CustomObject>
    <description>When we bring the data via APIs into Salesforce, irrespective of whether it is from PayPal or from other sources, we need to decide how log we can keep it without worrying about its freshness. Obviously the best way is to get the data from system of record always so that its fresh. But that will have performance implications and hence we need to strike a balance. This configuration will help with that.</description>
    <label>Cache Duration</label>
    <pluralLabel>Cache Duration</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cache_Duration__mdt/fields/Cache_Time__c.field-meta.xml
<CustomField>
    <fullName>Cache_Time__c</fullName>
    <description>Cache Time in Minutes - Duration for which the data is considered valid</description>
    <inlineHelpText>Cache Time in Minutes - Duration for which the data is considered valid</inlineHelpText>
    <label>Cache Time</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PrefetchUtil.cls
public class PrefetchUtil {
    private static Integer prefetchDataValidityTime = null;
    private static Integer prefetchInProgressWaitingTime = null;

    // Time for which the prefetched data is considered as valid
    public static Integer getPrefetchDataValidityTime()
    {
        if(prefetchDataValidityTime != null)
        {
            System.debug('Returned Prefetch validity time - ' + prefetchDataValidityTime + ' minutes');
            return prefetchDataValidityTime;
        }

        Cache_Duration__mdt cacheTime = [SELECT Cache_Time__c FROM Cache_Duration__mdt 
                                         WHERE MasterLabel='PayPalDefault' LIMIT 1];
        prefetchDataValidityTime = (Integer) cacheTime.Cache_Time__c;

        System.debug('Derived Prefetch validity time - ' + prefetchDataValidityTime + ' minutes');
        return prefetchDataValidityTime;
    }

    // Time for which we can wait for the triggered pre-fetch to Complete before we need to give up and
    // trigger a new prefetch request
    public static Integer getPrefetchInProgressWaitingTime()
    {
        if(prefetchInProgressWaitingTime != null)
        {
            System.debug('Returned In-Progress Prefetch waiting time - ' + prefetchInProgressWaitingTime + ' minutes');
            return prefetchInProgressWaitingTime;
        }

        Cache_Duration__mdt cacheTime = [SELECT Cache_Time__c FROM Cache_Duration__mdt 
                                         WHERE MasterLabel='PrefetchInProgressDuration' LIMIT 1];
        prefetchInProgressWaitingTime = (Integer) cacheTime.Cache_Time__c;

        System.debug('Derived In-Progress Prefetch waiting time - ' + prefetchInProgressWaitingTime + ' minutes');
        return prefetchInProgressWaitingTime;
    }

    // This method is a hook that can be used by other flows to trigger a prefetch in case it suspects that the
    // data is not prefetched already or is not fresh enough to use. For instance an UI component should ideally have
    // all the data required for it locally, but if it ends up calling API real-time for partial or full data, then it
    // will suspect whether the data is not pre-fetched before and call this method to investigate and act
    public static void checkAndTriggerPrefetchAsync(Account acct)
    {
        if ((acct == null) || (String.isBlank(acct.Account_Number_Encrypted__c)))
        {
            System.debug('Account object or encrypted account number passed in the request is null - cannot evaluate further or trigger prefetch');
            return;
        }

        if ((acct.Prefetch_Loaded_Time__c == null) || 
                (DateTime.now().addMinutes(PrefetchUtil.getPrefetchDataValidityTime() * -1) > acct.Prefetch_Loaded_Time__c))
        {
            // Prefetch data is not available locally, we need to trigger a pre-fetch
            TriggerPrefetchAsync prefetchTriggerJob = new TriggerPrefetchAsync(acct.Account_Number_Encrypted__c, true, true, ExecutionContextUtil.getContextDataAsJSON());
            ID jobId = System.enqueueJob(prefetchTriggerJob);
            System.debug('Successfully queued the prefetch trigger request. Job Id - ' + jobId);
        }

        System.debug('No need to trigger prefetch. Data is available locally and is fresh enough to use. Last loaded time - ' + acct.Prefetch_Loaded_Time__c);
    }
}