force-app/main/default/objects/Account/fields/Account_Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Account_Created_Time__c</fullName>
    <description>When was the account created, not in Salesforce but in the actual system of record.</description>
    <inlineHelpText>Account created time</inlineHelpText>
    <label>Account Created Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Manager_Flags_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Account_Manager_Flags_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Account Manager Flags Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number which should be used in all API calls. Please note that we will not be encrypting the account number in Salesforce side, this will be internally handled by User domain in PayPal.</description>
    <externalId>true</externalId>
    <inlineHelpText>Encrypted Account Number which should be used in API calls.</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status - Open, Locked, Closed, etc.,</description>
    <inlineHelpText>Account Status - Open, Locked, Closed, etc.,</inlineHelpText>
    <label>Account Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Account_Subtype__c</fullName>
    <description>Account&apos;s subtype. Not all account types or countries has a subtype, but this field is created to handle in scenarios where it is needed.</description>
    <inlineHelpText>Account subtype - like No Balance/PayPal Cash/PayPal Cash Plus account in case of Personal</inlineHelpText>
    <label>Account Subtype</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type - like Personal / Premier / Business in the tenant side. This could be a candidate for a picklist, but we dont need to put too many restrictions for customer data in the client side since we are not using Salesforce as a source of truth. So, let&apos;s keep it loosely coupled.</description>
    <inlineHelpText>Account Type - like Personal / Premier / Business</inlineHelpText>
    <label>Account Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ActivityLog_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>ActivityLog_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>ActivityLog Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Basic_Profile_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Basic_Profile_Loaded_Time__c</fullName>
    <description>For Cache or TTL purposes.</description>
    <inlineHelpText>For Cache or TTL purposes.</inlineHelpText>
    <label>Basic Profile Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Info_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Business_Info_Loaded_Time__c</fullName>
    <description>For cache TTL Purposes</description>
    <inlineHelpText>For cache TTL Purposes</inlineHelpText>
    <label>Business Info Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/CIP_Status__c.field-meta.xml
<CustomField>
    <fullName>CIP_Status__c</fullName>
    <description>Customer&apos;s CIP status, basically the KYC.</description>
    <inlineHelpText>CIP status of the customer</inlineHelpText>
    <label>CIP Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Compliance_Info_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Info_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Compliance Info Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>ISO Country Code for the account&apos;s legal country</description>
    <inlineHelpText>ISO Country Code for the account&apos;s legal country</inlineHelpText>
    <label>Country Code</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>Customer&apos;s legal country name</description>
    <inlineHelpText>Customer&apos;s legal country name</inlineHelpText>
    <label>Country Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>Segment the customer belongs to</description>
    <inlineHelpText>Segment the customer belongs to</inlineHelpText>
    <label>Customer Segment</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Unregistered__c.field-meta.xml
<CustomField>
    <fullName>Is_Unregistered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customers can use PayPal without registering for an account or do guest checkout even if they have one. This flag indicated whether the account is registered or not.</description>
    <inlineHelpText>Is this Account not registered yet?</inlineHelpText>
    <label>Is Unregistered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Limitation_Info_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Limitation_Info_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Limitation Info Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Linked_Accounts_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Linked_Accounts_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Linked Accounts Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Customer&apos;s location within the country - like City</description>
    <inlineHelpText>Customer&apos;s location within the country - like City</inlineHelpText>
    <label>Location</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/No_of_Secondary_Users__c.field-meta.xml
<CustomField>
    <fullName>No_of_Secondary_Users__c</fullName>
    <description>Total number of secondary users associated with the business account</description>
    <inlineHelpText>Total number of secondary users associated with the business account</inlineHelpText>
    <label>No of Secondary Users</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PayPal_Cases_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>PayPal_Cases_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>PayPal Cases Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Prefetch_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Prefetch_Loaded_Time__c</fullName>
    <description>This is a general bucket that indicates when the Prefetch data was last pushed to Salesforce platform. Please note that it is common to think this time will match with loaded time of all individual child objects, which could be true in certain scenarios, but there are possibilities where certain data categories will have different time than this.</description>
    <inlineHelpText>This is a general bucket that indicates when the Prefetch data was last pushed to Salesforce platform. Please note that it is common to think this time will match with loaded time of all individual child objects, which could be true in certain scenarios,</inlineHelpText>
    <label>Prefetch Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Previous_Interactions_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Previous_Interactions_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Previous Interactions Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Info_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Product_Info_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Product Info Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_User_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Secondary_User_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Secondary User Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/ServiceLog_Notes_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>ServiceLog_Notes_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>ServiceLog Notes Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <description>Customer&apos;s timezone. This might be required to display some data like transaction log in customer&apos;s timezone rather than teammate&apos;s.</description>
    <inlineHelpText>Customer&apos;s timezone.</inlineHelpText>
    <label>Timezone</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TransactionLog_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>TransactionLog_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>TransactionLog Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unregistered_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Unregistered_Account_Type__c</fullName>
    <description>If the account is not registered with PayPal, this field will indicate type of the account like Guest, WAX or DCC.</description>
    <inlineHelpText>If the account is not registered with PayPal, this field will indicate type of the account like Guest, WAX or DCC.</inlineHelpText>
    <label>Unregistered Account Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wallet_Info_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Info_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Wallet Info Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Channel_Id__c.field-meta.xml
<CustomField>
    <fullName>Channel_Id__c</fullName>
    <description>Unique identifier for the contacted Channel. This could be UCID or Avaya Id for Voice calls, MMT Chat Interaction Id for Chat or Kana Message Id for emails. Case origin and Channel Id will uniquely identify the Salesforce case associated to the contacted channel.</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique identifier for the contacted channel or selected Case Origin.</inlineHelpText>
    <label>Channel Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Address_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Address Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Customer&apos;s Age</description>
    <inlineHelpText>Customer&apos;s Age</inlineHelpText>
    <label>Age</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CIP_Status__c.field-meta.xml
<CustomField>
    <fullName>CIP_Status__c</fullName>
    <description>Customer&apos;s CIP status</description>
    <inlineHelpText>Customer&apos;s CIP status</inlineHelpText>
    <label>CIP Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Email_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Email Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Full Name of the customer. This value comes from PayPal domain and we need a separate field since Name in Contact object is not writable.</description>
    <inlineHelpText>Full Name of the customer.</inlineHelpText>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <description>Party Id that identifies the User/Party in PayPal system</description>
    <externalId>true</externalId>
    <inlineHelpText>Party Id that identifies the User/Party in PayPal system</inlineHelpText>
    <label>Party Id</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <description>Customer&apos;s profile picture</description>
    <inlineHelpText>Customer&apos;s profile picture</inlineHelpText>
    <label>Profile Picture</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestQuickGlanceController.cls
@isTest
public class TestQuickGlanceController {
private static Account createAccount(String Name, String AccountNumber){
        
        Account acct = new Account();
acct.Name = Name;
acct.Account_Number_Encrypted__c = 'AccountNumber';
acct.AccountNumber = AccountNumber;
acct.Account_Type__c = 'Personal';
acct.Account_Subtype__c = 'PayPal Cash Plus';
acct.Account_Status__c = 'Open';
acct.Location__c = 'San Jose';
acct.Country_Code__c = 'US';
acct.Country_Name__c = 'United States';
acct.Timezone__c = 'PST';
acct.Account_Created_Time__c = DateTime.newInstance(2015, 03, 01, 09, 00, 00);
acct.Customer_Segment__c = 'Likely To Churn';
acct.No_of_Secondary_Users__c = 0;
acct.CIP_Status__c = 'In-Progress';
acct.Is_Unregistered__c = false;
acct.Unregistered_Account_Type__c = '';
        

acct.ActivityLog_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Basic_Profile_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Compliance_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Account_Manager_Flags_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Limitation_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Business_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Linked_Accounts_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.PayPal_Cases_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Previous_Interactions_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Product_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Secondary_User_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.ServiceLog_Notes_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.TransactionLog_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Wallet_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Prefetch_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);

insert acct;
System.debug(JSON.serialize(acct.Id));
        return acct;
    }
    
    
private static Case createCaseid(String Name, String AccountNumber){
        
Account acct = new Account();
acct.Name = Name;
acct.Account_Number_Encrypted__c = 'AccountNumber';
acct.AccountNumber = AccountNumber;
acct.Account_Type__c = 'Personal';
acct.Account_Subtype__c = 'PayPal Cash Plus';
acct.Account_Status__c = 'Open';
acct.Location__c = 'San Jose';
acct.Country_Code__c = 'US';
acct.Country_Name__c = 'United States';
acct.Timezone__c = 'PST';
acct.Account_Created_Time__c = DateTime.newInstance(2015, 03, 01, 09, 00, 00);
acct.Customer_Segment__c = 'Likely To Churn';
acct.No_of_Secondary_Users__c = 0;
acct.CIP_Status__c = 'In-Progress';
acct.Is_Unregistered__c = false;
acct.Unregistered_Account_Type__c = '';
        

acct.ActivityLog_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Basic_Profile_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Compliance_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Account_Manager_Flags_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Limitation_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Business_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Linked_Accounts_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.PayPal_Cases_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Previous_Interactions_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Product_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Secondary_User_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.ServiceLog_Notes_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.TransactionLog_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Wallet_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Prefetch_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);

insert acct;
System.debug(JSON.serialize(acct.Id));

Case cs = new Case();
cs.Origin = 'Phone';
cs.Channel_Id__c = '10002';
cs.Status = 'Resolution';
cs.AccountId = acct.id;
insert cs;
System.debug(JSON.serialize(cs.Id));       
       return cs;
    }

    private static Case createCaseIdWoAccount(){
Case cs = new Case();
cs.Origin = 'Phone';
cs.Channel_Id__c = '10002';
cs.Status = 'Resolution';
insert cs;
System.debug(JSON.serialize(cs.Id));       
       return cs;
    }    
    
    
    
    
private static Account createNoLimitAccountFlag(String Name, String AccountNumber){
        
Account acct = new Account();
acct.Name = Name;
acct.Account_Number_Encrypted__c = 'AccountNumber';
acct.AccountNumber = AccountNumber;
acct.Account_Type__c = 'Personal';
acct.Account_Subtype__c = 'PayPal Cash Plus';
acct.Account_Status__c = 'Open';
acct.Location__c = 'San Jose';
acct.Country_Code__c = 'US';
acct.Country_Name__c = 'United States';
acct.Timezone__c = 'PST';
acct.Account_Created_Time__c = DateTime.newInstance(2015, 03, 01, 09, 00, 00);
acct.Customer_Segment__c = 'Likely To Churn';
acct.No_of_Secondary_Users__c = 0;
acct.CIP_Status__c = 'In-Progress';
acct.Is_Unregistered__c = false;
acct.Unregistered_Account_Type__c = '';
        

acct.ActivityLog_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Basic_Profile_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Business_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Linked_Accounts_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.PayPal_Cases_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Previous_Interactions_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Product_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Secondary_User_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.ServiceLog_Notes_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.TransactionLog_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Wallet_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Prefetch_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);

insert acct;
System.debug(JSON.serialize(acct.Id));
        return acct;
    }    


    
   private static Contact createContactRelationId(String Name, String AccountNumber){
        
        Account acct = new Account();
acct.Name = Name;
acct.Account_Number_Encrypted__c = 'AccountNumber';
acct.AccountNumber = AccountNumber;
acct.Account_Type__c = 'Personal';
acct.Account_Subtype__c = 'PayPal Cash Plus';
acct.Account_Status__c = 'Open';
acct.Location__c = 'San Jose';
acct.Country_Code__c = 'US';
acct.Country_Name__c = 'United States';
acct.Timezone__c = 'PST';
acct.Account_Created_Time__c = DateTime.newInstance(2015, 03, 01, 09, 00, 00);
acct.Customer_Segment__c = 'Likely To Churn';
acct.No_of_Secondary_Users__c = 0;
acct.CIP_Status__c = 'In-Progress';
acct.Is_Unregistered__c = false;
acct.Unregistered_Account_Type__c = '';
        

acct.ActivityLog_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Basic_Profile_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Compliance_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Account_Manager_Flags_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Limitation_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Business_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Linked_Accounts_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.PayPal_Cases_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Previous_Interactions_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Product_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Secondary_User_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.ServiceLog_Notes_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.TransactionLog_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Wallet_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Prefetch_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);

insert acct;
System.debug(JSON.serialize(acct.Id));

       
Contact ct = new Contact();
ct.Party_Id__c = '1334781826176083630';
ct.Full_Name__c = 'Jennifer Lawrence';
ct.FirstName = 'Jennifer';
ct.LastName = 'Lawrence';
ct.Profile_Picture__c = 'https://msmaster.qa.paypal.com:14870/v1/content/media-containers/PICS/cdn-assets/00/p/OGY0MmMyZDAtMmY5Zi00YTIyLWJkNzUtYTE1YTQwYjEwOWYx/image_2.JPG';
ct.Age__c = 27;
ct.AccountId = acct.Id;

ct.Address_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
ct.Email_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
ct.Phone_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);

insert ct;
System.debug(JSON.serialize(ct.Id));
       return ct;
   }
   
     public static String generateRandomNumber() {
        String randomNumber = generate();
        if (randomNumber.length() < 3) {
            String randomNumber2 = generate();
            randomNumber = randomNumber + randomNumber2.substring(0, 10 - randomNumber.length());
        }
        return randomNumber;
    }
    public static String generateIdentifier(String prefix) {
        return prefix + '-' + generateRandomNumber();
    }
    private static String generate() {
        return String.valueOf(Math.abs(Crypto.getRandomInteger()));
    }
 private static Account cloneAccount(){
         // Query an existing account in the organization. 
        Account a = [SELECT Id, Name FROM Account WHERE AccountNumber='1334781826176083629' LIMIT 1];
        System.assert(a != null);
        System.debug('a.id'+a.Id);
        // Create a test account based on the queried account.
        Account testAccount = a.clone();
        testAccount.Name = 'Acme Test';
        testAccount.Account_Number_Encrypted__c = '133478182617600'+generateIdentifier('t');
        insert testAccount;
        return testAccount;
    }   
        
    
       private static Contact createNoContactRelationId(String Name, String AccountNumber){
        
        Account acct = new Account();
acct.Name = Name;
acct.Account_Number_Encrypted__c = 'AccountNumber';
acct.AccountNumber = AccountNumber;
acct.Account_Type__c = 'Personal';
acct.Account_Subtype__c = 'PayPal Cash Plus';
acct.Account_Status__c = 'Open';
acct.Location__c = 'San Jose';
acct.Country_Code__c = 'US';
acct.Country_Name__c = 'United States';
acct.Timezone__c = 'PST';
acct.Account_Created_Time__c = DateTime.newInstance(2015, 03, 01, 09, 00, 00);
acct.Customer_Segment__c = 'Likely To Churn';
acct.No_of_Secondary_Users__c = 0;
acct.CIP_Status__c = 'In-Progress';
acct.Is_Unregistered__c = false;
acct.Unregistered_Account_Type__c = '';
        

acct.ActivityLog_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Basic_Profile_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Compliance_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Account_Manager_Flags_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Limitation_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Business_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Linked_Accounts_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.PayPal_Cases_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Previous_Interactions_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Product_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Secondary_User_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.ServiceLog_Notes_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.TransactionLog_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Wallet_Info_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);
acct.Prefetch_Loaded_Time__c = DateTime.newInstance(2021, 03, 01, 09, 00, 00);

insert acct;
System.debug(JSON.serialize(acct.Id));

       
Contact ct = new Contact();
ct.Party_Id__c = '1334781826176083630';
ct.Full_Name__c = 'Jennifer Lawrence';
ct.FirstName = 'Jennifer';
ct.LastName = 'Lawrence';
ct.Profile_Picture__c = 'https://msmaster.qa.paypal.com:14870/v1/content/media-containers/PICS/cdn-assets/00/p/OGY0MmMyZDAtMmY5Zi00YTIyLWJkNzUtYTE1YTQwYjEwOWYx/image_2.JPG';
ct.Age__c = 27;
ct.AccountId = acct.Id;

insert ct;
System.debug(JSON.serialize(ct.Id));
       return ct;
   }
   
  
     @isTest static void testNullAccountidAndCaseid()
    {
         QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(null,null);
         //System.debug('Result'+response.result.message);
         System.assertEquals('Unexpected Error: Both Case Id and Account Id is missing in the request', response.result.message); 
    }

    
    public static testMethod void myTestMethod(){
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(null,createAccount('Eazhil', '1293589840714216965').Id);
        System.debug('Eazhil Here'+ response.result);
        System.assertEquals('Data is Partially Loaded', response.result.message);
    }
    
    
     public static testMethod void limitationTestMethod(){
        Account acct = createAccount('Eazhil', '1293589840714216966');
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(null,acct.Id);
        System.debug('Eazhil Here'+ response.result);
        System.assertEquals('Data is Partially Loaded', response.result.message);
    }
    
    public static testMethod void nolimitationTestMethod(){
        Account acct = createNoLimitAccountFlag('Eazhil', '1293589840714216969');
        //acct.Limitation_Info_Loaded_Time__c = null;
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(null,acct.Id);
        System.debug('Eazhil Here'+ response.result.message);
        System.assertEquals('Failed to load the Data', response.result.message);
    }
    
     public static testMethod void noaccountManagerTestMethod(){
        Account acct = createNoLimitAccountFlag('Eazhil', '1293589840714216970');
        //acct.Account_Manager_Flags_Loaded_Time__c = null;
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(null,acct.Id);
        System.debug('Eazhil Here'+ response.result.message);
        System.assertEquals('Failed to load the Data', response.result.message);
    }
    
     public static testMethod void noComplianceInfoTestMethod(){
        Account acct = createNoLimitAccountFlag('Eazhil', '1293589840714216970');
        //acct.Account_Manager_Flags_Loaded_Time__c = null;
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(null,acct.Id);
        System.debug('Eazhil Here'+ response.result.message);
        System.assertEquals('Failed to load the Data', response.result.message);
    }

     public static testMethod void testCaseId(){
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(createCaseid('Eazhil', '1293589840714216988').Id,null);
        System.debug('Eazhil Here'+ response.result);
        System.assertEquals('Data is Partially Loaded', response.result.message);
    }
    
     public static testMethod void testAccountNumberNull(){
        Case caseObj = createCaseid('Eazhil', '1293589840714216988');
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(caseObj.Id,caseObj.Id);
        System.debug('Eazhil Here'+ response.result);
        System.assertEquals('Unexpected Error: Failed to find the account with Account Id passed in the request', response.result.message);
    }
    
      /*public static testMethod void testCaseInfoNull(){
        Account acct = createAccount('Eazhil', '1293589840714216966');
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(acct.Id,acct.Id);
        System.debug('Eazhil Here'+ response.result);
        System.assertEquals('Data is Partially Loaded', response.result.message);
    }*/
        
     public static testMethod void testCaseIdWoAccount(){
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(createCaseIdWoAccount().Id,null); 
        System.debug('Eazhil Here'+ response.result);
        System.assertEquals('Unexpected Error: Case Id passed in the request is not associated with any Account', response.result.message);
    }
    
     public static testMethod void testContactRelationId(){
        Contact ct = createContactRelationId('Eazhil', '1293589840714216991');
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(null,ct.AccountId);
        System.debug('Eazhil Here'+ response.result);
        System.assertEquals('SUCCESS', response.result.message);
    }

     public static testMethod void testNoContactRelationId(){
        Contact ct = createNoContactRelationId('Eazhil', '1293589840714216991');
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(null,ct.AccountId);
        System.debug('Eazhil Here'+ response.result);
        System.assertEquals('Data is Partially Loaded', response.result.message);
    }    
    
       @isTest static void testQuickGlanceInfoWoCache()
    {
         Account acct = createAccount('Eazhil', '1293589840714216966');
         QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfoWithoutCache(null,acct.Id);
         //System.debug('Result'+response.result.message);
         System.assertEquals('Failed to load the Data', response.result.message); 
    }
    
    public static testMethod void testQuickGlanceInfoWoCacheNull(){
        Case caseObj = createCaseid('Eazhil', '1293589840714216988');
        QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfoWithoutCache(caseObj.Id,caseObj.Id);
        System.debug('Eazhil Here'+ response.result);
        System.assertEquals('Unexpected Error: Failed to identify the Account using Account Id or Case Id', response.result.message);
    }
    
     @isTest
    public static void verifyQuickApiSuccess200Test(){
        // Creating Request
        Customer360APIRequest cx360Request = new Customer360APIRequest();
        Account acct = createAccount('Eazhil', '1293589840714216969');
        cx360Request.setAccount(acct);
        //cx360Request.setAccount(cloneAccount());
        cx360Request.addToDataCategoriesToBeLoaded(Customer360.DataCategory.ACCOUNT_INFO);
       test.startTest();
       // Create the mock response based on a static resource
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('AccountManagerValidResponse');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);
        // Call method to test
        Customer360APIResponse result = Customer360API.getCustomer360Data(cx360Request);
        Customer360DO customer360do = result.getCustomer360DO();
         System.debug('Success1'+result.isAPIStatusSuccess());
         System.debug('Success2'+result.isAPIStatusPartialSuccess());
         System.debug('Success3'+result.isAPIStatusFailure());
         QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(null,acct.Id);
        //CustomerTagsControllerResponse response =  CustomerTagsController.getCustomerTags(null,a.Id);
        System.debug('Eazhil Here'+ response.result);
        //System.assertEquals('SUCCESS', response.result.message);
        test.stopTest();
    }
    
      @isTest
    public static void verifyQuickApiPartial206Test(){
        // Creating Request
        Customer360APIRequest cx360Request = new Customer360APIRequest();
        Account acct = createAccount('Eazhil', '1293589840714216969');
        cx360Request.setAccount(acct);
        //cx360Request.setAccount(cloneAccount());
        cx360Request.addToDataCategoriesToBeLoaded(Customer360.DataCategory.ACCOUNT_INFO);
       test.startTest();
       // Create the mock response based on a static resource
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('AccountManagerValidResponse');
        mock.setStatusCode(206);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        // Associate the callout with a mock response
        Test.setMock(HttpCalloutMock.class, mock);
        // Call method to test
        Customer360APIResponse result = Customer360API.getCustomer360Data(cx360Request);
        Customer360DO customer360do = result.getCustomer360DO();
         System.debug('Success1'+result.isAPIStatusSuccess());
         System.debug('Success2'+result.isAPIStatusPartialSuccess());
         System.debug('Success3'+result.isAPIStatusFailure());
         QuickGlanceControllerResponse response =  QuickGlanceController.getQuickGlanceInfo(null,acct.Id);
        //CustomerTagsControllerResponse response =  CustomerTagsController.getCustomerTags(null,a.Id);
        System.debug('Eazhil Here'+ response.result);
        //System.assertEquals('SUCCESS', response.result.message);
        test.stopTest();
    }
    
    
}