force-app/main/default/objects/Account/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number which should be used in all API calls. Please note that we will not be encrypting the account number in Salesforce side, this will be internally handled by User domain in PayPal.</description>
    <externalId>true</externalId>
    <inlineHelpText>Encrypted Account Number which should be used in API calls.</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account_Limitation__c/Account_Limitation__c.object-meta.xml
<CustomObject>
    <description>Limitations / Restrictions placed on an account</description>
    <label>Account Limitation</label>
    <nameField>
        <label>Limitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Limitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Limitation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Limitations for an account</description>
    <inlineHelpText>Limitations for an account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Limitations</relationshipLabel>
    <relationshipName>Account_Limitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Limitation__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this limitation still actively placed</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Manager_Flag__c/Account_Manager_Flag__c.object-meta.xml
<CustomObject>
    <description>Account can be mapped to one or more flags that could indicated if it is managed by an account manager or not.</description>
    <label>Account Manager Flag</label>
    <nameField>
        <label>Flag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Manager Flags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Manager_Flag__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account manager flags associated with an account</description>
    <inlineHelpText>Account manager flags associated with an account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Manager Flags</relationshipLabel>
    <relationshipName>Account_Manager_Flags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Manager_Flag__c/fields/Is_Managed_Account__c.field-meta.xml
<CustomField>
    <fullName>Is_Managed_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the account is a managed account or not</description>
    <inlineHelpText>Indicates whether the account is a managed account or not</inlineHelpText>
    <label>Is Managed Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Session__c/Case_Session__c.object-meta.xml
<CustomObject>
    <description>Similar to user sessions in PayPal, teammates has an associated session when they handle interactions. A session is established for an Actor (teammate) and a subject (Account Number) and hence a single case can have multiple sessions (like switch accounts). Lot of interactions happen in a session between the actor and subject - like Basic Authentication, Step-up and so on and this object preserves critical session data that is required during the interaction and sometimes beyond for reporting purposes.</description>
    <label>Case Session</label>
    <nameField>
        <label>Case Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account Number being serviced in the interaction</description>
    <inlineHelpText>Account Number being serviced in the interaction</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Sessions</relationshipLabel>
    <relationshipName>Case_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Session__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current Interaction Case</description>
    <inlineHelpText>Current Interaction Case</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Sessions</relationshipLabel>
    <relationshipName>Case_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Party id that is currently contacting us. For personal accounts, this will be same as the primary owner associated with the contact. For business accounts, this could be either the primary owner or the secondary user.</description>
    <inlineHelpText>Party id that is currently contacting us. For personal accounts, this will be same as the primary owner associated with the contact. For business accounts, this could be either the primary owner or the secondary user.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Case Sessions</relationshipLabel>
    <relationshipName>Case_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <description>Party Id that identifies the User/Party in PayPal system</description>
    <externalId>true</externalId>
    <inlineHelpText>Party Id that identifies the User/Party in PayPal system</inlineHelpText>
    <label>Party Id</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Customer360Util.cls
public class Customer360Util {
    // Utility class that provides some common methods required for Customer360 data

    // Basic Account Record will load absolute minimal data without which Account record
    // does not make any sense like Account No. This method will be required in most of the Customer360
    // controllers when we want to load fresh data for an account ignoring all cached local data
    public static Account getBasicAccountDetails(Id caseId, Id accountId)
    {
        System.debug('Customer360Util:getBasicAccountDetails: caseId - ' + caseId + ', accountId' + accountId);

        if ((caseId == null) && (accountId == null))
        {
            System.debug(LoggingLevel.ERROR, 'Both Case Id and Account Id is null - cannot proceed further');
            return null;
        }

        List<Account> accountList = new List<Account>();

        // Lets start with the Account Id if it is not null, that is the most straighforward option
        if (accountId != null)
        {
            System.debug('Loading the account with accountId -' + accountId);
            accountList = queryBasicAccountWithAccountId(accountId);
        }
        else // Use Case Id
        {
            System.debug('Loading the account with caseId -' + caseId);
            accountList = queryBasicAccountWithCaseId(caseId);
        }

        if (accountList.size() == 0)
        {
            System.debug(LoggingLevel.ERROR, 'Unable to identify the Account with either account id or case id');
            return null;
        }

        return accountList[0];
    }

    // Basic Contact Record will load absolute minimal data without which Contact record
    // does not make any sense like Party Id. This method will be required in some of the Customer360
    // controllers when we want to load fresh data for an account ignoring all cached local data
    public static Contact getContactedParty(Id caseId, Id accountId)
    {
        System.debug('Customer360Util:getContactedPartyDetails: caseId - ' + caseId + ', accountId' + accountId);

        if ((caseId == null) || (accountId == null))
        {
            System.debug(LoggingLevel.ERROR, 'Either Case Id or Account Id is null - cannot determine the Case Session');
            return null;
        }

        List<Contact> contacts = queryPartyAssociatedWithCaseSession(caseId, accountId);

        if (contacts.size() == 0)
        {
            System.debug(LoggingLevel.ERROR, 'Unable to identify the Contacted party using Case Session');
            return null;
        }

        return contacts[0];
    }

    private static List<Account> queryBasicAccountWithAccountId(Id accountId)
    {
        return [SELECT Id, Account_Number_Encrypted__c, AccountNumber
                FROM Account WHERE Id=:accountId
               ];
    }

    private static List<Account> queryBasicAccountWithCaseId(Id caseId)
    {
        return [SELECT Id, Account_Number_Encrypted__c, AccountNumber
                FROM Account
                WHERE Id IN (SELECT AccountId FROM Case WHERE Id=:caseId)
               ];
    }

    private static List<Contact> queryPartyAssociatedWithCaseSession(Id caseId, Id accountId)
    {
        return [SELECT Id, Party_Id__c
                FROM Contact 
                WHERE Id IN (SELECT Contact__c FROM Case_Session__c WHERE Case__c=:caseId AND Account__c=:accountId)
               ];
    }

    public static Boolean isDataNotAvailableLocally(Customer360.DataCategory category, Datetime lastUpdatedTime)
    {
        // If the information is not loaded into Salesforce yet or if loaded earlier than allowed cache duration, we need to load it fresh
        // As of now, all Customer360 data entities share the same expiry time and hence there is no need to consider the category passed in
        // the request in expiry time computation. When we diversify, we will assign different expiry times to each data entity based
        // on the need and use it here.
        if ((lastUpdatedTime == null) || (DateTime.now().addMinutes(ExecutionContextUtil.getPayPalAPICacheTimeDefault() * -1) > lastUpdatedTime))
        {
            return true;
        }
        return false;
    }

    public static List<Account_Limitation__c> filterActiveLimitations(List<Account_Limitation__c> limitations)
    {
        List<Account_Limitation__c> activeLimitations = new List<Account_Limitation__c>();

        if (limitations != null)
        {
            System.debug('Number of Limitations passed to the filter - ' + limitations.size());

            for (Account_Limitation__c limitation : limitations)
            {
                if (limitation.Is_Active__c)
                {
                    activeLimitations.add(limitation);
                }
            }
        }

        return activeLimitations;
    }

    public static Account_Manager_Flag__c filterManagedAccountFlag(List<Account_Manager_Flag__c> flags)
    {
        if (flags != null)
        {
            System.debug('Number of Account Manager flags passed to the filter - ' + flags.size());

            for (Account_Manager_Flag__c flag : flags)
            {
                if (flag.Is_Managed_Account__c)
                {
                    // Managed Account flag found - just return it
                    // There can be only one managed account flag set for an account
                    return flag; 
                }
            }
        }

        return null;
    }
}