force-app/main/default/objects/Account/fields/Account_Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Account_Created_Time__c</fullName>
    <description>When was the account created, not in Salesforce but in the actual system of record.</description>
    <inlineHelpText>Account created time</inlineHelpText>
    <label>Account Created Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number which should be used in all API calls. Please note that we will not be encrypting the account number in Salesforce side, this will be internally handled by User domain in PayPal.</description>
    <externalId>true</externalId>
    <inlineHelpText>Encrypted Account Number which should be used in API calls.</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status - Open, Locked, Closed, etc.,</description>
    <inlineHelpText>Account Status - Open, Locked, Closed, etc.,</inlineHelpText>
    <label>Account Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type - like Personal / Premier / Business in the tenant side. This could be a candidate for a picklist, but we dont need to put too many restrictions for customer data in the client side since we are not using Salesforce as a source of truth. So, let&apos;s keep it loosely coupled.</description>
    <inlineHelpText>Account Type - like Personal / Premier / Business</inlineHelpText>
    <label>Account Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Unregistered__c.field-meta.xml
<CustomField>
    <fullName>Is_Unregistered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customers can use PayPal without registering for an account or do guest checkout even if they have one. This flag indicated whether the account is registered or not.</description>
    <inlineHelpText>Is this Account not registered yet?</inlineHelpText>
    <label>Is Unregistered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Linked_Accounts_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Linked_Accounts_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Linked Accounts Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unregistered_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Unregistered_Account_Type__c</fullName>
    <description>If the account is not registered with PayPal, this field will indicate type of the account like Guest, WAX or DCC.</description>
    <inlineHelpText>If the account is not registered with PayPal, this field will indicate type of the account like Guest, WAX or DCC.</inlineHelpText>
    <label>Unregistered Account Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/Account_Wallet__c.object-meta.xml
<CustomObject>
    <description>Wallet object stores all the financial instruments associated with the account like banks, cards, paypal credit and so on.</description>
    <label>Account Wallet</label>
    <nameField>
        <label>Account Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Wallet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Wallet__c/fields/Financial_Instrument_Type__c.field-meta.xml
<CustomField>
    <fullName>Financial_Instrument_Type__c</fullName>
    <description>Financial Instrument Type - like Card/Bank/etc.,</description>
    <inlineHelpText>Financial Instrument Type - like Card/Bank/etc.,</inlineHelpText>
    <label>Financial Instrument Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Last_4_digits__c.field-meta.xml
<CustomField>
    <fullName>Last_4_digits__c</fullName>
    <description>Last 4 digits of the card/bank account number/etc.,</description>
    <inlineHelpText>Last 4 digits of the card/bank account number/etc.,</inlineHelpText>
    <label>Last 4 digits</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/Contact_Address__c.object-meta.xml
<CustomObject>
    <description>Addresses associated with the contact</description>
    <label>Contact Address</label>
    <nameField>
        <label>Contact Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Address Line 1</description>
    <inlineHelpText>Address Line 1</inlineHelpText>
    <label>Address Line 1</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/Contact_Email__c.object-meta.xml
<CustomObject>
    <description>Email addresses associated with the contact / user.</description>
    <label>Contact Email</label>
    <nameField>
        <label>Contact Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Email__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>Email Address</description>
    <inlineHelpText>Email Address</inlineHelpText>
    <label>Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/Contact_Phone__c.object-meta.xml
<CustomObject>
    <description>Phone numbers associated with an account</description>
    <label>Contact Phone</label>
    <nameField>
        <label>Contact Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Phone__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Phone number</description>
    <inlineHelpText>Phone number</inlineHelpText>
    <label>Phone Number</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/Linked_Account__c.object-meta.xml
<CustomObject>
    <description>A PayPal account can be indirectly linked to other PayPal accounts by tEmail, Phone, Wallet and so on. This custom object is used to store accounts linked with each other via such category. The initial idea is to create account records for all linked accounts, but creating all those records is absolutely unnecessary unless the teammate wants to switch to one of those accounts. Even in that case, teammates will be switching to only one of those accounts and not to all. We will preserve the minimal details in this object and will create actual account is necessary.</description>
    <label>Linked Account</label>
    <nameField>
        <label>Linked Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Linked Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Linked_Account__c/fields/Account1__c.field-meta.xml
<CustomField>
    <fullName>Account1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account in one side of the linking</description>
    <inlineHelpText>Account in one side of the linking</inlineHelpText>
    <label>Account1</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Linked Accounts (Account1)</relationshipLabel>
    <relationshipName>Linked_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Account_Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Account_Created_Time__c</fullName>
    <description>Account Created Time</description>
    <inlineHelpText>Account Created Time</inlineHelpText>
    <label>Account Created Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Account Number</description>
    <inlineHelpText>Account Number</inlineHelpText>
    <label>Account Number</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number</description>
    <inlineHelpText>Encrypted Account Number</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status</description>
    <inlineHelpText>Account Status</inlineHelpText>
    <label>Account Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type</description>
    <inlineHelpText>Account Type</inlineHelpText>
    <label>Account Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Full Name of the linked account</description>
    <inlineHelpText>Full Name of the linked account</inlineHelpText>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Has_Strong_Link__c.field-meta.xml
<CustomField>
    <fullName>Has_Strong_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether account1 and account2 are strongly linked so that there is no need for validation while switching to that account.</description>
    <inlineHelpText>Indicates whether account1 and account2 are strongly linked so that there is no need for validation while switching to that account.</inlineHelpText>
    <label>Has Strong Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Is_Unregistered__c.field-meta.xml
<CustomField>
    <fullName>Is_Unregistered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is Unregistered</description>
    <inlineHelpText>Is Unregistered</inlineHelpText>
    <label>Is Unregistered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linked_Account__c/fields/Unregistered_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Unregistered_Account_Type__c</fullName>
    <description>Unregistered Account Type</description>
    <inlineHelpText>Unregistered Account Type</inlineHelpText>
    <label>Unregistered Account Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account_Attributes__c/Linked_Account_Attributes__c.object-meta.xml
<CustomObject>
    <description>Attributes by which two accounts are linked. It could be by name, email, phone or financial instruments.</description>
    <label>Linked Account Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Linked Account Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linked_Account_Attributes__c/fields/Attribute_Value__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Value__c</fullName>
    <description>Value of that attribute that is matching between accounts. It could be the name or email address or phone number, etc., This values is required to identify the exact value that is matching since there is a possibility of account having multiple data points (like multiple emails) out of which one could match.</description>
    <inlineHelpText>Value of that attribute that is matching between accounts.</inlineHelpText>
    <label>Attribute Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linked_Account_Attributes__c/fields/Has_Strong_Link__c.field-meta.xml
<CustomField>
    <fullName>Has_Strong_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the attribute is strongly linked or not. For e.g., an inactive email in account 1 could be matching with active email in account 2. In this case, we will consider these accounts as linked and it is linked by email address, but it is not a strong link for validation purposes since the email is inactive in an account.</description>
    <inlineHelpText>Is the attribute strongly linked?</inlineHelpText>
    <label>Has Strong Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linked_Account_Attributes__c/fields/Linked_Account__c.field-meta.xml
<CustomField>
    <fullName>Linked_Account__c</fullName>
    <description>Attributes by which two accounts are linked.</description>
    <inlineHelpText>Attributes by which two accounts are linked.</inlineHelpText>
    <label>Linked Account</label>
    <referenceTo>Linked_Account__c</referenceTo>
    <relationshipLabel>Linked Account Attributes</relationshipLabel>
    <relationshipName>Linked_Account_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linked_Account_Attributes__c/fields/Response_JSON__c.field-meta.xml
<CustomField>
    <fullName>Response_JSON__c</fullName>
    <description>The JSON string that contains the linked attribute details are stored in this field. Ideally, we would like to explode the whole data into the object, but given that Salesforce is not the system of record, we don&apos;t need to complicate unless it is absolutely necessary.</description>
    <inlineHelpText>The JSON string that contains the linked attribute details.</inlineHelpText>
    <label>Response JSON</label>
    <length>8192</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LinkedAccountAPI.cls
public class LinkedAccountAPI {
    
    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('LinkedAccountAPI:mapResponseToCustomer360SO - mapping Linked Accounts Information');
        
        // Check if there are any failures in loading Linked Accounts
        if (response.isLinkedAccountsFailed() || (response.getCustomer360DO().linked_accounts == null) ||
            (response.getCustomer360DO().linked_accounts.size() == 0))
        {
            System.debug('No Linked accounts available in Customer360 API response');
            return cx360SO;
        }
        
        // Map Linked Accounts to the cx360SO object passed in the request
        for (LinkedAccountDO lacct : response.getCustomer360DO().linked_accounts)
        {
            cx360SO.linkedAccounts.add(mapLinkedAccountDOToSO(lacct));
        }

        return cx360SO;
    }

    public static Account storeResponseInSObject(Account acct, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('LinkedAccountAPI:storeResponseInSObject - Stroing Linked Accounts Information into SObject');
        
        // Check if there are any failures in loading Linked Accounts
        if (response.isLinkedAccountsFailed())
        {
            System.debug('Customer360API did not successfully load the linked accounts');
            return acct;
        }

        // Remove all linked accounts from the account
        removeLinkedAccountsFromAccount(acct);

        List<LinkedAccountDO> lacctDOs = response.getCustomer360DO().linked_accounts;
        
        if ((lacctDOs != null) && (lacctDOs.size() > 0))
        {
            List<LinkedAccountSO> lacctSOs = new List<LinkedAccountSO>();
            List<Linked_Account__c> linkedAccountObjsToInsert = new List<Linked_Account__c>();

            for (LinkedAccountDO lacctDO : lacctDOs)
            {
                LinkedAccountSO lacctSO = mapLinkedAccountDOToSO(lacctDO);
                lacctSO.linkedAccount.Account1__c = acct.Id;
                linkedAccountObjsToInsert.add(lacctSO.linkedAccount);
                lacctSOs.add(lacctSO);
            }

            // Now that we have collected all linked accounts to be inserted, lets go ahead and insert
            // This will create Id for all the linked accounts, the beauty of handling object be reference
            // will make sure the Id values are available when we access
            System.debug('Inserting Linked Accounts. Number of Records - ' + linkedAccountObjsToInsert.size());
            insert linkedAccountObjsToInsert;

            List<Linked_Account_Attributes__c> linkedAttributeObjsToInsert = new List<Linked_Account_Attributes__c>();

            for (LinkedAccountSO lso : lacctSOs)
            {
                for (LinkedAccountAttributeSO lattrSO : lso.attributes)
                {
                    // Link the newly created id into the child object - linked account attributes
                    lattrSO.attribute.Linked_Account__c = lso.linkedAccount.Id;
                    linkedAttributeObjsToInsert.add(lattrSO.attribute);
                }
            }

            // Insert all child objects
            System.debug('Inserting Linked Account Attributes. Number of Records - ' + linkedAttributeObjsToInsert.size());
            if (linkedAttributeObjsToInsert.size() > 0)
            {
                insert linkedAttributeObjsToInsert;
            }
        }

        // If Linked Accounts is loaded successfully (NOT a failure or partial success), update the cache time
        if (response.isLinkedAccountsSuccessfullyLoaded())
        {
            acct.Linked_Accounts_Loaded_Time__c = Datetime.now();
        }

        return acct;
    }

    private static LinkedAccountSO mapLinkedAccountDOToSO(LinkedAccountDO lacct)
    {
        LinkedAccountSO lacctSo = new LinkedAccountSO();
        lacctSo.linkedAccount = mapResponseToLinkedAccount(lacct);

        // Map Linked By Attributes
        if (lacct.linked_by != null)
        {
            lacctSo = mapLinkedByInfoDOToSO(lacctSo, lacct.linked_by);
        }

        return lacctSo;
    }

    private static Linked_Account__c mapResponseToLinkedAccount(LinkedAccountDO lacct)
    {
        Linked_Account__c acct = new Linked_Account__c();
        acct.Full_Name__c = lacct.full_name;
        acct.Account_Number__c = lacct.account_number;
        acct.Account_Number_Encrypted__c = lacct.payer_id;
        acct.Account_Type__c = lacct.account_type;
        acct.Account_Created_Time__c = lacct.create_time;
        acct.Account_Status__c = lacct.account_status;
        acct.Has_Strong_Link__c = lacct.strongly_connected;

        // Guest/Wax account
        if (String.isNotBlank(lacct.registration_type))
        {
            // Registration type 'FULL' indicates that the account is properly registered PayPal Account
            // Anything else can be treated as unregistered - which is GUEST or ANONYMOUS
            if (!lacct.registration_type.equalsIgnoreCase('full'))
            {
                acct.Is_Unregistered__c = true;
                acct.Unregistered_Account_Type__c = lacct.registration_type;
            }
        }
        
        return acct;
    }

    private static LinkedAccountSO mapLinkedByInfoDOToSO(LinkedAccountSO lacctSo, LinkedByInfoDO linked_by)
    {
        // Linked By Name
        lacctSo.attributes.add(mapLinkedByNameDOToSO(linked_by.name));

        // Linked by email
        if ((linked_by.emails != null) && (linked_by.emails.size() != 0))
        {
            for (LinkedByEmailDO email : linked_by.emails)
            {
                lacctSo.attributes.add(mapLinkedByEmailDOToSO(email));
            }
        }

        // Linked By Phone
        if ((linked_by.phones != null) && (linked_by.phones.size() != 0))
        {
            for (LinkedByPhoneDO phone : linked_by.phones)
            {
                lacctSo.attributes.add(mapLinkedByPhoneDOToSO(phone));
            }
        }

        // Linked By Address
        if ((linked_by.addresses != null) && (linked_by.addresses.size() != 0))
        {
            for (LinkedByAddressDO address : linked_by.addresses)
            {
                lacctSo.attributes.add(mapLinkedByAddressDOToSO(address));
            }
        }

        // Linked By Financial Instrument
        if ((linked_by.financial_instruments != null) && (linked_by.financial_instruments.size() != 0))
        {
            for (LinkedByFinancialInstrumentDO fi : linked_by.financial_instruments)
            {
                lacctSo.attributes.add(mapLinkedByFinancialInstrumentDOToSO(fi));
            }
        }

        return lacctSo;
    }

    private static LinkedAccountAttributeSO mapLinkedByNameDOToSO(LinkedByNameDO name)
    {
        LinkedAccountAttributeSO lattrSO = new LinkedAccountAttributeSO();
        lattrSO.attribute.Name = 'Name';
        lattrSO.attribute.Attribute_Value__c = name.full_name;
        lattrSO.attribute.Has_Strong_Link__c = name.strongly_connected;

        return lattrSO;
    }

    private static LinkedAccountAttributeSO mapLinkedByEmailDOToSO(LinkedByEmailDO email)
    {
        LinkedAccountAttributeSO lattrSO = new LinkedAccountAttributeSO();
        lattrSO.attribute.Name = 'Email';
        lattrSO.attribute.Has_Strong_Link__c = email.strongly_connected;

        if (email.email != null)
        {
            Contact_Email__c emailObj = ProfileEmailAPI.mapEmailDOToContactEmail(email.email);
            lattrSO.attribute.Attribute_Value__c = emailObj.Email_Address__c;
            lattrSO.attribute.Response_JSON__c = JSON.serialize(emailObj);
            lattrSO.email = emailObj;
        }

        return lattrSO;
    }

    private static LinkedAccountAttributeSO mapLinkedByPhoneDOToSO(LinkedByPhoneDO phone)
    {
        LinkedAccountAttributeSO lattrSO = new LinkedAccountAttributeSO();
        lattrSO.attribute.Name = 'Phone';
        lattrSO.attribute.Has_Strong_Link__c = phone.strongly_connected;

        if (phone.phone != null)
        {
            Contact_Phone__c phoneObj = ProfilePhoneAPI.mapPhoneDOToContactPhone(phone.phone);
            lattrSO.attribute.Attribute_Value__c = phoneObj.Phone_Number__c;
            lattrSO.attribute.Response_JSON__c = JSON.serialize(phoneObj);
            lattrSO.phone = phoneObj;
        }

        return lattrSO;
    }

    private static LinkedAccountAttributeSO mapLinkedByAddressDOToSO(LinkedByAddressDO address)
    {
        LinkedAccountAttributeSO lattrSO = new LinkedAccountAttributeSO();
        lattrSO.attribute.Name = 'Address';
        lattrSO.attribute.Has_Strong_Link__c = address.strongly_connected;

        if (address.address != null)
        {
            Contact_Address__c addressObj = ProfileAddressAPI.mapAddressDOToContactAddress(address.address);
            lattrSO.attribute.Attribute_Value__c = addressObj.Address_Line_1__c;
            lattrSO.attribute.Response_JSON__c = JSON.serialize(addressObj);
            lattrSO.address = addressObj;
        }

        return lattrSO;
    }

    private static LinkedAccountAttributeSO mapLinkedByFinancialInstrumentDOToSO(LinkedByFinancialInstrumentDO fi)
    {
        LinkedAccountAttributeSO lattrSO = new LinkedAccountAttributeSO();
        lattrSO.attribute.Has_Strong_Link__c = fi.strongly_connected;

        if (fi.financial_instrument != null)
        {
            // TBD - Based on the Wallet fields and values finalization, we need to re-visit what will be
            // returned here and how to map it properly to use.
            Account_Wallet__c fiObj = WalletAPI.mapFinancialInstrumentDOToSO(fi.financial_instrument);
            lattrSO.attribute.Name = fiObj.Financial_Instrument_Type__c;
            lattrSO.attribute.Attribute_Value__c = fiObj.Last_4_digits__c;
            lattrSO.attribute.Response_JSON__c = JSON.serialize(fiObj);
            lattrSO.financialInstrument = fiObj;
        }

        return lattrSO;
    }

    public static LinkedAccountAttributeSO mapLinkedAccountAttributeObjToSO(Linked_Account_Attributes__c attr)
    {
        LinkedAccountAttributeSO lattrSO = new LinkedAccountAttributeSO();
        lattrSO.attribute = attr;
        
        if (attr.Name.equalsIgnoreCase('Email') && String.isNotBlank(attr.Response_JSON__c))
        {
            try {
                lattrSO.email = (Contact_Email__c) JSON.deserialize(attr.Response_JSON__c, Contact_Email__c.class);
            } catch (Exception e) {
                System.debug(LoggingLevel.ERROR, 'Failed to deserialize Linked by Email JSON response. Id - ' + attr.Id + ', Message - ' + e.getMessage());
            }
        }
        else if (attr.Name.equalsIgnoreCase('Phone') && String.isNotBlank(attr.Response_JSON__c))
        {
            try {
                lattrSO.phone = (Contact_Phone__c) JSON.deserialize(attr.Response_JSON__c, Contact_Phone__c.class);
            } catch (Exception e) {
                System.debug(LoggingLevel.ERROR, 'Failed to deserialize Linked by Phone JSON response. Id - ' + attr.Id + ', Message - ' + e.getMessage());
            }
        }
        else if (attr.Name.equalsIgnoreCase('Address') && String.isNotBlank(attr.Response_JSON__c))
        {
            try {
                lattrSO.address = (Contact_Address__c) JSON.deserialize(attr.Response_JSON__c, Contact_Address__c.class);
            } catch (Exception e) {
                System.debug(LoggingLevel.ERROR, 'Failed to deserialize Linked by Address JSON response. Id - ' + attr.Id + ', Message - ' + e.getMessage());
            }
        }
        else if (String.isNotBlank(attr.Response_JSON__c))
        {
            // The only other possibility is financial instrument, so lets try it
            try {
                lattrSO.financialInstrument = (Account_Wallet__c) JSON.deserialize(attr.Response_JSON__c, Account_Wallet__c.class);
            } catch (Exception e) {
                System.debug(LoggingLevel.ERROR, 'Failed to deserialize Linked by Wallet JSON response. Id - ' + attr.Id + ', Message - ' + e.getMessage());
            }
        }

        return lattrSO;
    }

    private static void removeLinkedAccountsFromAccount(Account acct)
    {
        List<Linked_Account__c> laccts = queryLinkedAccountsFromAccount(acct.Id);
        System.debug('Removing existing linked accounts from the account. Number of records found - ' + laccts.size());
        if (laccts.size() > 0)
        {
            delete laccts;

            // Deleting the linked accounts will automatically delete all linked account attributes child object
            // because of the Master - Detail relationship
        }
        return;
    }

    private static List<Linked_Account__c> queryLinkedAccountsFromAccount(Id accountId)
    {
        return [SELECT Id, Account1__c FROM Linked_Account__c
                WHERE Account1__c=:accountId];
    }
    
}