force-app/main/default/objects/Account/fields/Account_Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Account_Created_Time__c</fullName>
    <description>When was the account created, not in Salesforce but in the actual system of record.</description>
    <inlineHelpText>Account created time</inlineHelpText>
    <label>Account Created Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_Encrypted__c</fullName>
    <description>Encrypted Account Number which should be used in all API calls. Please note that we will not be encrypting the account number in Salesforce side, this will be internally handled by User domain in PayPal.</description>
    <externalId>true</externalId>
    <inlineHelpText>Encrypted Account Number which should be used in API calls.</inlineHelpText>
    <label>Account Number Encrypted</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status - Open, Locked, Closed, etc.,</description>
    <inlineHelpText>Account Status - Open, Locked, Closed, etc.,</inlineHelpText>
    <label>Account Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Account_Subtype__c</fullName>
    <description>Account&apos;s subtype. Not all account types or countries has a subtype, but this field is created to handle in scenarios where it is needed.</description>
    <inlineHelpText>Account subtype - like No Balance/PayPal Cash/PayPal Cash Plus account in case of Personal</inlineHelpText>
    <label>Account Subtype</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Account Type - like Personal / Premier / Business in the tenant side. This could be a candidate for a picklist, but we dont need to put too many restrictions for customer data in the client side since we are not using Salesforce as a source of truth. So, let&apos;s keep it loosely coupled.</description>
    <inlineHelpText>Account Type - like Personal / Premier / Business</inlineHelpText>
    <label>Account Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Basic_Profile_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Basic_Profile_Loaded_Time__c</fullName>
    <description>For Cache or TTL purposes.</description>
    <inlineHelpText>For Cache or TTL purposes.</inlineHelpText>
    <label>Basic Profile Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>ISO Country Code for the account&apos;s legal country</description>
    <inlineHelpText>ISO Country Code for the account&apos;s legal country</inlineHelpText>
    <label>Country Code</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <description>Customer&apos;s legal country name</description>
    <inlineHelpText>Customer&apos;s legal country name</inlineHelpText>
    <label>Country Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>Segment the customer belongs to</description>
    <inlineHelpText>Segment the customer belongs to</inlineHelpText>
    <label>Customer Segment</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Has_Secondary_Users__c.field-meta.xml
<CustomField>
    <fullName>Has_Secondary_Users__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Secondary Users</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Unregistered__c.field-meta.xml
<CustomField>
    <fullName>Is_Unregistered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customers can use PayPal without registering for an account or do guest checkout even if they have one. This flag indicated whether the account is registered or not.</description>
    <inlineHelpText>Is this Account not registered yet?</inlineHelpText>
    <label>Is Unregistered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Customer&apos;s language</description>
    <inlineHelpText>Customer&apos;s language</inlineHelpText>
    <label>Language</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Customer&apos;s location within the country - like City</description>
    <inlineHelpText>Customer&apos;s location within the country - like City</inlineHelpText>
    <label>Location</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <description>Customer&apos;s timezone. This might be required to display some data like transaction log in customer&apos;s timezone rather than teammate&apos;s.</description>
    <inlineHelpText>Customer&apos;s timezone.</inlineHelpText>
    <label>Timezone</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Unregistered_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Unregistered_Account_Type__c</fullName>
    <description>If the account is not registered with PayPal, this field will indicate type of the account like Guest, WAX or DCC.</description>
    <inlineHelpText>If the account is not registered with PayPal, this field will indicate type of the account like Guest, WAX or DCC.</inlineHelpText>
    <label>Unregistered Account Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <description>We could have used &quot;Direct&quot; relationship to depict the relationship, but there are two reasons to going with custom field.
1) A party can be an owner for zero or one or more Accounts, but SF allows only one primary contact per contact which will not suit us.
2) More relationships may emerge in future</description>
    <inlineHelpText>Relationship between the contact and Account.</inlineHelpText>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIMARY_OWNER</fullName>
                <default>true</default>
                <label>PRIMARY_OWNER</label>
            </value>
            <value>
                <fullName>SECONDARY_USER</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Customer&apos;s Age</description>
    <inlineHelpText>Customer&apos;s Age</inlineHelpText>
    <label>Age</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Full Name of the customer. This value comes from PayPal domain and we need a separate field since Name in Contact object is not writable.</description>
    <inlineHelpText>Full Name of the customer.</inlineHelpText>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <description>Party Id that identifies the User/Party in PayPal system</description>
    <externalId>true</externalId>
    <inlineHelpText>Party Id that identifies the User/Party in PayPal system</inlineHelpText>
    <label>Party Id</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <description>Customer&apos;s profile picture</description>
    <inlineHelpText>Customer&apos;s profile picture</inlineHelpText>
    <label>Profile Picture</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/Contact_Address__c.object-meta.xml
<CustomObject>
    <description>Addresses associated with the contact</description>
    <label>Contact Address</label>
    <nameField>
        <label>Contact Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Address__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation Status of the address in the profile</description>
    <inlineHelpText>Confirmation Status of the address in the profile</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this address primary?</description>
    <inlineHelpText>Is this address primary?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the address in the profile</description>
    <inlineHelpText>Status of the address in the profile</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of address - Home / Work / etc.,</description>
    <inlineHelpText>Type of address - Home / Work / etc.,</inlineHelpText>
    <label>Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/Contact_Email__c.object-meta.xml
<CustomObject>
    <description>Email addresses associated with the contact / user.</description>
    <label>Contact Email</label>
    <nameField>
        <label>Contact Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Email__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation status of the email in the profile</description>
    <inlineHelpText>Confirmation status of the email in the profile</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>Email Address</description>
    <inlineHelpText>Email Address</inlineHelpText>
    <label>Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this email Primary?</description>
    <inlineHelpText>Is this email Primary?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the email within the profile</description>
    <inlineHelpText>Current status of the email within the profile</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/Contact_Phone__c.object-meta.xml
<CustomObject>
    <description>Phone numbers associated with an account</description>
    <label>Contact Phone</label>
    <nameField>
        <label>Contact Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Phone__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation status of the phone number in the profile</description>
    <inlineHelpText>Confirmation status of the phone number in the profile</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country code of the Phone - 1 for US, 91 for India and so on</description>
    <inlineHelpText>Country code of the Phone</inlineHelpText>
    <label>Country Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this phone primary?</description>
    <inlineHelpText>Is this phone primary?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the phone number in the profile</description>
    <inlineHelpText>Current status of the phone number in the profile</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of phone number - like home/mobile/office/etc.,</description>
    <inlineHelpText>Type of phone number - like home/mobile/office/etc.,</inlineHelpText>
    <label>Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BasicProfileAPI.cls
public class BasicProfileAPI {

    // Map Basic Profile information to Customer360SO
    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('BasicProfileAPI:mapResponseToCustomer360SO - mapping Basic Profile Information');
        
        // Check if there are any failures in loading Basic Profile
        if (response.isBasicProfileFailed() || (response.getCustomer360DO().profile == null))
        {
            System.debug('Customer360 API response does not have any Basic Profile information');
            return cx360SO;
        }
        
        // Map Basic profile Information to the cx360SO object passed in the request
        cx360SO.acct = mapResponseToAccount(cx360SO.acct, response.getCustomer360DO().profile);
        cx360SO.primaryUser.user = mapResponseToContact(cx360SO.primaryUser.user, response.getCustomer360DO().profile);

        return cx360SO;
    }

    // Store Basic Profile information to Salesforce object - Both Account and Contact
    public static ProfileAPI.InsertToSOHelper storeResponseInSObject(ProfileAPI.InsertToSOHelper soHelper, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('BasicProfileAPI:storeResponseInSObject - Storing Basic Profile Information into SObject');

        ProfileDO profile = response.getCustomer360DO().profile;
        
        // Check if there basic profile is failed completetly or if the party id is blank, we cannot proceed further here
        if (response.isBasicProfileFailed() || String.isBlank(profile.party_id))
        {
            System.debug(LoggingLevel.ERROR, 'Customer360 API did not successfully load the basic profile information');
            return soHelper;
        }
        
        // Map Basic profile Information to the account object
        soHelper.acct = mapResponseToAccount(soHelper.acct, profile);

        List<Contact> contacts = queryContactAndItsRelationships(soHelper.acct.Id, profile.party_id);
        Contact ct = null;

        if (contacts.size() == 0)
        {
            // Great, looks like we got a brand new Contact to deal with, lets go ahead and set it up
            System.debug(LoggingLevel.ERROR, 'There are no existing contacts with Party Id - ' + profile.party_id);

            ct = new Contact();
            ct = mapResponseToContact(ct, profile);

            // Since this is the first time contact creation, we need to make sure the account is marked
            // as direct ownership - otherwise the private contacts will have some issues
            // Direct ownership will automatically create an entry in AccountContactRelationship table and
            // mark this relationship as "PRIMARY OWNER' by default.
            ct.AccountId = soHelper.acct.Id;

            // Check if the account is already having a PRIMARY OWNER in which case we need to remove that
            // relationship. We cannot delete that relationship record since the it could be a direct relationship
            // with that old contact which Salesforce will not allow us to remove.
            // We have mark that old relationship as NONE
            clearCurrentPrimaryOwnerForAccount(soHelper.acct.Id);

            // Lets go ahead and insert the newly created contact, this will create contact and primary owner
            // relationship with the account
            insert ct;

            soHelper.ct = ct;
            soHelper.newContact = true;
        }
        else
        {
            ct = contacts[0];
            System.debug('No of retrieved contacts - ' + contacts.size() + ', Identified Contact - ' + ct.Id);

            ct = mapResponseToContact(ct, profile);

            // We need to make sure the current account and contact is having PRIMARY OWNER relationship if not already
            // It is possible for the ownership to change at any point of time though its not frequent

            if (ct.AccountContactRelations.size() > 0)
            {
                System.debug('The Account and Contact already has some relationship');
                
                // We have located the relationship record between the Account and Contact
                // Salesforce allows only one relationship record between an account and contact, so we dont need to worry about
                // having or dealing with multiple relationship records here
                AccountContactRelation relation = ct.AccountContactRelations[0];
                if (relation.Relationship__c != 'PRIMARY_OWNER')
                {
                    System.debug('The current relationship is not PRIMARY OWNER. It is - ' + relation.Relationship__c);

                    // The curent relationship between the account and the contact is not primary
                    // We need to check and clear if the account is already having a primary relationship with some other contact
                    clearCurrentPrimaryOwnerForAccount(soHelper.acct.Id);

                    // Lets update the current relationship to PRIMARY OWNER
                    relation.Relationship__c = 'PRIMARY_OWNER';
                    update relation;
                }
                else 
                {
                    System.debug('This account and contact is already having PRIMARY OWNER relationship - no need to do anything');
                }
            }
            else 
            {
                // Contact is already existing, but the contact is not linked with the account. Now we need to link the Account and Contact.
                System.debug('The Account and Contact is existing - but does not having any relationship yet');

                // Lets clear if the Account is having PRIMARY OWNER relationship with any other Contact
                clearCurrentPrimaryOwnerForAccount(soHelper.acct.Id);

                // Just check if the contact is a Private Contact - The possibility for this is very rare since we will always associate an
                // account whenever we create a contact - either it is PRIMARY OWNER or SECONDARY USER, but lets capture that scenario here
                // to make this code more reliable
                if (ct.AccountId == null)
                {
                    System.debug('The Contact is not linked with any account yet - its a private contact.');

                    // Lets just add this as a primary account which will automatically take care of creating a new relationship between this
                    // account and the contact and mark that relationship as PRIMARY OWNER as well
                    ct.AccountId = soHelper.acct.Id;
                }
                else
                {
                    System.debug('Creating a new PRIMARY OWNER relationship between the Account and Contact');

                    // Lets go ahead and create a new PRIMARY OWNER relationship between the account and contact
                    AccountContactRelation relation = new AccountContactRelation();
                    relation.AccountId = soHelper.acct.Id;
                    relation.ContactId = ct.Id;
                    relation.Relationship__c = 'PRIMARY_OWNER';
                    insert relation;
                }
            }

            // Lot of hard work is done, lets go ahead and update the helper object with the contact
            soHelper.ct = ct;
            soHelper.newContact = false;
        }

        // If Basic profile is successfully loaded without any issue (NOT a failure or partial success), lets update the basic profile
        // loaded time in Account object
        if (response.isBasicProfileSuccessfullyLoaded())
        {
            soHelper.acct.Basic_Profile_Loaded_Time__c = DateTime.now();
        }

        return soHelper;
    }

    private static void clearCurrentPrimaryOwnerForAccount(Id accountId)
    {
        // Query the PRIMARY OWNER relationships for the account
        List<AccountContactRelation> relations = queryPrimaryOwnerOfAccount(accountId);

        if (relations.size() == 0)
        {
            System.debug('There are no existing primary owners for the account - ' + accountId);
            return;
        }

        for (AccountContactRelation relation : relations)
        {
            // Clear the relationship by marking it as NONE
            relation.Relationship__c = 'NONE';
        }

        update relations;
        System.debug('Cleared all existing primary owners for the account - ' + accountId + ', No of primary owners - ' + relations.size());
        return;
    }

    private static Account mapResponseToAccount(Account acct, ProfileDO profile)
    {
        acct.Account_Number_Encrypted__c = profile.account_id;
        acct.AccountNumber = profile.account_number;
        acct.Account_Type__c = profile.account_type;
        acct.Account_Subtype__c = profile.account_subtype;
        acct.Account_Status__c = profile.account_status;
        acct.Location__c = profile.location;
        acct.Language__c = profile.language;
        acct.Country_Code__c = profile.legal_country_code;
        acct.Country_Name__c = profile.legal_country_name;
        acct.Timezone__c = profile.timezone;
        acct.Account_Created_Time__c = profile.create_time;
        acct.Customer_Segment__c = profile.customer_segment;
        acct.Has_Secondary_Users__c = profile.has_secondary_users;

        System.debug('Account Type - ' + profile.account_type);

        // Account name should be assigned with profile name only for non-business accounts
        // For Business Accounts, we will assign the actual business name from the business details
        if (String.isNotBlank(profile.account_type) && (!profile.account_type.equalsIgnoreCase('business')))
        {
            acct.Name = profile.full_name;
        }

        // Guest/Wax account
        if (String.isNotBlank(profile.registration_type))
        {
            // Registration type 'FULL' indicates that the account is properly registered PayPal Account
            // Anything else can be treated as unregistered - which is GUEST or ANONYMOUS
            if (!profile.registration_type.equalsIgnoreCase('full'))
            {
                acct.Is_Unregistered__c = true;
                acct.Unregistered_Account_Type__c = profile.registration_type;
            }
        }

        return acct;
    }

    private static Contact mapResponseToContact(Contact ct, ProfileDO profile)
    {
        ct.Party_Id__c = profile.party_id;
        ct.Full_Name__c = profile.full_name;
        ct.FirstName = profile.first_name;
        ct.LastName = profile.last_name;
        ct.Profile_Picture__c = profile.logo_url;
        ct.Age__c = profile.age;

        return ct;
    }

    public static List<Contact> queryContactAndItsRelationships(Id accountId, String partyId)
    {
        return [SELECT Id, AccountId, Party_Id__c, Full_Name__c, FirstName, LastName, Profile_Picture__c, Age__c,
                        (SELECT Id, Email_Address__c, Is_Primary__c, Status__c, Confirmation_Status__c, Trust_Status__c, Is_Active__c, 
                        Is_Confirmed__c, Is_Trusted__c 
                        FROM Contact_Emails__r),
                        (SELECT Id, Country_Code__c, Phone_Number__c, Type__c, Status__c, Confirmation_Status__c, Trust_Status__c, Is_Primary__c,
                        Is_Active__c, Is_Confirmed__c, Is_Trusted__c
                        FROM Contact_Phones__r),
                        (SELECT Id, Address_Line_1__c, Address_Line_2__c, Address_Line_3__c, Admin_Area_4__c, Admin_Area_3__c,
                        Admin_Area_2__c, Admin_Area_1__c, Country__c, Postal_Code__c, Type__c, Status__c, Confirmation_Status__c, Is_Primary__c,
                        Is_Active__c, Is_Confirmed__c
                        FROM Contact_Addresses__r),
                        (SELECT Id, AccountId, ContactId, Relationship__c 
                        FROM AccountContactRelations WHERE AccountId = :accountId),
                Email_Loaded_Time__c, Phone_Loaded_Time__c, Address_Loaded_Time__c 
                FROM Contact WHERE Party_Id__c=:partyId
               ];
    }

    private static List<AccountContactRelation> queryPrimaryOwnerOfAccount(Id accountId)
    {
        return [SELECT Id, AccountId, ContactId, Relationship__c
                FROM AccountContactRelation 
                WHERE AccountId=:accountId AND Relationship__c = 'PRIMARY_OWNER'];
    }
}