force-app/main/default/objects/Account/fields/ActivityLog_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>ActivityLog_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>ActivityLog Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/Activity_Log__c.object-meta.xml
<CustomObject>
    <description>Activity Logs associated with an account</description>
    <label>Activity Log</label>
    <nameField>
        <label>Activity Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Activity logs associated with an account</description>
    <inlineHelpText>Activity logs associated with an account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activity Logs</relationshipLabel>
    <relationshipName>Activity_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Action_Data__c.field-meta.xml
<CustomField>
    <fullName>Action_Data__c</fullName>
    <description>Activity Log action data which has details about the activity</description>
    <inlineHelpText>Activity Log action data which has details about the activity</inlineHelpText>
    <label>Action Data</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <description>Activity Log Action Type</description>
    <inlineHelpText>Activity Log Action Type</inlineHelpText>
    <label>Action Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Action_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Action_Type_Id__c</fullName>
    <description>Id associated with the action type</description>
    <inlineHelpText>Id associated with the action type</inlineHelpText>
    <label>Action Type Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Activity_Log_Id__c.field-meta.xml
<CustomField>
    <fullName>Activity_Log_Id__c</fullName>
    <description>Unique Identifier for the activity log</description>
    <inlineHelpText>Unique Identifier for the activity log</inlineHelpText>
    <label>Activity Log Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <description>Name of the actor - like teammate user id or customer email and so on</description>
    <inlineHelpText>Name of the actor - like teammate user id or customer email and so on</inlineHelpText>
    <label>Actor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/IP_Address__c.field-meta.xml
<CustomField>
    <fullName>IP_Address__c</fullName>
    <description>IP Address associated with the activity</description>
    <inlineHelpText>IP Address associated with the activity</inlineHelpText>
    <label>IP Address</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Time_Created__c.field-meta.xml
<CustomField>
    <fullName>Time_Created__c</fullName>
    <description>Activity Log Created Time</description>
    <inlineHelpText>Activity Log Created Time</inlineHelpText>
    <label>Time Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Activity_Log__c/fields/Visitor_Id__c.field-meta.xml
<CustomField>
    <fullName>Visitor_Id__c</fullName>
    <description>Visitor Id associated with the activity</description>
    <inlineHelpText>Visitor Id associated with the activity</inlineHelpText>
    <label>Visitor Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ActivityLogAPI.cls
public class ActivityLogAPI {
    
    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('ActivityLogAPI:mapResponseToCustomer360SO - mapping Activity Log Information');
        
        // Check if there are any failures in loading PayPal activity logs
        if (response.isActivityLogsFailed() || (response.getCustomer360DO().activities == null) ||
            (response.getCustomer360DO().activities.size() == 0))
        {
            System.debug('No Activity logs available in Customer360 API response');
            return cx360SO;
        }
        
        // Map Activity logs to the cx360SO object passed in the request
        for (ActivityLogDO activity : response.getCustomer360DO().activities)
        {
            cx360SO.activityLogs.add(mapActivityLogDOToSO(activity));
        }

        return cx360SO;
    }

    public static Account storeResponseInSObject(Account acct, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('ActivityLogAPI:storeResponseInSObject - Storing Activity Logs to SObject');
        
        // Check if there are any failures in loading Activity Logs
        if (response.isActivityLogsFailed())
        {
            System.debug('Customer360 API did not successfully load Activity logs');
            return acct;
        }

        // Remove all Activity Logs from the account
        removeActivityLogsFromAccount(acct);

        List<ActivityLogDO> activities = response.getCustomer360DO().activities;
        
        if ((activities != null) && (activities.size() > 0))
        {
            List<Activity_Log__c> activityObjs = new List<Activity_Log__c>();

            for (ActivityLogDO act : activities)
            {
                Activity_Log__c activityObj = mapActivityLogDOToSO(act);
                activityObj.Account__c = acct.Id;
                activityObjs.add(activityObj);
            }

            insert activityObjs;
        }

        // If Activity logs are successfully loaded (NOT a failure or partial success), update the cache time
        if (response.isActivityLogsSuccessfullyLoaded())
        {
            acct.ActivityLog_Loaded_Time__c = Datetime.now();
        }

        return acct;
    }

    private static void removeActivityLogsFromAccount(Account acct)
    {
        List<Activity_Log__c> activities = queryActivityLogsFromAccount(acct.Id);
        System.debug('Removing existing Activity Logs from the account. Number of records found - ' + activities.size());
        if (activities.size() > 0)
        {
            delete activities;
        }
        return;
    }

    private static Activity_Log__c mapActivityLogDOToSO(ActivityLogDO activity)
    {
        Activity_Log__c actLog = new Activity_Log__c();
        actLog.Activity_Log_Id__c = activity.activity_id;
        actLog.Time_Created__c = activity.create_time;
        actLog.IP_Address__c = activity.ip;
        actLog.Visitor_Id__c = activity.visitor_id;
        actLog.Actor__c = activity.actor;
        actLog.Action_Type__c = activity.action_type;
        actLog.Action_Type_Id__c = activity.action_type_id;
        actLog.Action_Data__c = activity.meta_data;
        
        return actLog;
    }

    private static List<Activity_Log__c> queryActivityLogsFromAccount(Id accountId)
    {
        return [SELECT Id, Account__c FROM Activity_Log__c
                WHERE Account__c=:accountId];
    }
}