force-app/main/default/objects/Account/fields/Admin_Merchant_Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Admin_Merchant_Category_Code__c</fullName>
    <description>This is the merchant category code entered by the teammate based on his/her assessment which could be different than the one given by the user at the time of PayPal account registration.</description>
    <inlineHelpText>This is the merchant category code entered by the teammate based on his/her assessment which could be different than the one given by the user at the time of PayPal account registration.</inlineHelpText>
    <label>Admin Merchant Category Code</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Average_Monthly_TPV__c.field-meta.xml
<CustomField>
    <fullName>Average_Monthly_TPV__c</fullName>
    <description>Monthly TPV String</description>
    <inlineHelpText>Monthly TPV String</inlineHelpText>
    <label>Average Monthly TPV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Info_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Business_Info_Loaded_Time__c</fullName>
    <description>For cache TTL Purposes</description>
    <inlineHelpText>For cache TTL Purposes</inlineHelpText>
    <label>Business Info Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Service_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Email__c</fullName>
    <description>Customer service email of the merchant</description>
    <inlineHelpText>Customer service email of the merchant</inlineHelpText>
    <label>Customer Service Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Service_Phone__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Phone__c</fullName>
    <inlineHelpText>Customer service phone number of the Merchant.</inlineHelpText>
    <label>Customer Service Phone</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Industry_Name__c.field-meta.xml
<CustomField>
    <fullName>Industry_Name__c</fullName>
    <description>Merchant&apos;s industry</description>
    <inlineHelpText>Merchant&apos;s industry</inlineHelpText>
    <label>Industry Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Merchant_Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Category_Code__c</fullName>
    <description>MCC code of the merchant</description>
    <inlineHelpText>MCC code of the merchant</inlineHelpText>
    <label>Merchant Category Code</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monthly_TPV_Lower_Bound_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_TPV_Lower_Bound_Amount__c</fullName>
    <label>Monthly TPV Lower Bound Amount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monthly_TPV_Lower_Bound_Currency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_TPV_Lower_Bound_Currency__c</fullName>
    <label>Monthly TPV Lower Bound Currency</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monthly_TPV_Upper_Bound_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_TPV_Upper_Bound_Amount__c</fullName>
    <label>Monthly TPV Upper Bound Amount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monthly_TPV_Upper_Bound_Currency__c.field-meta.xml
<CustomField>
    <fullName>Monthly_TPV_Upper_Bound_Currency__c</fullName>
    <label>Monthly TPV Upper Bound Currency</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/Business_Address__c.object-meta.xml
<CustomObject>
    <description>Custom object to store one or more addresses associated with the business account</description>
    <label>Business Address</label>
    <nameField>
        <label>Business Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account to which this Business Address is associated</description>
    <inlineHelpText>Account to which this Business Address is associated</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Addresses</relationshipLabel>
    <relationshipName>Business_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Address_Id__c</fullName>
    <description>Unique identifier for the address which we can pass to appropriate micro services to perform updates if necessary.</description>
    <inlineHelpText>Unique identifier for the address which we can pass to appropriate micro services to perform updates if necessary.</inlineHelpText>
    <label>Address Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>The first line of the address. For example, number or street. For example, `173 Drury Lane`. Required for data entry and compliance and risk checks. Must contain the full address.</description>
    <inlineHelpText>The first line of the address. For example, number or street. For example, `173 Drury Lane`. Required for data entry and compliance and risk checks. Must contain the full address.</inlineHelpText>
    <label>Address Line 1</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>The second line of the address. For example, suite or apartment number.</description>
    <inlineHelpText>The second line of the address. For example, suite or apartment number.</inlineHelpText>
    <label>Address Line 2</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <description>The third line of the address, if needed. For example, a street complement for Brazil, direction text, such as `next to Walmart`, or a landmark in an Indian address.</description>
    <inlineHelpText>The third line of the address, if needed. For example, a street complement for Brazil, direction text, such as `next to Walmart`, or a landmark in an Indian address.</inlineHelpText>
    <label>Address Line 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Admin_Area_1__c.field-meta.xml
<CustomField>
    <fullName>Admin_Area_1__c</fullName>
    <description>The highest level sub-division in a country, which is usually a province, state, or ISO-3166-2 subdivision. Format for postal delivery. For example, &apos;CA&apos; and not &apos;California&apos;. Value, by country, is:
UK. A county.
US. A state.
Canada. A province.
Japan. A prefecture.
Switzerland. A kanton.</description>
    <inlineHelpText>The highest level sub-division in a country, which is usually a province, state, or ISO-3166-2 subdivision.</inlineHelpText>
    <label>Admin Area 1</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Admin_Area_2__c.field-meta.xml
<CustomField>
    <fullName>Admin_Area_2__c</fullName>
    <description>A city, town, or village. Smaller than &apos;admin_area_level_1&apos;.</description>
    <inlineHelpText>A city, town, or village. Smaller than &apos;admin_area_level_1&apos;.</inlineHelpText>
    <label>Admin Area 2</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Admin_Area_3__c.field-meta.xml
<CustomField>
    <fullName>Admin_Area_3__c</fullName>
    <description>A sub-locality, suburb, neighborhood, or district. Smaller than &apos;admin_area_level_2&apos;. Value is:
Brazil. Suburb, bairro, or neighborhood.
India. Sub-locality or district. Street name information is not always available but a sub-locality or district can be a very small area.</description>
    <inlineHelpText>A sub-locality, suburb, neighborhood, or district. Smaller than &apos;admin_area_level_2&apos;.</inlineHelpText>
    <label>Admin Area 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Admin_Area_4__c.field-meta.xml
<CustomField>
    <fullName>Admin_Area_4__c</fullName>
    <description>The neighborhood, ward, or district. Smaller than &apos;admin_area_level_3&apos; or &apos;sub_locality&apos;. Value is: 
The postal sorting code for Guernsey and many French territories, such as French Guiana.
The fine-grained administrative levels in China.</description>
    <inlineHelpText>The neighborhood, ward, or district. Smaller than &apos;admin_area_level_3&apos; or &apos;sub_locality&apos;.</inlineHelpText>
    <label>Admin Area 4</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Address Confirmation Status</description>
    <inlineHelpText>Address Confirmation Status</inlineHelpText>
    <label>Confirmation Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country Code</description>
    <inlineHelpText>Country Code</inlineHelpText>
    <label>Country</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Is_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Is_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>The postal code, which is the zip code or equivalent. Typically required for countries with a postal code or an equivalent. See [postal code](https://en.wikipedia.org/wiki/Postal_code).</description>
    <inlineHelpText>The postal code, which is the zip code or equivalent.</inlineHelpText>
    <label>Postal Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Address Status</description>
    <inlineHelpText>Address Status</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Tags_JSON__c.field-meta.xml
<CustomField>
    <fullName>Tags_JSON__c</fullName>
    <label>Tags JSON</label>
    <length>512</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Address Type</description>
    <inlineHelpText>Address Type</inlineHelpText>
    <label>Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BusinessDetailsAPI.cls
public class BusinessDetailsAPI {
    
    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('BusinessDetailsAPI:mapResponseToCustomer360SO - Mapping Business Information');

        if (response.isBusinessInfoFailed() || (response.getCustomer360DO().business_details == null))
        {
            System.debug('Customer360 API response does not have any Business details');
            return cx360SO;
        }

        cx360SO.acct = mapBusinessDetailsDOToAccount(cx360SO.acct, response.getCustomer360DO().business_details);

        if (response.getCustomer360DO().business_details.business_address != null)
        {
            cx360SO.businessAddresses.add(mapAddressDOToBusinessAddress(response.getCustomer360DO().business_details.business_address));
        }
        else
        {
            System.debug('Business Address is missing in the Business Details - so ignoring the mapping');
        }

        return cx360SO;
    }

    public static Account storeResponseInSObject(Account acct, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('BusinessDetailsAPI:storeResponseInSObject - Storing Business Information into SObject');

        BusinessDetailsDO businessDetails = response.getCustomer360DO().business_details;

        if (response.isBusinessInfoFailed())
        {
            System.debug('Customer360 API response did not successfully load the Business details');
            return acct;
        }

        // Remove old business addresses associated with the account
        removeBusinessAddressesFromAccount(acct);

        if (businessDetails != null)
        {
            acct = mapBusinessDetailsDOToAccount(acct, businessDetails);

            if (businessDetails.business_address != null)
            {
                Business_Address__c address = mapAddressDOToBusinessAddress(businessDetails.business_address);
                address.Account__c = acct.Id;
                insert address;
            }
            else
            {
                System.debug('Business Address is missing in the Business Details - so ignoring the mapping');
            }
        }

        // If Business information is loaded successfully (NOT a failure or partial success), let us update the cache time
        if (response.isBusinessInfoSuccessfullyLoaded())
        {
            acct.Business_Info_Loaded_Time__c = Datetime.now();
        }

        return acct;
    }

    private static void removeBusinessAddressesFromAccount(Account acct)
    {
        List<Business_Address__c> addresses = queryBusinessAddressesFromAccount(acct.Id);
        System.debug('Removing existing business addresses from the account. Number of business addresses found - ' + addresses.size());
        if (addresses.size() > 0)
        {
            delete addresses;
        }
        return;
    }

    private static Account mapBusinessDetailsDOToAccount(Account acct, BusinessDetailsDO businessDetails)
    {
        acct.Industry_Name__c = businessDetails.industry_name;
        acct.Merchant_Category_Code__c = businessDetails.merchant_category_code;
        acct.Admin_Merchant_Category_Code__c = businessDetails.admin_merchant_category_code;
        acct.Customer_Service_Email__c = businessDetails.customer_service_email;
        acct.Customer_Service_Phone__c = businessDetails.customer_service_phone;

        // This is just for safety purposes, no harm in doing so too
        if (String.isNotBlank(businessDetails.business_name))
        {
            acct.Name = businessDetails.business_name;
        }

        // Map Monthly TPV related values
        if (businessDetails.average_monthly_volume != null)
        {
            // TBD - Get the final decision around service passing this value in fomatted String
            acct.Average_Monthly_TPV__c = businessDetails.average_monthly_volume.average_monthly_volume_str;

            // TPV Lower Bound
            if (businessDetails.average_monthly_volume.lower_bound != null)
            {
                try {
                    acct.Monthly_TPV_Lower_Bound_Amount__c = Decimal.valueOf(businessDetails.average_monthly_volume.lower_bound.value);
                    acct.Monthly_TPV_Lower_Bound_Currency__c = businessDetails.average_monthly_volume.lower_bound.currency_code;
                }
                catch(Exception e) {
                    System.debug('Monthly TPV Lower Bound Exception: ' + e.getMessage() + ', Failed to convert from String to Decimal - ' 
                                                                       + JSON.serialize(businessDetails.average_monthly_volume.lower_bound));
                }
            }

            // TPV Upper Bound
            if (businessDetails.average_monthly_volume.upper_bound != null)
            {
                try {
                    acct.Monthly_TPV_Upper_Bound_Amount__c = Decimal.valueOf(businessDetails.average_monthly_volume.upper_bound.value);
                    acct.Monthly_TPV_Upper_Bound_Currency__c = businessDetails.average_monthly_volume.upper_bound.currency_code;
                }
                catch(Exception e) {
                    System.debug('Monthly TPV Upper Bound Exception: ' + e.getMessage() + ', Failed to convert from String to Decimal - ' 
                                                                       + JSON.serialize(businessDetails.average_monthly_volume.upper_bound));
                }
            }
        }

        return acct;
    }

    private static Business_Address__c mapAddressDOToBusinessAddress(AddressDO address)
    {
        Business_Address__c bAddress = new Business_Address__c();
        bAddress.Address_Id__c = address.address_id;
        bAddress.Type__c = address.address_type;
        bAddress.Tags_JSON__c = JSON.serialize(address.tags);
        bAddress.Status__c = address.status;
        bAddress.Confirmation_Status__c = address.confirmation_status;
        bAddress.Is_Primary__c = address.primary;
        
        if (address.address != null)
        {
            bAddress.Address_Line_1__c = address.address.address_line_1;
            bAddress.Address_Line_2__c = address.address.address_line_2;
            bAddress.Address_Line_3__c = address.address.address_line_3;
            bAddress.Admin_Area_4__c = address.address.admin_area_4;
            bAddress.Admin_Area_3__c = address.address.admin_area_3;
            bAddress.Admin_Area_2__c = address.address.admin_area_2;
            bAddress.Admin_Area_1__c = address.address.admin_area_1;
            bAddress.Postal_Code__c = address.address.postal_code;
            bAddress.Country__c = address.address.country_code;
        }

        // TBD - Address Type, confirm if we have separate type to identify home, work, etc.,

        // Is Address Active?
        if (String.isNotBlank(address.status) && address.status.equalsIgnoreCase('active'))
        {
            bAddress.Is_Active__c = true;
        }

        // Is Address Confirmed?
        if (String.isNotBlank(address.confirmation_status) && address.confirmation_status.equalsIgnoreCase('confirmed'))
        {
            bAddress.Is_Confirmed__c = true;
        }

        return bAddress;
    }

    private static List<Business_Address__c> queryBusinessAddressesFromAccount(Id accountId)
    {
        return [SELECT Id, Account__c FROM Business_Address__c
                WHERE Account__c=:accountId];
    }
}