force-app/main/default/objects/Account/fields/CIP_Status__c.field-meta.xml
<CustomField>
    <fullName>CIP_Status__c</fullName>
    <description>Customer&apos;s CIP status, basically the KYC.</description>
    <inlineHelpText>CIP status of the customer</inlineHelpText>
    <label>CIP Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>ISO Country Code for the account&apos;s legal country</description>
    <inlineHelpText>ISO Country Code for the account&apos;s legal country</inlineHelpText>
    <label>Country Code</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_User_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Secondary_User_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Secondary User Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Can_Contact_CS__c.field-meta.xml
<CustomField>
    <fullName>Can_Contact_CS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can Contact CS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <description>We could have used &quot;Direct&quot; relationship to depict the relationship, but there are two reasons to going with custom field.
1) A party can be an owner for zero or one or more Accounts, but SF allows only one primary contact per contact which will not suit us.
2) More relationships may emerge in future</description>
    <inlineHelpText>Relationship between the contact and Account.</inlineHelpText>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIMARY_OWNER</fullName>
                <default>true</default>
                <label>PRIMARY_OWNER</label>
            </value>
            <value>
                <fullName>SECONDARY_USER</fullName>
            </value>
            <value>
                <fullName>NONE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Customer&apos;s Age</description>
    <inlineHelpText>Customer&apos;s Age</inlineHelpText>
    <label>Age</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CIP_Status__c.field-meta.xml
<CustomField>
    <fullName>CIP_Status__c</fullName>
    <description>Customer&apos;s CIP status</description>
    <inlineHelpText>Customer&apos;s CIP status</inlineHelpText>
    <label>CIP Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <description>Full Name of the customer. This value comes from PayPal domain and we need a separate field since Name in Contact object is not writable.</description>
    <inlineHelpText>Full Name of the customer.</inlineHelpText>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Party_Id__c.field-meta.xml
<CustomField>
    <fullName>Party_Id__c</fullName>
    <description>Party Id that identifies the User/Party in PayPal system</description>
    <externalId>true</externalId>
    <inlineHelpText>Party Id that identifies the User/Party in PayPal system</inlineHelpText>
    <label>Party Id</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Party_Info_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Party_Info_Loaded_Time__c</fullName>
    <label>Party Info Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <description>Customer&apos;s profile picture</description>
    <inlineHelpText>Customer&apos;s profile picture</inlineHelpText>
    <label>Profile Picture</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/Contact_Address__c.object-meta.xml
<CustomObject>
    <description>Addresses associated with the contact</description>
    <label>Contact Address</label>
    <nameField>
        <label>Contact Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Address Line 1</description>
    <inlineHelpText>Address Line 1</inlineHelpText>
    <label>Address Line 1</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Address Line 2</description>
    <inlineHelpText>Address Line 2</inlineHelpText>
    <label>Address Line 2</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <description>Address Line 3</description>
    <inlineHelpText>Address Line 3</inlineHelpText>
    <label>Address Line 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Admin_Area_3__c.field-meta.xml
<CustomField>
    <fullName>Admin_Area_3__c</fullName>
    <description>Admin Area 3</description>
    <inlineHelpText>Admin Area 3</inlineHelpText>
    <label>Admin Area 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Admin_Area_4__c.field-meta.xml
<CustomField>
    <fullName>Admin_Area_4__c</fullName>
    <description>Admin Area 4</description>
    <inlineHelpText>Admin Area 4</inlineHelpText>
    <label>Admin Area 4</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation Status of the address in the profile</description>
    <inlineHelpText>Confirmation Status of the address in the profile</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact to which the address is associated</description>
    <inlineHelpText>Contact to which the address is associated</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Addresses</relationshipLabel>
    <relationshipName>Contact_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this address primary?</description>
    <inlineHelpText>Is this address primary?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the address in the profile</description>
    <inlineHelpText>Status of the address in the profile</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of address - Home / Work / etc.,</description>
    <inlineHelpText>Type of address - Home / Work / etc.,</inlineHelpText>
    <label>Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/Contact_Email__c.object-meta.xml
<CustomObject>
    <description>Email addresses associated with the contact / user.</description>
    <label>Contact Email</label>
    <nameField>
        <label>Contact Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Email__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation status of the email in the profile</description>
    <inlineHelpText>Confirmation status of the email in the profile</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Emails associated with the contact</description>
    <inlineHelpText>Emails associated with the contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Emails</relationshipLabel>
    <relationshipName>Contact_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>Email Address</description>
    <inlineHelpText>Email Address</inlineHelpText>
    <label>Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this email Primary?</description>
    <inlineHelpText>Is this email Primary?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the email within the profile</description>
    <inlineHelpText>Current status of the email within the profile</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Trust_Status__c.field-meta.xml
<CustomField>
    <fullName>Trust_Status__c</fullName>
    <description>Trust Status of the Email</description>
    <inlineHelpText>Trust Status of the Email</inlineHelpText>
    <label>Trust Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/Contact_Phone__c.object-meta.xml
<CustomObject>
    <description>Phone numbers associated with an account</description>
    <label>Contact Phone</label>
    <nameField>
        <label>Contact Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Phone__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation status of the phone number in the profile</description>
    <inlineHelpText>Confirmation status of the phone number in the profile</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Phone numbers associated with a contact</description>
    <inlineHelpText>Phone numbers associated with a contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Phones</relationshipLabel>
    <relationshipName>Contact_Phones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country code of the Phone - 1 for US, 91 for India and so on</description>
    <inlineHelpText>Country code of the Phone</inlineHelpText>
    <label>Country Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this phone primary?</description>
    <inlineHelpText>Is this phone primary?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Is_Trusted__c.field-meta.xml
<CustomField>
    <fullName>Is_Trusted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Trusted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Phone number</description>
    <inlineHelpText>Phone number</inlineHelpText>
    <label>Phone Number</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the phone number in the profile</description>
    <inlineHelpText>Current status of the phone number in the profile</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Trust_Status__c.field-meta.xml
<CustomField>
    <fullName>Trust_Status__c</fullName>
    <description>Trust status of the Phone</description>
    <inlineHelpText>Trust status of the Phone</inlineHelpText>
    <label>Trust Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of phone number - like home/mobile/office/etc.,</description>
    <inlineHelpText>Type of phone number - like home/mobile/office/etc.,</inlineHelpText>
    <label>Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SecondaryUserAPI.cls
public class SecondaryUserAPI {

    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('SecondaryUserAPI:mapResponseToCustomer360SO - mapping Secondary Users');
        
        // Check if there are any failures in loading Secondary Users
        if (response.isSecondaryUsersFailed() || (response.getCustomer360DO().secondary_users == null) ||
            (response.getCustomer360DO().secondary_users.size() == 0))
        {
            System.debug('Customer360 API response does not have any Secondary Users');
            return cx360SO;
        }

        // Map details per secondary user
        for (SecondaryUserDO secUser : response.getCustomer360DO().secondary_users)
        {
            cx360SO.secondaryUsers.add(mapSecondaryUserDOToSO(secUser));
        }

        return cx360SO;
    }

    public static Account storeResponseInSObject(Account acct, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('SecondaryUserAPI:mapResponseToCustomer360SO - Storing Secondary Users to SObject');
        
        // Check if there are any failures in loading Secondary Users
        if (response.isSecondaryUsersFailed())
        {
            System.debug('Customer360 API did not successfully load any Secondary Users');
            return acct;
        }

        // Clear all Secondary user relationships for the account
        // Even if there are no secondary users currently associated with the customer, there is a chance that the
        // acount may have had a secondary users assigned before and that relationship has to be cleared in SF.
        removeAllSecondaryUserRelationships(acct);

        List<SecondaryUserDO> users = response.getCustomer360DO().secondary_users;

        if ((users != null) && (users.size() > 0))
        {
            System.debug('Number of secondary users in the response - ' + users.size());

            // Lets get all party ids from the secondary users list
            List<String> partyIds = new List<String>();
            Map<String, SecondaryUserDO> partyIdToSecondaryUserMap = new Map<String, SecondaryUserDO>();

            for (SecondaryUserDO user : users)
            {
                if (String.isNotBlank(user.party_id) && (user.has_permission_to_speak))
                {
                    partyIds.add(user.party_id);
                    partyIdToSecondaryUserMap.put(user.party_id, user);
                }
            }

            // Query all contact records for the party ids received in the response
            List<Contact> contacts = queryContactAndItsRelationships(acct.Id, partyIds);
            System.debug('Number of contacts loaded from salesforce - ' + contacts.size());

            Map<String, Contact> partyIdToContactMap = new Map<String, Contact>();
            List<Contact> contactsToUpsert = new List<Contact>();
            List<SObject> recordsToDelete = new List<SObject>();
            List<SObject> recordsToInsert  = new List<SObject>();

            // Create a map between party id and the contact
            for (Contact ct : contacts)
            {
                partyIdToContactMap.put(ct.Party_Id__c, ct);
            }

            for (SecondaryUserDO user : users)
            {
                if (String.isBlank(user.party_id))
                {
                    System.debug(LoggingLevel.ERROR, 'Party Id is blank in the Customer360 data, let us continue with others');
                    continue;
                }

                if (!user.has_permission_to_speak)
                {
                    System.debug('Skipping the user since the Party does not have the permission to contact CS. Party ID - ' + user.party_id);
                    continue;
                }

                Contact ct = partyIdToContactMap.get(user.party_id);
                
                if (ct != null)
                {
                    // Contact record is alreay available for the party id, let us update the contact object with fresh values
                    ct = mapSecondaryUserToContact(ct, user);

                    if (response.isSecondaryUsersSuccessfullyLoaded()) {
                        ct.Party_Info_Loaded_Time__c = Datetime.now();
                    }

                    // Add all child records to be deleted - Phones, emails addresses
                    recordsToDelete.addAll(ct.Contact_Emails__r);
                    recordsToDelete.addAll(ct.Contact_Phones__r);
                    recordsToDelete.addAll(ct.Contact_Addresses__r);

                    // Relationship Handling
                    if (ct.AccountId == null)
                    {
                        // May be the party is not associated with any account yet, its a rare case
                        // This assignment will automatically create a new relationship and mark that relationship as 'PRIMARY OWNER',
                        // we can update it to 'SECONDARY USER' later.
                        ct.AccountId = acct.Id;
                    }
                    else
                    {
                        // Check if the current Account and Contact is already having a relationship, please note that we already filtered
                        // the account id in the query and hence the relationship retrieved will only be between this Account and Contact
                        if (ct.AccountContactRelations.size() == 0)
                        {
                            System.debug('This Account has no existing relationship with the Contact - ' + ct.Id + ', lets create a new one');
                            AccountContactRelation relation = new AccountContactRelation();
                            relation.AccountId = acct.Id;
                            relation.ContactId = ct.Id;
                            relation.Relationship__c = 'SECONDARY_USER';
                            
                            recordsToInsert.add(relation);
                        }
                        else
                        {
                            // There is already some relationship exist between this account and contact, let us not worry about
                            // what that relationship is since we will do a mass update of all relationships to 'SECONDARY USER' later
                        }
                    }

                    contactsToUpsert.add(ct);
                }
                else
                {
                    // Contact object is not available for the party yet, so we need to create a new one
                    ct = new Contact();
                    ct = mapSecondaryUserToContact(ct, user);

                    if (response.isSecondaryUsersSuccessfullyLoaded()) {
                        ct.Party_Info_Loaded_Time__c = Datetime.now();
                    }

                    // Since this is a fresh contact, we can straight away assign the account as primary which will automatically create
                    // a new relationship record as well. We will just need to update that relationship to SECONDARY USER - same mass update
                    ct.AccountId = acct.Id;
                    contactsToUpsert.add(ct);
                }
            }

            // Upsert Contacts - Existing contacts will be updated and new contacts will be inserted. We dont need to upsert using Party Id
            // here since we already loaded the contact records for existing ones and only the new ones has to be inserted
            if (contactsToUpsert.size() > 0)
            {
                System.debug('We got some contacts to upsert. Number of records - ' + contactsToUpsert.size());
                upsert contactsToUpsert;
            }

            List<Id> contactIdsToUpdateRelationship = new List<Id>();

            // Now that the required contacts are all updated or created, lets get to the business of adding emails, phones and addresses
            for (Contact ct : contactsToUpsert)
            {
                if (ct.Id == null)
                {
                    System.debug(LoggingLevel.ERROR, 'Id is not available after upsert for the Party Id - ' + ct.Party_Id__c);
                    continue;
                }

                SecondaryUserDO user = partyIdToSecondaryUserMap.get(ct.Party_Id__c);
                if (user == null)
                {
                    // This is extremely rare, but need to handle every scenario as a developer
                    System.debug(LoggingLevel.ERROR, 'User object retrieved from the map is null - this should never happen');
                    continue;
                }

                contactIdsToUpdateRelationship.add(ct.Id);

                // Add emails to insert list
                if ((user.emails != null) && (user.emails.size() > 0))
                {
                    for (EmailDO email : user.emails)
                    {
                        Contact_Email__c emailObj = ProfileEmailAPI.mapEmailDOToContactEmail(email);
                        emailObj.Contact__c = ct.Id;
                        recordsToInsert.add(emailObj);
                    }
                }

                // Add Phones to insert list
                if ((user.phone_numbers != null) && (user.phone_numbers.size() > 0))
                {
                    for (PhoneDO phone : user.phone_numbers)
                    {
                        Contact_Phone__c phoneObj = ProfilePhoneAPI.mapPhoneDOToContactPhone(phone);
                        phoneObj.Contact__c = ct.Id;
                        recordsToInsert.add(phoneObj);
                    }
                }

                // Add Addresses to insert list
                if ((user.addresses != null) && (user.addresses.size() > 0))
                {
                    for (AddressDO address : user.addresses)
                    {
                        Contact_Address__c addressObj = ProfileAddressAPI.mapAddressDOToContactAddress(address);
                        addressObj.Contact__c = ct.Id;
                        recordsToInsert.add(addressObj);
                    }
                }
            }

            // Delete all records that are marked for deletion
            if (recordsToDelete.size() > 0)
            {
                System.debug('We got some records to delete. Number of records - ' + recordsToDelete.size());
                delete recordsToDelete;
            }

            // Insert all records that are marked for insertion
            if (recordsToInsert.size() > 0)
            {
                System.debug('We got some records to insert. Number of records - ' + recordsToDelete.size());
                insert recordsToInsert;
            }

            // Now that we have made sure all the contacts are available and all relationships too - even though it
            // might all be in different statuses, we can just go ahead and update the relationship type like cake walk
            // Update all relationsips between this account and created/updated account ids to SECONDARY USERS
            updateAllRelationshipsToSecondaryUsers(acct, contactIdsToUpdateRelationship);
        }

        // If Secondary users info is successfully loaded (NOT a failure or partial success), update the cache time
        if (response.isSecondaryUsersSuccessfullyLoaded())
        {
            acct.Secondary_User_Loaded_Time__c = Datetime.now();
        }

        return acct;
    }

    private static void removeAllSecondaryUserRelationships(Account acct)
    {
        List<AccountContactRelation> relations = querySecondaryUsersForAccount(acct.Id);

        if (relations.size() == 0)
        {
            System.debug('There are no existing secondary users for the account - ' + acct.Id);
            return;
        }
        
        for (AccountContactRelation relation : relations)
        {
            // Clear the relationship by marking it as NONE
            relation.Relationship__c = 'NONE';
        }

        update relations;
        System.debug('Cleared all existing secondary users for the account - ' + acct.Id + ', No of secondary users - ' + relations.size());
        return;
    }

    private static void updateAllRelationshipsToSecondaryUsers(Account acct, List<Id> contactIds)
    {
        if (contactIds.size() == 0)
        {
            System.debug('Number of contact ids to update the relationship is zero');
            return;
        }

        List<AccountContactRelation> relations = queryRelationshipBetweenAccountAndContacts(acct.Id, contactIds);
        if (relations.size() == 0)
        {
            System.debug(LoggingLevel.ERROR, 'Number of relationships identified is zero');
            return;
        }

        for (AccountContactRelation relation : relations)
        {
            // Prefetch deals with only secondary users who has permission to speak with customer service. Only those
            // parties will be recorded in Salesforce and everything else has to be dealt in real time. Since we deal
            // with only the parties who has the permissions to speak, we are blindly assigning here. We also have a 
            // mechanism to filter out other parties when coming to storing it. So we are good here.
            relation.Can_Contact_CS__c = true;
            relation.Relationship__c = 'SECONDARY_USER';
        }

        update relations;
        System.debug('Updated all relationships for the Account as SECONDARY USER. Number of records updated - ' + relations.size());
        return;
    }

    private static ContactSO mapSecondaryUserDOToSO(SecondaryUserDO secUser)
    {
        ContactSO ctSo = new ContactSO();

        // Map the user details to Contact Object
        ctSo.user = mapSecondaryUserToContact(ctSo.user, secUser);

        // Map the secondary user attributes like login id, permissions and so on to SO Object
        ctSo.secondaryUserAttrbutes = mapSecondaryUserAttributesToSO(ctSo.secondaryUserAttrbutes, secUser);

        // Add emails
        if ((secUser.emails != null) && (secUser.emails.size() > 0))
        {
            for (EmailDO email : secUser.emails)
            {
                ctSo.emails.add(ProfileEmailAPI.mapEmailDOToContactEmail(email));
            }
        }

        // Add Phones
        if ((secUser.phone_numbers != null) && (secUser.phone_numbers.size() > 0))
        {
            for (PhoneDO phone : secUser.phone_numbers)
            {
                ctSo.phones.add(ProfilePhoneAPI.mapPhoneDOToContactPhone(phone));
            }
        }

        // Add Addresses
        if ((secUser.addresses != null) && (secUser.addresses.size() > 0))
        {
            for (AddressDO address : secUser.addresses)
            {
                ctSo.addresses.add(ProfileAddressAPI.mapAddressDOToContactAddress(address));
            }
        }

        return ctSo;
    }

    private static Contact mapSecondaryUserToContact(Contact ct, SecondaryUserDO secUser)
    {
        ct.Full_Name__c = secUser.full_name;
        ct.FirstName = secUser.first_name;
        ct.LastName = secUser.last_name;
        ct.Party_Id__c = secUser.party_id;
        ct.Profile_Picture__c = secUser.logo_url;
        ct.Age__c = secUser.age;

        if (secUser.compliance != null)
        {
            ct.CIP_Status__c = secUser.compliance.cip_status;
        }

        return ct;
    }

    private static SecondaryUserAttrobutesSO mapSecondaryUserAttributesToSO(SecondaryUserAttrobutesSO attr, SecondaryUserDO secUser)
    {
        attr.loginId = secUser.login_id;
        attr.canContactCS = secUser.has_permission_to_speak;
        return attr;
    }

    public static List<Contact> queryContactAndItsRelationships(Id accountId, List<String> partyIds)
    {
        return [SELECT Id, AccountId, Party_Id__c, Full_Name__c, FirstName, LastName, Profile_Picture__c, Age__c, CIP_Status__c,
                        (SELECT Id, Email_Address__c, Is_Primary__c, Status__c, Confirmation_Status__c, Trust_Status__c, Is_Active__c, 
                        Is_Confirmed__c, Is_Trusted__c 
                        FROM Contact_Emails__r),
                        (SELECT Id, Country_Code__c, Phone_Number__c, Type__c, Status__c, Confirmation_Status__c, Trust_Status__c, Is_Primary__c,
                        Is_Active__c, Is_Confirmed__c, Is_Trusted__c
                        FROM Contact_Phones__r),
                        (SELECT Id, Address_Line_1__c, Address_Line_2__c, Address_Line_3__c, Admin_Area_4__c, Admin_Area_3__c,
                        Admin_Area_2__c, Admin_Area_1__c, Country__c, Postal_Code__c, Type__c, Status__c, Confirmation_Status__c, Is_Primary__c,
                        Is_Active__c, Is_Confirmed__c
                        FROM Contact_Addresses__r),
                        (SELECT Id, AccountId, ContactId, Relationship__c, Can_Contact_CS__c 
                        FROM AccountContactRelations WHERE AccountId = :accountId),
                Email_Loaded_Time__c, Phone_Loaded_Time__c, Address_Loaded_Time__c 
                FROM Contact WHERE Party_Id__c IN :partyIds
               ];
    }

    private static List<AccountContactRelation> querySecondaryUsersForAccount(Id accountId)
    {
        return [SELECT Id, AccountId, ContactId, Relationship__c
                FROM AccountContactRelation 
                WHERE AccountId=:accountId AND Relationship__c = 'SECONDARY_USER' AND Can_Contact_CS__c = true];
    }

    private static List<AccountContactRelation> queryRelationshipBetweenAccountAndContacts(Id accountId, List<Id> contactIds)
    {
        return [SELECT Id, AccountId, ContactId, Relationship__c
                FROM AccountContactRelation 
                WHERE AccountId=:accountId AND ContactId IN :contactIds];
    }
}