force-app/main/default/objects/Account/fields/Limitation_Info_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Limitation_Info_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Limitation Info Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Limitation__c/Account_Limitation__c.object-meta.xml
<CustomObject>
    <description>Limitations / Restrictions placed on an account</description>
    <label>Account Limitation</label>
    <nameField>
        <label>Limitation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Limitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Limitation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Limitations for an account</description>
    <inlineHelpText>Limitations for an account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Limitations</relationshipLabel>
    <relationshipName>Account_Limitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Limitation__c/fields/Cases_JSON__c.field-meta.xml
<CustomField>
    <fullName>Cases_JSON__c</fullName>
    <label>Cases JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Limitation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category of the limitations on the customer account.</description>
    <inlineHelpText>Category of the limitations on the customer account.</inlineHelpText>
    <label>Category</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Limitation__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this limitation still actively placed</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Limitation__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Level of the limitations on the customer account e.g. 1,2 etc.</description>
    <inlineHelpText>Level of the limitations on the customer account e.g. 1,2 etc.</inlineHelpText>
    <label>Level</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Limitation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the limitation</description>
    <inlineHelpText>Current status of the limitation</inlineHelpText>
    <label>Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Limitation__c/fields/Subtypes_JSON__c.field-meta.xml
<CustomField>
    <fullName>Subtypes_JSON__c</fullName>
    <label>Subtypes_JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Limitation__c/fields/Time_Created__c.field-meta.xml
<CustomField>
    <fullName>Time_Created__c</fullName>
    <label>Time Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Limitation_Access_Change__c/Limitation_Access_Change__c.object-meta.xml
<CustomObject>
    <description>When a limitation is placed on an account, a set of access changes will be associated with it - like blocking payments, modifying profile, withdrawing amount, etc., This object is used to store the list of access changes associated with a limitation.</description>
    <label>Limitation Access Change</label>
    <nameField>
        <label>Access Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limitation Access Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Limitation_Access_Change__c/fields/Account_Limitation__c.field-meta.xml
<CustomField>
    <fullName>Account_Limitation__c</fullName>
    <description>Access change associated with the limitation</description>
    <inlineHelpText>Access change associated with the limitation</inlineHelpText>
    <label>Account Limitation</label>
    <referenceTo>Account_Limitation__c</referenceTo>
    <relationshipLabel>Limitation Access Changes</relationshipLabel>
    <relationshipName>Limitation_Access_Changes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Limitation_Access_Change__c/fields/Time_Created__c.field-meta.xml
<CustomField>
    <fullName>Time_Created__c</fullName>
    <description>Time when the access change is created</description>
    <inlineHelpText>Time when the access change is created</inlineHelpText>
    <label>Time Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LimitationAPI.cls
public class LimitationAPI {

    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('LimitationAPI:mapResponseToCustomer360SO - mapping Limitations Information');
        
        // Check if there are any failures in loading Limitations Info
        if (response.isLimitationsFailed() || (response.getCustomer360DO().limitations == null) ||
            (response.getCustomer360DO().limitations.size() == 0))
        {
            System.debug('Customer360 API response does not have Limitations information');
            return cx360SO;
        }
        
        // Map Limitations Information to the cx360SO object passed in the request
        for (LimitationDO limitation : response.getCustomer360DO().limitations)
        {
            cx360SO.limitations.add(mapLimitationDOToSO(limitation));
        }

        return cx360SO;
    }

    public static Account storeResponseInSObject(Account acct, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('LimitationAPI:storeResponseInSObject - Storing Limitations Information into SObject');
        
        // Check if there are any failures in loading Limitations Info
        if (response.isLimitationsFailed())
        {
            System.debug('Customer360 API did not successfully load Limitations information');
            return acct;
        }

        // Remove all existing limitations associated with the account
        removeLimitationsFromAccount(acct);

        List<LimitationDO> limitations = response.getCustomer360DO().limitations;
        
        if ((limitations != null) && (limitations.size() > 0))
        {
            List<Account_Limitation__c> limObjs = new List<Account_Limitation__c>();

            for (LimitationDO limitation : limitations)
            {
                Account_Limitation__c limObj = mapLimitationDOToSO(limitation);
                limObj.Account__c = acct.Id;
                limObjs.add(limObj);
            }

            insert limObjs;
        }

        // If limitations is successfully loaded (NOT a failure or partial success), update the cache time
        if (response.isLimitationsSuccessfullyLoaded())
        {
            acct.Limitation_Info_Loaded_Time__c = Datetime.now();
        }

        return acct;
    }

    private static void removeLimitationsFromAccount(Account acct)
    {
        List<Account_Limitation__c> limitations = queryLimitationsFromAccount(acct.Id);
        System.debug('Removing existing limitations from the account. Number of records found - ' + limitations.size());
        if (limitations.size() > 0)
        {
            delete limitations;
        }
        return;
    }

    private static Account_Limitation__c mapLimitationDOToSO(LimitationDO limitation)
    {
        Account_Limitation__c lim = new Account_Limitation__c();
        lim.Name = limitation.name;
        lim.Category__c = limitation.category;
        lim.Level__c = limitation.level;
        lim.Time_Created__c = limitation.limited_time;
        lim.Status__c = limitation.status;
        lim.Cases_JSON__c = JSON.serialize(limitation.cases);
        lim.Subtypes_JSON__c = JSON.serialize(limitation.subtypes);
        lim.Is_Active__c = isLimitationActive(limitation.status);
        
        return lim;
    }

    // Is this Limitation still open on the account?
    private static Boolean isLimitationActive(String status)
    {        
        if (String.isBlank(status))
        {
            return false;
        }

        if (status.equalsIgnoreCase('active') || (status.equalsIgnoreCase('appeal_denied')))
        {
            return true;
        }
        
        return false;
    }

    private static Limitation_Access_Change__c mapLimitationAccessChangeDOToSO(LimitationAccessChangeDO accessChange)
    {
        Limitation_Access_Change__c aCh = new Limitation_Access_Change__c();
        aCh.Name = accessChange.name;
        aCh.Time_Created__c = accessChange.create_time;
        
        return aCh;
    }

    private static List<Account_Limitation__c> queryLimitationsFromAccount(Id accountId)
    {
        return [SELECT Id, Account__c FROM Account_Limitation__c
                WHERE Account__c=:accountId];
    }
}