force-app/main/default/objects/Account/fields/PayPal_Cases_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>PayPal_Cases_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>PayPal Cases Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PayPal_Case__c/PayPal_Case__c.object-meta.xml
<CustomObject>
    <description>Cases created in internal PayPal systems like Disputes, PET, SCM and so on.</description>
    <label>PayPal Case</label>
    <nameField>
        <label>PayPal Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PayPal Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PayPal_Case__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cases associated with an account</description>
    <inlineHelpText>Cases associated with an account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PayPal Cases</relationshipLabel>
    <relationshipName>PayPal_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PayPal_Case__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <description>Case Id</description>
    <inlineHelpText>Case Id</inlineHelpText>
    <label>Case Id</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PayPal_Case__c/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <description>Case Status</description>
    <inlineHelpText>Case Status</inlineHelpText>
    <label>Case Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PayPal_Case__c/fields/Case_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Case_Subtype__c</fullName>
    <description>Case Subtype</description>
    <inlineHelpText>Case Subtype</inlineHelpText>
    <label>Case Subtype</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PayPal_Case__c/fields/Case_System__c.field-meta.xml
<CustomField>
    <fullName>Case_System__c</fullName>
    <description>Case system - Attack/Gold/PET/SCM/etc.,</description>
    <inlineHelpText>Case system - Attack/Gold/PET/SCM/etc.,</inlineHelpText>
    <label>Case System</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PayPal_Case__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <description>Case Type</description>
    <inlineHelpText>Case Type</inlineHelpText>
    <label>Case Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PayPal_Case__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <description>Case Party w.r.t. the current account</description>
    <inlineHelpText>Case Party w.r.t. the current account</inlineHelpText>
    <label>Party</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PayPal_Case__c/fields/Time_Created__c.field-meta.xml
<CustomField>
    <fullName>Time_Created__c</fullName>
    <description>PayPal case created time</description>
    <inlineHelpText>PayPal case created time</inlineHelpText>
    <label>Time Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PayPal_Case__c/fields/Transaction_Ids_JSON__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Ids_JSON__c</fullName>
    <description>A case can be associated with one or more transaction ids depending on the type. This field will store the array of transaction ids in the JSON format which can be deserialized into array back when needed.</description>
    <inlineHelpText>A case can be associated with one or more transaction ids depending on the type. This field will store the array of transaction ids in the JSON format which can be deserialized into array back when needed.</inlineHelpText>
    <label>Transaction Ids JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PayPalCaseAPI.cls
public class PayPalCaseAPI {
    
    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('PayPalCaseAPI:mapResponseToCustomer360SO - mapping Case Information');
        
        // Check if there are any failures in loading PayPal Case logs
        if (response.isCasesFailed() || (response.getCustomer360DO().cases == null) ||
            (response.getCustomer360DO().cases.size() == 0))
        {
            System.debug('No PayPal case logs available in Customer360 API response');
            return cx360SO;
        }
        
        // Map Case logs to the cx360SO object passed in the request
        for (PayPalCaseDO cs : response.getCustomer360DO().cases)
        {
            cx360SO.cases.add(mapPayPalCaseDOToSO(cs));
        }

        return cx360SO;
    }

    public static Account storeResponseInSObject(Account acct, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('PayPalCaseAPI:storeResponseInSObject - Storing Case Logs to SObject');
        
        // Check if there are any failures in loading PayPal Case logs
        if (response.isCasesFailed())
        {
            System.debug('Customer360 API did not successfully load PayPal case logs');
            return acct;
        }

        // Remove all PayPal cases from the account
        removePayPalCasesFromAccount(acct);

        List<PayPalCaseDO> cases = response.getCustomer360DO().cases;
        
        if ((cases != null) && (cases.size() > 0))
        {
            List<Paypal_Case__c> caseObjs = new List<Paypal_Case__c>();

            for (PayPalCaseDO cs : cases)
            {
                Paypal_Case__c caseObj = mapPayPalCaseDOToSO(cs);
                caseObj.Account__c = acct.Id;
                caseObjs.add(caseObj);
            }

            insert caseObjs;
        }

        // If Case logs are successfully loaded (NOT a failure or partial success), update the cache time
        if (response.isCasesSuccessfullyLoaded())
        {
            acct.PayPal_Cases_Loaded_Time__c = Datetime.now();
        }

        return acct;
    }

    private static void removePayPalCasesFromAccount(Account acct)
    {
        List<Paypal_Case__c> cases = queryPayPalCasesFromAccount(acct.Id);
        System.debug('Removing existing PayPal cases from the account. Number of records found - ' + cases.size());
        if (cases.size() > 0)
        {
            delete cases;
        }
        return;
    }

    private static Paypal_Case__c mapPayPalCaseDOToSO(PayPalCaseDO cs)
    {
        Paypal_Case__c ppCase = new Paypal_Case__c();
        ppCase.Case_Type__c = cs.case_type;
        ppCase.Case_Subtype__c = cs.subtype;
        ppCase.Time_Created__c = cs.create_time;
        ppCase.Transaction_Ids_JSON__c = JSON.serialize(cs.transaction_ids);
        ppCase.Case_Id__c = cs.case_id;
        ppCase.Party__c = cs.party;
        ppCase.Case_Status__c = cs.status;
        ppCase.Case_System__c = cs.case_system;
        
        return ppCase;
    }

    private static List<Paypal_Case__c> queryPayPalCasesFromAccount(Id accountId)
    {
        return [SELECT Id, Account__c FROM Paypal_Case__c
                WHERE Account__c=:accountId];
    }
}