force-app/main/default/objects/Account/fields/Previous_Interactions_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Previous_Interactions_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Previous Interactions Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interaction_Intent__c/Interaction_Intent__c.object-meta.xml
<CustomObject>
    <description>One or more Intents handled as part of the interaction</description>
    <label>Interaction Intent</label>
    <nameField>
        <label>Intent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interaction Intents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interaction_Intent__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <description>Actor name who handled the intent. This is required since an interaction can be handled by multiple teammates in case of transfer or asynchronous chats.</description>
    <inlineHelpText>Actor name</inlineHelpText>
    <label>Actor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction_Intent__c/fields/Previous_Interaction__c.field-meta.xml
<CustomField>
    <fullName>Previous_Interaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Intents associated with a previous interaction</description>
    <inlineHelpText>Intents associated with a previous interaction</inlineHelpText>
    <label>Previous Interaction</label>
    <referenceTo>Previous_Interaction__c</referenceTo>
    <relationshipLabel>Interaction Intents</relationshipLabel>
    <relationshipName>Interaction_Intents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interaction_Intent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the intent</description>
    <inlineHelpText>Status of the intent</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interaction_Intent__c/fields/Time_Started__c.field-meta.xml
<CustomField>
    <fullName>Time_Started__c</fullName>
    <description>Time the intent is handled</description>
    <inlineHelpText>Time the intent is handled</inlineHelpText>
    <label>Time Started</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/Previous_Interaction__c.object-meta.xml
<CustomObject>
    <description>Previous Interactions between this account and customer service</description>
    <label>Previous Interaction</label>
    <nameField>
        <label>Previous Interactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Previous Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Previous_Interaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Previous interactions associated with the account</description>
    <inlineHelpText>Previous interactions associated with the account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Previous Interactions</relationshipLabel>
    <relationshipName>Previous_Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <description>Actor / Teammate handled the interaction</description>
    <inlineHelpText>Actor / Teammate handled the interaction</inlineHelpText>
    <label>Actor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <description>Case Id for the previous interaction</description>
    <inlineHelpText>Case Id for the previous interaction</inlineHelpText>
    <label>Case Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Channel_Id__c.field-meta.xml
<CustomField>
    <fullName>Channel_Id__c</fullName>
    <description>Unique identifier associated with the Channel - like UCID for Phone, MMT chat interaction id for chat and so on.</description>
    <inlineHelpText>Unique identifier associated with the Channel</inlineHelpText>
    <label>Channel Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Channel_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Name__c</fullName>
    <description>Channel Name - It could be Phone / Chat / Email / Followup / etc.,</description>
    <inlineHelpText>Channel Name - It could be Phone / Chat / Email / Followup / etc.,</inlineHelpText>
    <label>Channel Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Contact_Reason__c.field-meta.xml
<CustomField>
    <fullName>Contact_Reason__c</fullName>
    <description>Contact Reason recorded in the system</description>
    <inlineHelpText>Contact Reason recorded in the system</inlineHelpText>
    <label>Contact Reason</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Followup_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Date__c</fullName>
    <description>Date to follow-up in case this case identifies a follow-up</description>
    <inlineHelpText>Date to follow-up in case this case identifies a follow-up</inlineHelpText>
    <label>Followup Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Followup_Reason__c.field-meta.xml
<CustomField>
    <fullName>Followup_Reason__c</fullName>
    <description>Reason for following up</description>
    <inlineHelpText>Reason for following up</inlineHelpText>
    <label>Followup Reason</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Has_Followup__c.field-meta.xml
<CustomField>
    <fullName>Has_Followup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this interaction has a follow-up scheduled?</description>
    <inlineHelpText>Is this interaction has a follow-up scheduled?</inlineHelpText>
    <label>Has Followup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Parent_Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case_Id__c</fullName>
    <description>Case id of the parent in case these two cases are linked. This is applicable in scenarios like followups.</description>
    <inlineHelpText>Case id of the parent in case these two cases are linked</inlineHelpText>
    <label>Parent Case Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status - New / In Progress / Closed / Paused / etc.,</description>
    <inlineHelpText>Status - New / In Progress / Closed / Paused / etc.,</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Time_Completed__c.field-meta.xml
<CustomField>
    <fullName>Time_Completed__c</fullName>
    <description>Time the Interaction is completed</description>
    <inlineHelpText>Time the Interaction is completed</inlineHelpText>
    <label>Time Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Previous_Interaction__c/fields/Time_Started__c.field-meta.xml
<CustomField>
    <fullName>Time_Started__c</fullName>
    <description>Time the Interaction started</description>
    <inlineHelpText>Time the Interaction started</inlineHelpText>
    <label>Time Started</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/InteractionsAPI.cls
public class InteractionsAPI {
    
    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('InteractionsAPI:mapResponseToCustomer360SO - mapping Previous Interactions');
        
        // Check if there are any failures in loading previous interactions
        if (response.isPreviousInteractionsFailed() || (response.getCustomer360DO().previous_interactions == null) ||
            (response.getCustomer360DO().previous_interactions.size() == 0))
        {
            System.debug('Customer360 API did not load any previous interactions information');
            return cx360SO;
        }
        
        // Map Previous Interactions Information to the cx360SO object passed in the request
        for (PreviousInteractionDO interaction : response.getCustomer360DO().previous_interactions)
        {
            PreviousInteractionSO interactionSO = new PreviousInteractionSO();
            interactionSO.interaction = mapPreviousInteractionDOToSO(interaction);

            // Check if any intents are available within the interaction and map
            if ((interaction.intents != null) && (interaction.intents.size() != 0))
            {
                for (InteractionIntentDO intent : interaction.intents)
                {
                    interactionSO.intents.add(mapInteractionIntentDOToSO(intent));
                }
            }

            cx360SO.previousInteractions.add(interactionSO);
        }

        return cx360SO;
    }

    public static Account storeResponseInSObject(Account acct, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('InteractionsAPI:storeResponseInSObject - Storing Previous Interactions into SObject');
        
        // Check if there are any failures in loading previous interactions
        if (response.isPreviousInteractionsFailed())
        {
            System.debug('Customer360 API did not load any previous interactions information');
            return acct;
        }

        // Remove all previous interactions from the account
        removePreviousInteractionsFromAccount(acct);

        List<PreviousInteractionDO> interactionDOs = response.getCustomer360DO().previous_interactions;

        if ((interactionDOs != null) && (interactionDOs.size() > 0))
        {
            List<PreviousInteractionSO> interactionSOs = new List<PreviousInteractionSO>();
            List<Previous_Interaction__c> interactionObjsToInsert = new List<Previous_Interaction__c>();
        
            for (PreviousInteractionDO interactionDO : interactionDOs)
            {
                PreviousInteractionSO interactionSO = new PreviousInteractionSO();
                interactionSO.interaction = mapPreviousInteractionDOToSO(interactionDO);
                interactionSO.interaction.Account__c = acct.Id;

                // Check if any intents are available within the interaction and map
                if ((interactionDO.intents != null) && (interactionDO.intents.size() != 0))
                {
                    for (InteractionIntentDO intentDO : interactionDO.intents)
                    {
                        interactionSO.intents.add(mapInteractionIntentDOToSO(intentDO));
                    }
                }

                interactionObjsToInsert.add(interactionSO.interaction);
                interactionSOs.add(interactionSO);
            }

            // Insert all Previous Interactions to the database
            System.debug('Inserting Previous Interaction to the account. Number of records - ' + interactionObjsToInsert.size());
            insert interactionObjsToInsert;

            List<Interaction_Intent__c> intentObjsToInsert = new List<Interaction_Intent__c>();
            for (PreviousInteractionSO intSO : interactionSOs)
            {
                for (Interaction_Intent__c intent : intSO.intents)
                {
                    intent.Previous_Interaction__c = intSO.interaction.Id;
                    intentObjsToInsert.add(intent);
                }
            }

            System.debug('Inserting Interaction Intents to the account. Number of records - ' + intentObjsToInsert.size());
            if (intentObjsToInsert.size() > 0)
            {
                insert intentObjsToInsert;
            }
        }

        // If Previous Interactions is loaded successfully (NOT a failure or partial success), update the cache time
        if (response.isPreviousInteractionsSuccessfullyLoaded())
        {
            acct.Previous_Interactions_Loaded_Time__c = Datetime.now();
        }

        return acct;
    }

    private static Previous_Interaction__c mapPreviousInteractionDOToSO(PreviousInteractionDO interaction)
    {
        Previous_Interaction__c inter = new Previous_Interaction__c();
        inter.Case_Id__c = interaction.case_id;
        inter.Channel_Id__c = interaction.channel_id;
        inter.Channel_Name__c = interaction.channel_name;
        inter.Time_Started__c = interaction.create_time;
        inter.Time_Completed__c = interaction.end_time;
        inter.Parent_Case_Id__c = interaction.parent_case_id;
        inter.Status__c = interaction.status;
        inter.Actor__c = interaction.actor;
        inter.Contact_Reason__c = interaction.contact_reason;
        inter.Has_Followup__c = interaction.followup;
        inter.Followup_Date__c = interaction.followup_date;
        inter.Followup_Reason__c = interaction.followup_reason;

        return inter;
    }

    private static Interaction_Intent__c mapInteractionIntentDOToSO(InteractionIntentDO intent)
    {
        Interaction_Intent__c intentObj = new Interaction_Intent__c();
        intentObj.Name = intent.intent_name;
        intentObj.Time_Started__c = intent.create_time;
        intentObj.Status__c = intent.status;
        intentObj.Actor__c = intent.actor;
        
        return intentObj;
    }

    private static void removePreviousInteractionsFromAccount(Account acct)
    {
        List<Previous_Interaction__c> prevInteractions = queryPreviousInteractionsFromAccount(acct.Id);
        System.debug('Removing previous interactions from the account. Number of records found - ' + prevInteractions.size());
        if (prevInteractions.size() > 0)
        {
            delete prevInteractions;

            // Deleting the previous interactions will automatically delete all interaction intents associated with it
            // because of the Master - Detail relationship
        }
        return;
    }

    private static List<Previous_Interaction__c> queryPreviousInteractionsFromAccount(Id accountId)
    {
        return [SELECT Id, Account__c FROM Previous_Interaction__c
                WHERE Account__c=:accountId];
    }
}