force-app/main/default/objects/Account/fields/TransactionLog_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>TransactionLog_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>TransactionLog Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <description>Transaction Logs associated with an account</description>
    <label>Transaction Log</label>
    <nameField>
        <label>Transaction Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Transaction Logs for an account</description>
    <inlineHelpText>Transaction Logs for an account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transaction Logs</relationshipLabel>
    <relationshipName>Transaction_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Counterparty_Email__c.field-meta.xml
<CustomField>
    <fullName>Counterparty_Email__c</fullName>
    <description>Counterparty Email</description>
    <inlineHelpText>Counterparty Email</inlineHelpText>
    <label>Counterparty Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Counterparty_Name__c.field-meta.xml
<CustomField>
    <fullName>Counterparty_Name__c</fullName>
    <description>Counterparty Name</description>
    <inlineHelpText>Counterparty Name</inlineHelpText>
    <label>Counterparty Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <description>Fee Amount</description>
    <inlineHelpText>Fee Amount</inlineHelpText>
    <label>Fee Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Fee_Amount_Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount_Currency_Code__c</fullName>
    <description>Fee Amount Currency Code</description>
    <inlineHelpText>Fee Amount Currency Code</inlineHelpText>
    <label>Fee Amount Currency Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Amount__c</fullName>
    <description>Gross Amount of the Transaction</description>
    <inlineHelpText>Gross Amount of the Transaction</inlineHelpText>
    <label>Gross Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Gross_Amount_Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Gross_Amount_Currency_Code__c</fullName>
    <description>Gross Amount Currency Code</description>
    <inlineHelpText>Gross Amount Currency Code</inlineHelpText>
    <label>Gross Amount Currency Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Has_Dispute__c.field-meta.xml
<CustomField>
    <fullName>Has_Dispute__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this transaction ever disputed?</description>
    <inlineHelpText>Is this transaction ever disputed?</inlineHelpText>
    <label>Has Dispute</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Is_Parent__c.field-meta.xml
<CustomField>
    <fullName>Is_Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this a parent transaction as per the transaction model?</description>
    <inlineHelpText>Is this a parent transaction as per the transaction model?</inlineHelpText>
    <label>Is Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Last_4_digits__c.field-meta.xml
<CustomField>
    <fullName>Last_4_digits__c</fullName>
    <description>Last 4 digits of the financial instrument that funded this transaction</description>
    <inlineHelpText>Last 4 digits of the financial instrument that funded this transaction</inlineHelpText>
    <label>Last 4 digits</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount__c</fullName>
    <description>Net Amount</description>
    <inlineHelpText>Net Amount</inlineHelpText>
    <label>Net Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Net_Amount_Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount_Currency_Code__c</fullName>
    <description>Net Amount Currency Code</description>
    <inlineHelpText>Net Amount Currency Code</inlineHelpText>
    <label>Net Amount Currency Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Running_Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Running_Balance_Amount__c</fullName>
    <description>Running Balance Amount</description>
    <inlineHelpText>Running Balance Amount</inlineHelpText>
    <label>Running Balance Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Running_Balance_Amount_Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Running_Balance_Amount_Currency_Code__c</fullName>
    <description>Running Balance Amount Currency Code</description>
    <inlineHelpText>Running Balance Amount Currency Code</inlineHelpText>
    <label>Running Balance Amount Currency Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/ToFrom__c.field-meta.xml
<CustomField>
    <fullName>ToFrom__c</fullName>
    <description>Payment To / From Information</description>
    <inlineHelpText>Payment To / From Information</inlineHelpText>
    <label>ToFrom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>Transaction Id</description>
    <inlineHelpText>Transaction Id</inlineHelpText>
    <label>Transaction Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Transaction_Id_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id_Encrypted__c</fullName>
    <description>Encrypted Transaction Id</description>
    <inlineHelpText>Encrypted Transaction Id</inlineHelpText>
    <label>Transaction Id Encrypted</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <description>Current Status of the Transaction</description>
    <inlineHelpText>Current Status of the Transaction</inlineHelpText>
    <label>Transaction Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Transaction_Time__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Time__c</fullName>
    <description>Transaction Time</description>
    <inlineHelpText>Transaction Time</inlineHelpText>
    <label>Transaction Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>Detailed Transaction Type</description>
    <inlineHelpText>Detailed Transaction Type</inlineHelpText>
    <label>Transaction Type</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TransactionAPI.cls
public class TransactionAPI {
    
    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('TransactionAPI:mapResponseToCustomer360SO - mapping Transaction Information');
        
        // Check if there are any failures in loading Transaction logs
        if (response.isTransactionsFailed() || (response.getCustomer360DO().transactions == null) ||
            (response.getCustomer360DO().transactions.size() == 0))
        {
            System.debug('Customer360 API response does not have any Transactions');
            return cx360SO;
        }
        
        // Map Transaction logs to the cx360SO object passed in the request
        for (TransactionDO txn : response.getCustomer360DO().transactions)
        {
            cx360SO.transactions.add(mapTransactionDOToSO(txn));
        }

        return cx360SO;
    }

    public static Account storeResponseInSObject(Account acct, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('TransactionAPI:storeResponseInSObject - Storing Transactions into SObject');
        
        // Check if there are any failures in loading Transaction Logs
        if (response.isTransactionsFailed())
        {
            System.debug('Customer360 API did not successfully load Transaction Logs');
            return acct;
        }

        // Remove all existing transactions from the account
        removeTransactionsFromAccount(acct);

        List<TransactionDO> txns = response.getCustomer360DO().transactions;
        
        if ((txns != null) && (txns.size() > 0))
        {
            List<Transaction_Log__c> txnObjs = new List<Transaction_Log__c>();

            for (TransactionDO txn : txns)
            {
                Transaction_Log__c txnObj = mapTransactionDOToSO(txn);
                txnObj.Account__c = acct.Id;
                txnObjs.add(txnObj);
            }

            insert txnObjs;
        }

        // If Transaction logs are successfully loaded (NOT a failure or partial success), update the cache time
        if (response.isTransactionsSuccessfullyLoaded())
        {
            acct.TransactionLog_Loaded_Time__c = Datetime.now();
        }

        return acct;
    }

    private static void removeTransactionsFromAccount(Account acct)
    {
        List<Transaction_Log__c> transactions = queryTransactionsFromAccount(acct.Id);
        System.debug('Removing existing transactions from the account. Number of records found - ' + transactions.size());
        if (transactions.size() > 0)
        {
            delete transactions;
        }
        return;
    }

    private static Transaction_Log__c mapTransactionDOToSO(TransactionDO txn)
    {
        Transaction_Log__c trans = new Transaction_Log__c();
        trans.Transaction_Type__c = txn.transaction_type;
        trans.Transaction_Time__c = txn.create_time;
        trans.Transaction_Id__c = txn.transaction_id;
        trans.Transaction_Id_Encrypted__c = txn.encrypted_transaction_id;
        trans.Transaction_Status__c = txn.status;
        trans.Last_4_digits__c = txn.last_digits;
        trans.ToFrom__c = txn.to_and_from;
        trans.Counterparty_Name__c = txn.counterparty_name;
        trans.Counterparty_Email__c = txn.counterparty_email;
        trans.Is_Parent__c = txn.parent;
        trans.Has_Dispute__c = txn.disputed;
        
        // Gross Amount
        if (txn.gross_amount != null)
        {
            try {
                trans.Gross_Amount__c = Decimal.valueOf(txn.gross_amount.value);
                trans.Gross_Amount_Currency_Code__c = txn.gross_amount.currency_code;
            }
            catch(Exception e) {
                System.debug('Gross Amount: ' + e.getMessage() + ', Failed to convert from String to Decimal - ' 
                                            + JSON.serialize(txn.gross_amount));
            }
        }

        // Net Amount
        if (txn.net_amount != null)
        {
            try {
                trans.Net_Amount__c = Decimal.valueOf(txn.net_amount.value);
                trans.Net_Amount_Currency_Code__c = txn.net_amount.currency_code;
            }
            catch(Exception e) {
                System.debug('Net Amount: ' + e.getMessage() + ', Failed to convert from String to Decimal - ' 
                                            + JSON.serialize(txn.net_amount));
            }
        }

        // Fee Amount
        if (txn.fee_amount != null)
        {
            try {
                trans.Fee_Amount__c = Decimal.valueOf(txn.fee_amount.value);
                trans.Fee_Amount_Currency_Code__c = txn.fee_amount.currency_code;
            }
            catch(Exception e) {
                System.debug('Fee Amount: ' + e.getMessage() + ', Failed to convert from String to Decimal - ' 
                                            + JSON.serialize(txn.fee_amount));
            }
        }

        // Running Balance Amount
        if (txn.running_balance_amount != null)
        {
            try {
                trans.Running_Balance_Amount__c = Decimal.valueOf(txn.running_balance_amount.value);
                trans.Running_Balance_Amount_Currency_Code__c = txn.running_balance_amount.currency_code;
            }
            catch(Exception e) {
                System.debug('Running Balance Amount: ' + e.getMessage() + ', Failed to convert from String to Decimal - ' 
                                                        + JSON.serialize(txn.running_balance_amount));
            }
        }
        
        return trans;
    }

    private static List<Transaction_Log__c> queryTransactionsFromAccount(Id accountId)
    {
        return [SELECT Id, Account__c FROM Transaction_Log__c
                WHERE Account__c=:accountId];
    }
}