force-app/main/default/objects/Account/fields/Wallet_Info_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Info_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Wallet Info Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/Account_Wallet__c.object-meta.xml
<CustomObject>
    <description>Wallet object stores all the financial instruments associated with the account like banks, cards, paypal credit and so on.</description>
    <label>Account Wallet</label>
    <nameField>
        <label>Account Wallet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Wallet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Wallet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Financial Instruments associated with an Account</description>
    <inlineHelpText>Financial Instruments associated with an Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Wallet</relationshipLabel>
    <relationshipName>Account_Wallet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation status of the financial instrument</description>
    <inlineHelpText>Confirmation status of the financial instrument</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Credit_Limit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Amount__c</fullName>
    <description>Total credit limit for PayPal Credit product</description>
    <inlineHelpText>Total credit limit for PayPal Credit product</inlineHelpText>
    <label>Credit Limit Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Credit_Limit_Currency__c.field-meta.xml
<CustomField>
    <fullName>Credit_Limit_Currency__c</fullName>
    <description>Credit Limit Currency Code</description>
    <inlineHelpText>Credit Limit Currency Code</inlineHelpText>
    <label>Credit Limit Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Credit_Usage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Usage_Amount__c</fullName>
    <description>Amount of PayPal credit used by the customer</description>
    <inlineHelpText>Amount of PayPal credit used by the customer</inlineHelpText>
    <label>Credit Usage Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Credit_Usage_Currency__c.field-meta.xml
<CustomField>
    <fullName>Credit_Usage_Currency__c</fullName>
    <description>Currency code for the PayPal credit usage</description>
    <inlineHelpText>Currency code for the PayPal credit usage</inlineHelpText>
    <label>Credit Usage Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Customer Name on File. This could be same or different than the one used in the profile/account.</description>
    <inlineHelpText>Customer Name on File.</inlineHelpText>
    <label>Customer Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>Expiry Date for the card or any other applicable financial instrument</description>
    <inlineHelpText>Expiry Date for the card or any other applicable financial instrument</inlineHelpText>
    <label>Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Financial_Instrument_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Financial_Instrument_Subtype__c</fullName>
    <description>Financial Instrument Subtype - For card it could be Credit/Debit, For bank it could be checking/saving and so on.</description>
    <inlineHelpText>Financial Instrument Subtype - For card it could be Credit/Debit, For bank it could be checking/saving and so on.</inlineHelpText>
    <label>Financial Instrument Subtype</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Financial_Instrument_Type__c.field-meta.xml
<CustomField>
    <fullName>Financial_Instrument_Type__c</fullName>
    <description>Financial Instrument Type - like Card/Bank/etc.,</description>
    <inlineHelpText>Financial Instrument Type - like Card/Bank/etc.,</inlineHelpText>
    <label>Financial Instrument Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Issuer_Name__c.field-meta.xml
<CustomField>
    <fullName>Issuer_Name__c</fullName>
    <description>Issuer Name for Card/Bank, etc.,</description>
    <inlineHelpText>Issuer Name for Card/Bank, etc.,</inlineHelpText>
    <label>Issuer Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Last_4_digits__c.field-meta.xml
<CustomField>
    <fullName>Last_4_digits__c</fullName>
    <description>Last 4 digits of the card/bank account number/etc.,</description>
    <inlineHelpText>Last 4 digits of the card/bank account number/etc.,</inlineHelpText>
    <label>Last 4 digits</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <description>Card Art, Bank Logo, etc.,</description>
    <inlineHelpText>Card Art, Bank Logo, etc.,</inlineHelpText>
    <label>Logo URL</label>
    <length>1028</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the financial instrument</description>
    <inlineHelpText>Current status of the financial instrument</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Wallet__c/fields/Wallet_Id__c.field-meta.xml
<CustomField>
    <fullName>Wallet_Id__c</fullName>
    <description>Unique identifier for the corresponding financial instrument</description>
    <inlineHelpText>Unique identifier for the corresponding financial instrument</inlineHelpText>
    <label>Wallet Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WalletAPI.cls
public class WalletAPI {

    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('WalletAPI:mapResponseToCustomer360SO - mapping Wallet Information');
        
        // Check if there are any failures in loading Wallet details
        if (response.isWalletFailed() || (response.getCustomer360DO().financial_instruments == null) ||
            (response.getCustomer360DO().financial_instruments.size() == 0))
        {
            System.debug('Customer360 API response does not have Wallet details');
            return cx360SO;
        }
        
        // Map Wallet details to the cx360SO object passed in the request
        for (FinancialInstrumentDO fi : response.getCustomer360DO().financial_instruments)
        {
            cx360SO.financialInstruments.add(mapFinancialInstrumentDOToSO(fi));
        }

        return cx360SO;
    }

    public static Account storeResponseInSObject(Account acct, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('WalletAPI:storeResponseInSObject - Storing Wallet Information into SObject');
        
        // Check if there are any failures in loading Wallet details
        if (response.isWalletFailed())
        {
            System.debug('Customer360 API did not successfully load Wallet details');
            return acct;
        }

        // Remove all existing financial instruments from the account
        removeFinancialInstrumentsFromAccount(acct);

        List<FinancialInstrumentDO> fis = response.getCustomer360DO().financial_instruments;
        
        if ((fis != null) && (fis.size() > 0))
        {
            List<Account_Wallet__c> walletObjs = new List<Account_Wallet__c>();

            for (FinancialInstrumentDO fi : fis)
            {
                Account_Wallet__c walletObj = mapFinancialInstrumentDOToSO(fi);
                walletObj.Account__c = acct.Id;
                walletObjs.add(walletObj);
            }

            insert walletObjs;
        }

        // If Financial Instruments is successfully loaded (NOT a failure or partial success), update the cache time
        if (response.isWalletSuccessfullyLoaded())
        {
            acct.Wallet_Info_Loaded_Time__c = Datetime.now();
        }

        return acct;
    }

    private static void removeFinancialInstrumentsFromAccount(Account acct)
    {
        List<Account_Wallet__c> fis = queryFinancialInstrumentsFromAccount(acct.Id);
        System.debug('Removing existing financial instruments from the account. Number of records found - ' + fis.size());
        if (fis.size() > 0)
        {
            delete fis;
        }
        return;
    }

    public static Account_Wallet__c mapFinancialInstrumentDOToSO(FinancialInstrumentDO fi)
    {
        Account_Wallet__c aw = new Account_Wallet__c();
        aw.Wallet_Id__c = fi.wallet_id;
        aw.Logo_URL__c = fi.logo_url;
        aw.Issuer_Name__c = fi.issuer_name;
        aw.Customer_Name__c = fi.name_on_file;
        aw.Financial_Instrument_Type__c = fi.financial_instrument_type;
        aw.Financial_Instrument_Subtype__c = fi.subtype;
        aw.Last_4_digits__c = fi.last_digits;
        aw.Expiry_Date__c = fi.expiry_date;
        aw.Status__c = fi.status;
        aw.Confirmation_Status__c = fi.confirmation_status;
        
        // PayPal Credit Limit
        if (fi.paypal_credit_limit != null)
        {
            try {
                aw.Credit_Limit_Amount__c = Decimal.valueOf(fi.paypal_credit_limit.value);
                aw.Credit_Limit_Currency__c = fi.paypal_credit_limit.currency_code;
            }
            catch(Exception e) {
                System.debug('PayPal Credit Limit: ' + e.getMessage() + ', Failed to convert from String to Decimal - ' 
                                                     + JSON.serialize(fi.paypal_credit_limit));
            }
        }

        // PayPal Credit Usage
        if (fi.paypal_credit_usage != null)
        {
            try {
                aw.Credit_Usage_Amount__c = Decimal.valueOf(fi.paypal_credit_usage.value);
                aw.Credit_Usage_Currency__c = fi.paypal_credit_usage.currency_code;
            }
            catch(Exception e) {
                System.debug('PayPal Credit Usage: ' + e.getMessage() + ', Failed to convert from String to Decimal - ' 
                                                     + JSON.serialize(fi.paypal_credit_usage));
            }
        }
        
        return aw;
    }

    private static List<Account_Wallet__c> queryFinancialInstrumentsFromAccount(Id accountId)
    {
        return [SELECT Id, Account__c FROM Account_Wallet__c
                WHERE Account__c=:accountId];
    }
}