force-app/main/default/objects/Batch_Config__mdt/Batch_Config__mdt.object-meta.xml
<CustomObject>
    <description>Typically batches needs certain configurations - like how much time window has to be processed, how old the records should be, fault tolerance and so on. This metadata can help with configuring such parameters for each batch.</description>
    <label>Batch Configuration</label>
    <pluralLabel>Batch Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Batch_Config__mdt/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <description>Number of records that needs to be passed into execute - for each transaction within a batch.</description>
    <inlineHelpText>Number of records that needs to be passed into execute - for each transaction within a batch.</inlineHelpText>
    <label>Scope</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PrefetchDataCleanupSchedule.cls
public class PrefetchDataCleanupSchedule implements Schedulable {
    public void execute(SchedulableContext sc) {
        System.debug('PrefetchDataCleanupSchedule:execute Begin called with CronTrigger Id - ' + sc.getTriggerId());

        // Lets get the scope or number of records per execute transaction from the configuration
        String batchName = 'CUSTOMER360_DATA_CLEANUP';
        Batch_Config__mdt config = [SELECT Scope__c FROM Batch_Config__mdt 
                                    WHERE MasterLabel=:batchName LIMIT 1];
        
        Integer scope = (Integer) config.Scope__c;
        System.debug('Identified batch size / scope value - ' + scope);

        // Lets go ahead and run the batch
        PrefetchDataCleanupBatch batch = new PrefetchDataCleanupBatch();
        String jobId = Database.executeBatch(batch, scope);

        // If executeBatch fails, it will return 000000000000000, otherwise we are expected to receive 707xxxxxxxxxxxx
        // Refer - https://trailblazer.salesforce.com/issues_view?id=a1p3A0000008geqQAA
        
        if(jobId.startsWith('707')) { 
            System.debug('Batch Job Queued successfully. Job Id - ' + jobId);
        } else {
            System.debug(LoggingLevel.ERROR, 'Failed to queue the Batch Job. Returned Job Id - ' + jobId);
        }

        System.debug('PrefetchDataCleanupSchedule:execute End');
    }
}