force-app/main/default/objects/Contact/fields/Address_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Address_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Address Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/Contact_Address__c.object-meta.xml
<CustomObject>
    <description>Addresses associated with the contact</description>
    <label>Contact Address</label>
    <nameField>
        <label>Contact Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Address__c/fields/Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Address_Id__c</fullName>
    <description>Unique identifier for this address in the system of record</description>
    <inlineHelpText>Unique identifier for this address in the system of record</inlineHelpText>
    <label>Address Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Address Line 1</description>
    <inlineHelpText>Address Line 1</inlineHelpText>
    <label>Address Line 1</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Address Line 2</description>
    <inlineHelpText>Address Line 2</inlineHelpText>
    <label>Address Line 2</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <description>Address Line 3</description>
    <inlineHelpText>Address Line 3</inlineHelpText>
    <label>Address Line 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Admin_Area_1__c.field-meta.xml
<CustomField>
    <fullName>Admin_Area_1__c</fullName>
    <description>Admin Area 1</description>
    <inlineHelpText>Admin Area 1</inlineHelpText>
    <label>Admin Area 1</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Admin_Area_2__c.field-meta.xml
<CustomField>
    <fullName>Admin_Area_2__c</fullName>
    <description>Admin Area 2</description>
    <inlineHelpText>Admin Area 2</inlineHelpText>
    <label>Admin Area 2</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Admin_Area_3__c.field-meta.xml
<CustomField>
    <fullName>Admin_Area_3__c</fullName>
    <description>Admin Area 3</description>
    <inlineHelpText>Admin Area 3</inlineHelpText>
    <label>Admin Area 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Admin_Area_4__c.field-meta.xml
<CustomField>
    <fullName>Admin_Area_4__c</fullName>
    <description>Admin Area 4</description>
    <inlineHelpText>Admin Area 4</inlineHelpText>
    <label>Admin Area 4</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation Status of the address in the profile</description>
    <inlineHelpText>Confirmation Status of the address in the profile</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact to which the address is associated</description>
    <inlineHelpText>Contact to which the address is associated</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Addresses</relationshipLabel>
    <relationshipName>Contact_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country</description>
    <inlineHelpText>Country</inlineHelpText>
    <label>Country</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this address primary?</description>
    <inlineHelpText>Is this address primary?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>Postal Code</description>
    <inlineHelpText>Postal Code</inlineHelpText>
    <label>Postal Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the address in the profile</description>
    <inlineHelpText>Status of the address in the profile</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Tags_JSON__c.field-meta.xml
<CustomField>
    <fullName>Tags_JSON__c</fullName>
    <description>Tags associated with the Address</description>
    <inlineHelpText>Tags associated with the Address</inlineHelpText>
    <label>Tags JSON</label>
    <length>512</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of address - Home / Work / etc.,</description>
    <inlineHelpText>Type of address - Home / Work / etc.,</inlineHelpText>
    <label>Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProfileAddressAPI.cls
public class ProfileAddressAPI {
    
    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('ProfileAddressAPI:mapResponseToCustomer360SO - Mapping Address Information');

        if (response.isProfileAddressesFailed() || (response.getCustomer360DO().profile == null) ||
           (response.getCustomer360DO().profile.addresses == null) || (response.getCustomer360DO().profile.addresses.size() == 0))
        {
            System.debug('Customer360 API response does not have any addresses');
            return cx360SO;
        }

        for (AddressDO address : response.getCustomer360DO().profile.addresses)
        {
            cx360SO.primaryUser.addresses.add(mapAddressDOToContactAddress(address));
        }

        return cx360SO;
    }

    public static ProfileAPI.InsertToSOHelper storeResponseInSObject(ProfileAPI.InsertToSOHelper soHelper, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('ProfileAddressAPI:storeResponseInSObject - Storing Address Information into SObject');

        if (response.isProfileAddressesFailed())
        {
            System.debug('Customer360 API did not successfully load any Addresses');
            return soHelper;
        }

        List<AddressDO> addresses = response.getCustomer360DO().profile.addresses;

        if (addresses != null)
        {
            for (AddressDO address : addresses)
            {
                Contact_Address__c addressObj = mapAddressDOToContactAddress(address);
                addressObj.Contact__c = soHelper.ct.Id;
                soHelper.recordsToInsert.add(addressObj);
            }
        }

        // If it is not the new contact that we created now, we may have some old addresses to be deleted
        if (!soHelper.newContact)
        {
            soHelper.recordsToDelete.addAll(soHelper.ct.Contact_Addresses__r);
        }

        // If addresses are successfully loaded (NOT a failure or partial success), lets update the last loaded time
        if (response.isProfileAddressesSuccessfullyLoaded())
        {
            soHelper.ct.Address_Loaded_Time__c = Datetime.now();
        }

        return soHelper;
    }

    public static Contact_Address__c mapAddressDOToContactAddress(AddressDO address)
    {
        Contact_Address__c ctAddress = new Contact_Address__c();
        ctAddress.Address_Id__c = address.address_id;
        ctAddress.Type__c = address.address_type;
        ctAddress.Tags_JSON__c = JSON.serialize(address.tags);
        ctAddress.Status__c = address.status;
        ctAddress.Confirmation_Status__c = address.confirmation_status;
        ctAddress.Is_Primary__c = address.primary;
        
        if (address.address != null)
        {
            ctAddress.Address_Line_1__c = address.address.address_line_1;
            ctAddress.Address_Line_2__c = address.address.address_line_2;
            ctAddress.Address_Line_3__c = address.address.address_line_3;
            ctAddress.Admin_Area_4__c = address.address.admin_area_4;
            ctAddress.Admin_Area_3__c = address.address.admin_area_3;
            ctAddress.Admin_Area_2__c = address.address.admin_area_2;
            ctAddress.Admin_Area_1__c = address.address.admin_area_1;
            ctAddress.Postal_Code__c = address.address.postal_code;
            ctAddress.Country__c = address.address.country_code;
        }

        ctAddress.Is_Active__c = false;
        ctAddress.Is_Confirmed__c = false;

        // TBD - Address Type, confirm if we have separate type to identify home, work, etc.,

        // Is Address Active?
        if (String.isNotBlank(address.status) && address.status.equalsIgnoreCase('active'))
        {
            ctAddress.Is_Active__c = true;
        }

        // Is Address Confirmed?
        if (String.isNotBlank(address.confirmation_status) && address.confirmation_status.equalsIgnoreCase('confirmed'))
        {
            ctAddress.Is_Confirmed__c = true;
        }

        return ctAddress;
    }

}