force-app/main/default/objects/Contact/fields/Email_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Email_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Email Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/Contact_Email__c.object-meta.xml
<CustomObject>
    <description>Email addresses associated with the contact / user.</description>
    <label>Contact Email</label>
    <nameField>
        <label>Contact Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Email__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation status of the email in the profile</description>
    <inlineHelpText>Confirmation status of the email in the profile</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Emails associated with the contact</description>
    <inlineHelpText>Emails associated with the contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Emails</relationshipLabel>
    <relationshipName>Contact_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Domain_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Domain_Identifier__c</fullName>
    <description>Unique identifier for this email in the system of record</description>
    <inlineHelpText>Unique identifier for this email in the system of record</inlineHelpText>
    <label>Domain Identifier</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>Email Address</description>
    <inlineHelpText>Email Address</inlineHelpText>
    <label>Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this email Primary?</description>
    <inlineHelpText>Is this email Primary?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the email within the profile</description>
    <inlineHelpText>Current status of the email within the profile</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Trust_Status__c.field-meta.xml
<CustomField>
    <fullName>Trust_Status__c</fullName>
    <description>Trust Status of the Email</description>
    <inlineHelpText>Trust Status of the Email</inlineHelpText>
    <label>Trust Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProfileEmailAPI.cls
public class ProfileEmailAPI {
    
    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('ProfileEmailAPI:mapResponseToCustomer360SO - Mapping Email Information');

        if (response.isProfileEmailsFailed() || (response.getCustomer360DO().profile == null) ||
           (response.getCustomer360DO().profile.emails == null) || (response.getCustomer360DO().profile.emails.size() == 0))
        {
            System.debug('Customer360 API response does not have any emails');
            return cx360SO;
        }

        for (EmailDO email : response.getCustomer360DO().profile.emails)
        {
            cx360SO.primaryUser.emails.add(mapEmailDOToContactEmail(email));
        }

        return cx360SO;
    }

    public static ProfileAPI.InsertToSOHelper storeResponseInSObject(ProfileAPI.InsertToSOHelper soHelper, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('ProfileEmailAPI:storeResponseInSObject - Storing Email Information into SObject');

        if (response.isProfileEmailsFailed())
        {
            System.debug('Customer360 API did not successfully load any emails');
            return soHelper;
        }

        List<EmailDO> emails = response.getCustomer360DO().profile.emails;

        if (emails != null)
        {
            for (EmailDO email : emails)
            {
                Contact_Email__c emailObj = mapEmailDOToContactEmail(email);
                emailObj.Contact__c = soHelper.ct.Id;
                soHelper.recordsToInsert.add(emailObj);
            }
        }

        // If it is not the new contact that we created now, we may have some old emails to be deleted
        if (!soHelper.newContact)
        {
            soHelper.recordsToDelete.addAll(soHelper.ct.Contact_Emails__r);
        }

        // If Emails are successfully loaded (NOT a failure or partial success), lets update the last loaded time
        if (response.isProfileEmailsSuccessfullyLoaded())
        {
            soHelper.ct.Email_Loaded_Time__c = Datetime.now();
        }

        return soHelper;
    }

    public static Contact_Email__c mapEmailDOToContactEmail(EmailDO email)
    {
        Contact_Email__c ctEmail = new Contact_Email__c();
        ctEmail.Domain_Identifier__c = email.unique_email_identifier;
        ctEmail.Email_Address__c = email.email_id;
        ctEmail.Status__c = email.status;
        ctEmail.Confirmation_Status__c = email.confirmation_status;
        ctEmail.Trust_Status__c = email.trust_status;
        ctEmail.Is_Primary__c = email.primary;

        ctEmail.Is_Active__c = false;
        ctEmail.Is_Confirmed__c = false;
        ctEmail.Is_Trusted__c = false;

        // Is Email Active?
        if (String.isNotBlank(email.status) && email.status.equalsIgnoreCase('active'))
        {
            ctEmail.Is_Active__c = true;
        }

        // Is Email Confirmed?
        if (String.isNotBlank(email.confirmation_status) && email.confirmation_status.equalsIgnoreCase('confirmed'))
        {
            ctEmail.Is_Confirmed__c = true;
        }

        // Is Email Trusted?
        if (String.isNotBlank(email.trust_status) && email.trust_status.equalsIgnoreCase('trusted'))
        {
            ctEmail.Is_Trusted__c = true;
        }

        return ctEmail;
    }
}