force-app/main/default/objects/Contact/fields/Phone_Loaded_Time__c.field-meta.xml
<CustomField>
    <fullName>Phone_Loaded_Time__c</fullName>
    <description>For cache TTL purposes</description>
    <inlineHelpText>For cache TTL purposes</inlineHelpText>
    <label>Phone Loaded Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/Contact_Phone__c.object-meta.xml
<CustomObject>
    <description>Phone numbers associated with an account</description>
    <label>Contact Phone</label>
    <nameField>
        <label>Contact Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Phone__c/fields/Confirmation_Status__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Status__c</fullName>
    <description>Confirmation status of the phone number in the profile</description>
    <inlineHelpText>Confirmation status of the phone number in the profile</inlineHelpText>
    <label>Confirmation Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Phone numbers associated with a contact</description>
    <inlineHelpText>Phone numbers associated with a contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Phones</relationshipLabel>
    <relationshipName>Contact_Phones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country code of the Phone - 1 for US, 91 for India and so on</description>
    <inlineHelpText>Country code of the Phone</inlineHelpText>
    <label>Country Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this phone primary?</description>
    <inlineHelpText>Is this phone primary?</inlineHelpText>
    <label>Is Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Is_Trusted__c.field-meta.xml
<CustomField>
    <fullName>Is_Trusted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Trusted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Phone_Id__c.field-meta.xml
<CustomField>
    <fullName>Phone_Id__c</fullName>
    <description>Unique identifier for this phone in the system of record</description>
    <inlineHelpText>Unique identifier for this phone in the system of record</inlineHelpText>
    <label>Phone Id</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Phone number</description>
    <inlineHelpText>Phone number</inlineHelpText>
    <label>Phone Number</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the phone number in the profile</description>
    <inlineHelpText>Current status of the phone number in the profile</inlineHelpText>
    <label>Status</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Tags_JSON__c.field-meta.xml
<CustomField>
    <fullName>Tags_JSON__c</fullName>
    <description>Tags associated with the Phone</description>
    <inlineHelpText>Tags associated with the Phone</inlineHelpText>
    <label>Tags JSON</label>
    <length>512</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Trust_Status__c.field-meta.xml
<CustomField>
    <fullName>Trust_Status__c</fullName>
    <description>Trust status of the Phone</description>
    <inlineHelpText>Trust status of the Phone</inlineHelpText>
    <label>Trust Status</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of phone number - like home/mobile/office/etc.,</description>
    <inlineHelpText>Type of phone number - like home/mobile/office/etc.,</inlineHelpText>
    <label>Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProfilePhoneAPI.cls
public class ProfilePhoneAPI {
    
    public static Customer360SO mapResponseToCustomer360SO(Customer360SO cx360SO, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('ProfilePhoneAPI:mapResponseToCustomer360SO - Mapping Phone Information');

        if (response.isProfilePhonesFailed() || (response.getCustomer360DO().profile == null) ||
           (response.getCustomer360DO().profile.phone_numbers == null) || (response.getCustomer360DO().profile.phone_numbers.size() == 0))
        {
            System.debug('Customer360 API response does not have any phone numbers');
            return cx360SO;
        }

        for (PhoneDO phone : response.getCustomer360DO().profile.phone_numbers)
        {
            cx360SO.primaryUser.phones.add(mapPhoneDOToContactPhone(phone));
        }

        return cx360SO;
    }

    public static ProfileAPI.InsertToSOHelper storeResponseInSObject(ProfileAPI.InsertToSOHelper soHelper, Customer360APIRequest request, Customer360APIResponse response)
    {
        System.debug('ProfilePhoneAPI:storeResponseInSObject - Storing Phone Information into SObject');

        if (response.isProfilePhonesFailed())
        {
            System.debug('Customer360 API did not successfully load any phone numbers');
            return soHelper;
        }

        List<PhoneDO> phones = response.getCustomer360DO().profile.phone_numbers;

        if (phones != null)
        {
            for (PhoneDO phone : phones)
            {
                Contact_Phone__c phoneObj = mapPhoneDOToContactPhone(phone);
                phoneObj.Contact__c = soHelper.ct.Id;
                soHelper.recordsToInsert.add(phoneObj);
            }
        }

        // If it is not the new contact that we created now, we may have some old phone numbers to be deleted
        if (!soHelper.newContact)
        {
            soHelper.recordsToDelete.addAll(soHelper.ct.Contact_Phones__r);
        }

        // If Phone numbers are successfully loaded (NOT a failure or partial success), lets update the last loaded time
        if (response.isProfilePhonesSuccessfullyLoaded())
        {
            soHelper.ct.Phone_Loaded_Time__c = Datetime.now();
        }

        return soHelper;
    }

    public static Contact_Phone__c mapPhoneDOToContactPhone(PhoneDO phone)
    {
        Contact_Phone__c ctPhone = new Contact_Phone__c();
        ctPhone.Phone_Id__c = phone.phone_id;
        ctPhone.Country_Code__c = phone.country_code;
        ctPhone.Phone_Number__c = phone.phone_number;
        ctPhone.Type__c = getPhoneType(phone.tags);
        ctPhone.Tags_JSON__c = JSON.serialize(phone.tags);
        ctPhone.Status__c = phone.status;
        ctPhone.Confirmation_Status__c = phone.confirmation_status;
        ctPhone.Trust_Status__c = phone.trust_status;
        ctPhone.Is_Primary__c = phone.primary;

        ctPhone.Is_Active__c = false;
        ctPhone.Is_Confirmed__c = false;
        ctPhone.Is_Trusted__c = false;
                
        // Is Phone Active?
        if (String.isNotBlank(phone.status) && phone.status.equalsIgnoreCase('active'))
        {
            ctPhone.Is_Active__c = true;
        }

        // Is Phone Confirmed?
        if (String.isNotBlank(phone.confirmation_status) && phone.confirmation_status.equalsIgnoreCase('confirmed'))
        {
            ctPhone.Is_Confirmed__c = true;
        }

        // Is Phone Trusted?
        if (String.isNotBlank(phone.trust_status) && phone.trust_status.equalsIgnoreCase('trusted'))
        {
            ctPhone.Is_Trusted__c = true;
        }

        return ctPhone;
    }

    private static String getPhoneType(List<String> tags)
    {
        if (tags == null) {
            return 'OTHER';
        }
        else if (tags.contains('MOBILE')) {
            return 'MOBILE';
        }
        else if (tags.contains('HOME')) {
            return 'HOME';
        }
        else if (tags.contains('WORK')) {
            return 'WORK';
        }
        else if (tags.contains('FAX')) {
            return 'FAX';
        }
        else {
            return 'OTHER';
        }
    }
}