force-app/main/default/objects/Pin__c/Pin__c.object-meta.xml
<CustomObject>
    <label>Pin</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>Pin Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pin__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pins</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pin__c/fields/Widget__c.field-meta.xml
<CustomField>
    <fullName>Widget__c</fullName>
    <label>Widget</label>
    <referenceTo>Widget__c</referenceTo>
    <relationshipLabel>Pins</relationshipLabel>
    <relationshipName>Pins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Widget__c/Widget__c.object-meta.xml
<CustomObject>
    <label>Widget</label>
    <nameField>
        <label>Widget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Widget__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WidgetController.cls
public with sharing class WidgetController {

    @AuraEnabled(cacheable=true)
    public static List<SObject> fetchWidgets(Id User, String SearchParam){
        if (String.isBlank(SearchParam)) {
            return [SELECT Id, Name, Tags__c, Icon__c, ObjectName__c, (SELECT User__c FROM Pins__r) FROM Widget__c WHERE Id IN (SELECT Widget__c FROM Pin__c WHERE User__c = :User)];
        }
        else {
            string param = '%' + SearchParam + '%';
            return [SELECT Id, Name, Tags__c, Icon__c, ObjectName__c, (SELECT User__c FROM Pins__r WHERE User__c = :User) FROM Widget__c WHERE Name LIKE :param OR Tags__c LIKE :param];
        }
    }

    @AuraEnabled(cacheable=false)
    public static Pin__c pinWidget(Id WidgetId, Id UserId){
        List<Pin__c> existingPin = [SELECT Id, Widget__c, User__c FROM Pin__c WHERE Widget__c = :WidgetID AND User__c = :UserID ORDER BY Id];
        if(existingPin.size()>0 ){
            System.debug('Return existing pin');
            return existingPin[0];
        }
        else {
            Pin__c pin = new Pin__c(Widget__c = WidgetID, User__c = UserID);
        	insert pin;
            System.debug('Return new pin');
        	return pin;
        }
    }

    @AuraEnabled(cacheable=false)
    public static void unpinWidget(Id WidgetId, Id UserId){
        List<Pin__c> existingPin = [SELECT Id, Widget__c, User__c FROM Pin__c WHERE Widget__c = :WidgetID AND User__c = :UserID ORDER BY Id];
        if(existingPin.size()>0 ){
            System.debug('Removing existing pin');
            delete existingPin;
        }
        return;
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> fetchAllWidgets(Id User){
        return [SELECT Id, Name, Tags__c, Icon__c, ObjectName__c, (SELECT User__c FROM Pins__r WHERE User__c = :User) FROM Widget__c];
    }
}